### ISSUE TITLE
I18n support

### ISSUE THREAD

**Issue by pkking** [fedora-copr/copr#2386]
Hi team,
Is there a i18n plan for copr frontend? Im glad to do some translations :)

**Comment by praiskup** [comment]
Thank you for the issue.

There's no such plan, yet.  This is waiting for some brave contributor!

**Comment by xsuchy** [comment]
At the beginning of Copr we discussed this and developers usually do not have a problem using English. Localized developer's tools usually bring more pain than usefulness. E.g., see localized man pages :(
I am going to close this issue as the core team will not work on this in foreseeable future. However, if you, or anyone else, will submit a pull request, we will do the review and merge it.
