### ISSUE TITLE
Backend tests fail for Rawhide/F38

### ISSUE THREAD

**Issue by FrostyX** [fedora-copr/copr#2388]
The `test_full_rpm_build_no_sign` fails on Rawhide/F38 with 

```
>       assert worker.job.built_packages == "example 1.0.14"
E       AssertionError: assert '' == 'example 1.0.14'
E         - example 1.0.14
```

Further down in the log, there is

```
stderr:
error: example-1.0.14-1.fc30.x86_64.rpm: Header V3 RSA/SHA1 Signature, key ID ac058ff1: BAD
error: example-1.0.14-1.fc30.x86_64.rpm: not an rpm package (or package manifest)
```

**Comment by praiskup** [comment]
Seems like rpm-sequoia related, I updated [the bug](https://bugzilla.redhat.com/show_bug.cgi?id=2141686)

**Comment by pmatilai** [comment]
> error: example-1.0.14-1.fc30.x86_64.rpm: Header V3 RSA/**SHA1** Signature, key ID ac058ff1: BAD
                                                                                                      

That's rawhide crypto policy, not rpm.

"update-crypto-policies --set DEFAULT:FEDORA32" to make it accessible, but you really shouldn't. There may also be a smaller hammer to achieve that, this isn't my home turf.

**Comment by pmatilai** [comment]
Note that it may still be related to Sequoia in that it's a new crypto-policy backend and perhaps it has different defaults than openssl. The relevant component in Fedora would be crypto-policies package.
