### ISSUE TITLE
copr server seems unhealthy state

### ISSUE THREAD

**Issue by mtasaka** [fedora-copr/copr#2393]
As of 2022-11-29 13:23 JST(=UTC+9), looks line copr server seems unhealthy Lots of queues are now stuck with "importing" state.

Would someone investigate the status? Thank you.

**Comment by praiskup** [comment]
indeed, thank you for the report:
```
Nov 29 00:52:43 copr-dist-git.aws.fedoraproject.org systemd[1]: copr-dist-git.service: systemd-oomd killed 1 process(es) in this unit.
Nov 29 00:52:43 copr-dist-git.aws.fedoraproject.org systemd[1]: copr-dist-git.service: Main process exited, code=killed, status=9/KILL
Nov 29 00:52:43 copr-dist-git.aws.fedoraproject.org systemd[1]: copr-dist-git.service: Failed with result 'oom-kill'.
Nov 29 00:52:43 copr-dist-git.aws.fedoraproject.org systemd[1]: copr-dist-git.service: Consumed 18min 40.747s CPU time.
```

**Comment by praiskup** [comment]
Also httpd was killed.  Restarted.  But we need to restart automatically.

**Comment by praiskup** [comment]
Also, the `/dev/zram0` swap must be disabled on all infrastructure because multiple swaps are [broken in kernel](https://bugzilla.redhat.com/show_bug.cgi?id=2051154)

**Comment by praiskup** [comment]
[zram0 swap disabled](https://pagure.io/fedora-infra/ansible/c/6dc43e2d2385d11be47822afc6c80e6838621e89?branch=main)

**Comment by praiskup** [comment]
See also #2410.  Apache is being OOM killed because of cgit, and when apache is down git clients can't clone which fails the builds  - that causes #2394.

**Comment by praiskup** [comment]
For now we did `systemctl disable systemd-oomd` on copr-dist-git.

**Comment by praiskup** [comment]
And `systemctl mask systemd-oomd.service` and `systemctl mask systemd-oomd.socket`.

**Comment by praiskup** [comment]
Useful docs are man oomd.conf and https://fedoraproject.org/wiki/Changes/EnableSystemdOomd

**Comment by mtasaka** [comment]
Once closing.
