### ISSUE TITLE
Every single cgit http request to copr-dist-git easts CPU for several seconds

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2410]
ssia

**Comment by praiskup** [comment]
My bet is `/etc/cgitrc` which does `include=/var/cache/cgit/repo-configuration.rc`.
In the production that file has 340MB.

**Comment by praiskup** [comment]
I think we should avoid starting 'cgit' binary for every single request.  We can keep the server processes for several minutes, for example ... (for newly imported packages, cgit will probably not work till restarted, but that sounds acceptable).

**Comment by praiskup** [comment]
Looking at some old [CZ school work](https://rtime.felk.cvut.cz/osp/student/mildedan/vysledek.pdf) presentation, it seems cgit isn't (or wasn't by that time) ready for FastCGI use-cases.  Namely it looks like it suffers from memory leaks.

Therefore I think the only option is to use the `MACRO EXPANSION` feature (see man 5 cgitrc).  We can e.g. have one include file per copr owner, or similar.

The problem is how to use it properly.  Not sure if we don't have to have our own cgit CGI wrapper.
Some env vars available for such a script:
```
GIT_PROJECT_ROOT=/var/lib/dist-git/git
GIT_HTTP_EXPORT_ALL=
HTTPS=on
HTTP_HOST=copr-dist-git.fedorainfracloud.org
HTTP_USER_AGENT=Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0
HTTP_ACCEPT=text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
HTTP_ACCEPT_LANGUAGE=en-US,en;q=0.5
HTTP_ACCEPT_ENCODING=gzip, deflate, br
HTTP_REFERER=https://copr-dist-git.fedorainfracloud.org/cgit/?ofs=715450
HTTP_DNT=1
HTTP_CONNECTION=keep-alive
HTTP_UPGRADE_INSECURE_REQUESTS=1
HTTP_SEC_FETCH_DEST=document
HTTP_SEC_FETCH_MODE=navigate
HTTP_SEC_FETCH_SITE=same-origin
HTTP_SEC_FETCH_USER=?1
HTTP_IF_MODIFIED_SINCE=Mon, 05 Dec 2022 14:03:59 GMT
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
SERVER_SIGNATURE=
SERVER_SOFTWARE=Apache/2.4.54 (Fedora Linux) OpenSSL/3.0.5
SERVER_NAME=copr-dist-git.fedorainfracloud.org
SERVER_ADDR=2600:1f18:8ee:ae00:41cc:53dc:b87b:2d8c
SERVER_PORT=443
REMOTE_ADDR=2a00:ca8:a1f:46a:c8af:eec6:7d27:5795
DOCUMENT_ROOT=/var/www/html
REQUEST_SCHEME=https
CONTEXT_PREFIX=/cgit
CONTEXT_DOCUMENT_ROOT=/var/www/cgi-bin/cgit
SERVER_ADMIN=root@localhost
SCRIPT_FILENAME=/var/www/cgi-bin/cgit
REMOTE_PORT=52370
GATEWAY_INTERFACE=CGI/1.1
SERVER_PROTOCOL=HTTP/1.1
REQUEST_METHOD=GET
QUERY_STRING=
REQUEST_URI=/cgit/willc/r-packages/R-covr.git/
SCRIPT_NAME=/cgit
PATH_INFO=/willc/r-packages/R-covr.git/
PATH_TRANSLATED=/var/www/html/willc/r-packages/R-covr.git/
```

**Comment by praiskup** [comment]
Idea: Could we drop the "list of all project page" (eventually useless for thousands of packages) and just keep direct links from our web-UI?

**Comment by praiskup** [comment]
Again downtime caused by this: https://pagure.io/fedora-infrastructure/issue/11174

**Comment by praiskup** [comment]
Worked-around with `chmod -x /var/www/cgi-bin/cgit` again.

**Comment by sergiomb2** [comment]
maybe just instead gives a page http 500  Internal Server Error , one page saying "our cgit is temporarily disabled because it consumes too much resources."

**Comment by tmzullinger** [comment]
> Idea: Could we drop the "list of all project page" (eventually useless for thousands of packages) and just keep direct links from our web-UI?

That seems like a good idea.  Adding a redirect (or any other method of serving some other page in place of the index URL) should keep cgit from being called to list the index.  (I'm assuming that's what causes the issue.)

I tested this change against the stock `/etc/httpd/conf.d/cgit.conf` with the following change:

```diff
--- cgit.conf.dist~	2020-03-13 19:49:52.000000000 -0400
+++ cgit.conf	2023-06-26 23:27:23.292803459 -0400
@@ -1,4 +1,7 @@
 Alias /cgit-data /usr/share/cgit
+<LocationMatch ^/cgit/?$>
+    RedirectMatch /cgit/? /
+</LocationMatch>
 ScriptAlias /cgit /var/www/cgi-bin/cgit
 <Directory "/usr/share/cgit">
     Require all granted
```

The order does matter.  But that allows direct links to work while redirecting requests to the cgit index.

The destination could possibly be a page which allowed someone to search for a repo, if anyone were inclined to write such a search tool and integrate it with the copr code.  But if it just went to a page which explained how to access the cgit repos if would be better than having it disabled entirely.  :)

For review, here's what that might look like as a patch against the fedora-infra ansible repo.  If that's something worth trying, I can submit it there.  (It's got a .txt extension because github bizarrely refused to allow me to upload it with a .patch extension.)

[0001-copr-dist-git-redirect-cgit-index-page-elsewhere.patch.txt](https://github.com/fedora-copr/copr/files/11877461/0001-copr-dist-git-redirect-cgit-index-page-elsewhere.patch.txt)

**Comment by juhp** [comment]
Yeah, I think the index is totally not necessary, but cgit access to individual repos is very valuable.

**Comment by praiskup** [comment]
Thank you for the patch and work! But I'm afraid it will not help. The problem is that (a) index file is too big and (b) that it is loaded for every single cgit request (not just querying the index page).

**Comment by praiskup** [comment]
Lemme experiment with this, though.

**Comment by praiskup** [comment]
OK, confirmed :-( every request loads the file (550MB) - and the bad thing is that the pre-generated list of repositories has to exist, otherwise cgit won't find those repositories at all.  The pattern current pattern is, for every single package, looks like:

```
[root@copr-dist-git ~][PROD]# head /var/cache/cgit/repo-configuration.rc -n30

repo.url=0x444d/hd-idle/golang-github-adelolmo-hd-idle.git
repo.name=0x444d/hd-idle/golang-github-adelolmo-hd-idle.git
repo.path=//var/lib/dist-git/git/0x444d/hd-idle/golang-github-adelolmo-hd-idle.git/
repo.owner=
repo.desc=Unnamed repository; edit this file 'description' to name the repository.
repo.section=
repo.enable-blame=0
repo.enable-commit-graph=0
repo.enable-log-filecount=0
repo.enable-log-linecount=0
repo.enable-remote-branches=0
repo.enable-subject-links=0
repo.enable-html-serving=0
repo.hide=0
repo.ignore=0
...
```

I'm sure we could at least make the file significantly smaller.

**Comment by praiskup** [comment]
I temporarily changed the format to:
```
repo.url=packit/teemtee-tmt-2174/tmt.git
repo.path=/var/lib/dist-git/git/packit/teemtee-tmt-2174/tmt.git/
```
This shrank the file to 94M, and it could actually help?

**Comment by tmzullinger** [comment]
Excellent!  Sorry I didn't catch that my changes wouldn't avoid the issue.
