### ISSUE TITLE
OpenID login doesn't work

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2418]
When I hit "login" link, with kerberos token taken, I get "504 gateway timeout".
https://pagure.io/fedora-infrastructure/issue/11025

**Comment by praiskup** [comment]
The same version of our software works fine on staging (against staging oid).

Not sure what is going on.  The `@oid.after_login()` hook is never called by Flask OpenID.

**Comment by praiskup** [comment]
I enabled production Fedora OpenID even on Fedora Copr stage, and it behaves the same way...  I think there's some difference between id.stg.fedoraproject.org vs. id.fedoraproject.org.

**Comment by FrostyX** [comment]
> I enabled production Fedora OpenID even on Fedora Copr stage, and it behaves the same way... I think there's some difference between id.stg.fedoraproject.org vs. id.fedoraproject.org.

The weird thing is that our docker container uses production id.fedoraproject.org and doesn't suffer this issue.

**Comment by FrostyX** [comment]
Deep, deep down in the python `openid` library, this is being called and timeouts

```python
import urllib.request

url = "http://frostyx.id.fedoraproject.org/"

# On STG server it works, uncomment the variable to make sure
# url = "http://frostyx.id.stg.fedoraproject.org/"

accept = 'text/html; q=0.3, application/xhtml+xml; q=0.5, application/xrds+xml'
headers = {
    'Accept': accept,
    'User-Agent': 'python-openid/3.1.0 (linux) Python-urllib/3.11',
}

req = urllib.request.Request(url, data=None, headers=headers)
resp = urllib.request.urlopen(req)
print(resp.status)
```

**Comment by praiskup** [comment]
Good job @FrostyX!

```
[root@copr-fe-dev ~][STG]# wget http://frostyx.id.fedoraproject.org/
--2022-12-07 19:09:52--  http://frostyx.id.fedoraproject.org/
Resolving frostyx.id.fedoraproject.org (frostyx.id.fedoraproject.org)... 2600:1f14:fad:5c02:3556:f9be:1874:bdc0, 2600:2701:4000:5211:dead:beef:fe:fed3, 2605:bc80:3010:600:dead:beef:cafe:fed9, ...
Connecting to frostyx.id.fedoraproject.org (frostyx.id.fedoraproject.org)|2600:1f14:fad:5c02:3556:f9be:1874:bdc0|:80...

And it hangs forever ... Doing wget -4 http://frostyx.id.fedoraproject.org/ works just fine.
```

This seems like the FAS ipv6 is broken, because ipv6 just works on our server.  Can you please report to the infra team?

**Comment by FrostyX** [comment]
I have submitted some feedback for the infra team in
https://pagure.io/fedora-infrastructure/issue/11025

Kevin says that they are planning to add IPv6 to iad2 early next year. Until then, I added the modified `gai.conf` into the ansible playbook, and consider this fixed.
