### ISSUE TITLE
User friendly message for appstream-builder fails

### ISSUE THREAD

**Issue by FrostyX** [fedora-copr/copr#2419]
The `appstream-builder` command it slow for larger repositories and it is a good idea to disable it. We should tell that to users in the build logs, instead of timeouting with a traceback

```
Sub-command failed
Traceback (most recent call last):
  File "/usr/bin/copr-repo", line 453, in main
    main_try_lock(opts, batch)
  File "/usr/bin/copr-repo", line 405, in main_try_lock
    main_locked(opts, batch, opts.log)
  File "/usr/bin/copr-repo", line 369, in main_locked
    add_appdata(opts)
  File "/usr/bin/copr-repo", line 234, in add_appdata
    run_cmd([
  File "/usr/lib/python3.11/site-packages/copr_backend/helpers.py", line 148, in run_cmd
    raise CommandException(exc_msg)
copr_backend.helpers.CommandException: Command '/usr/bin/timeout --kill-after=240 180 /usr/bin/appstream-builder --temp-dir=/var/lib/copr/public_html/results/@kdesig/kde-nightly/fedora-rawhide-aarch64/tmp --cache-dir=/var/lib/copr/public_html/results/@kdesig/kde-nightly/fedora-rawhide-aarch64/cache --packages-dir=/var/lib/copr/public_html/results/@kdesig/kde-nightly/fedora-rawhide-aarch64 --output-dir=/var/lib/copr/public_html/results/@kdesig/kde-nightly/fedora-rawhide-aarch64/appdata --basename=appstream --include-failed --min-icon-size=48 --veto-ignore=missing-parents --enable-hidpi --origin=@kdesig/kde-nightly' failed, exit code '124
```

**Comment by praiskup** [comment]
Please take a look at #2420, I promissed some time ago.  This is the first step;  second step should be to announce this and turn it off even for existing projects.

**Comment by FrostyX** [comment]
The #2420 fixes the issue for new projects but the current projects already have the appstream option enabled. I will consider this fixed once we either provide a user-friendly message or once we announce and disable appstream generating for all existing projects (and let users opt-in for it).

**Comment by praiskup** [comment]
Triage time: appstream builder is disabled by default nowadays, and likely going to be phased out once we move to PULP
