### ISSUE TITLE
OpenID Connect supported

### ISSUE THREAD

**Issue by pkking** [fedora-copr/copr#2422]
Hi again,
I notice that copr can be integrated with some openID group or kerberos infra
For now, our infra using a [OpenID Connect](https://openid.net/connect/) facility to support authentication, is it possiable for copr to support this spec?

**Comment by praiskup** [comment]
> Is it possiable for copr to support this spec?

Definitely possible, and desired (Fedora has OIDC instance that we could use, too).
But I'm afraid we'll need help with implementation.  Can you take a look?

There are two things that need to be done:
- server side -> copr-frontend -> it should be opt-in feature, configurable in `/etc/copr/copr.conf`
- client-side (python-copr and copr-cli) - the client authentication mechanism should be configurable too

**Comment by praiskup** [comment]
Note also [1800](https://pagure.io/copr/copr/issue/1800)

**Comment by pkking** [comment]
OIDC is fully and well supported in python world, we got [flask-pyoidc](https://github.com/zamzterz/Flask-pyoidc) and [pyoidc](https://github.com/OpenIDC/pyoidc), i'd like to introduce them into copr :)

**Comment by praiskup** [comment]
Sure, patches are welcome!  Note that (if not already present) the new dependencies need to be added to Fedora.

**Comment by pkking** [comment]
Is there a guide to add new pkgs into Fedora? @praiskup

**Comment by pkking** [comment]
> Is there a guide to add new pkgs into Fedora? @praiskup

Maybe i can try to make these pkgs avaliable in coprs?

**Comment by FrostyX** [comment]
> Maybe i can try to make these pkgs avaliable in coprs firstly?

That is a good idea, it will help you in many ways. 

But please note that we install packages only from Fedora repositories on our production servers, so you will have to get them into Fedora in order for us to use them. I am not saying it is a bad idea to install Copr packages on servers in general. Our case is different because we don't want to introduce a circular dependency in the sense that the production Copr instance would have to install packages from itself.

> Is there a guide to add new pkgs into Fedora?

If you already know how to write a .spec file and build RPM packages locally, this document describes how to get them into Fedora.
https://docs.fedoraproject.org/en-US/package-maintainers/Package_Review_Process/
You want to follow the "Contributor" part of the process.

**Comment by pkking** [comment]
Im working on this, firstly some pacakges need to be imported :) @FrostyX @praiskup 


[1]. My first package review: https://bugzilla.redhat.com/show_bug.cgi?id=2161003

**Comment by FrostyX** [comment]
> [1]. My first package review: https://bugzilla.redhat.com/show_bug.cgi?id=2161003

I am taking the review

**Comment by pkking** [comment]
> > [1]. My first package review: https://bugzilla.redhat.com/show_bug.cgi?id=2161003
> 
> I am taking the review
Some srpm links were refered to html links, already change to a raw link.

**Comment by praiskup** [comment]
FTR Dustin Minnich @ Red Hat commented:
> Can't contribute code but I think  https://authlib.org/  works with Flask

**Comment by FrostyX** [comment]
@pkking Hello, I sent you a private email regarding this issue but it might have gotten lost on its way.

Do you think https://authlib.org would work for you? It is already in Fedora (`python3-authlib`) so it might be the easiest solution. If not, please let me know what packages you still want to get reviewed.

**Comment by pkking** [comment]
Will give authlib a try😀

**Comment by pkking** [comment]
Hi @FrostyX @praiskup , these day i tried [authlib](https://github.com/lepture/authlib), but seems encountered https://github.com/lepture/authlib/issues/462 with our provider, im not so familiar with JWT&JWS, so still need some time to try to get it work.

**Comment by praiskup** [comment]
Awesome!  Thanks for the good news.

Were you able to handle groups?

> This will be the first step and need some of your help as i dont know the use case in RedHat provider :)

Don't worry about it, it's not important at this point (we have two, one for the private instance, one for Fedora Copr).
But we'll handle that;  the point is to keep the oidc "opt-in" so we can do follow-ups.

**Comment by pkking** [comment]
> Were you able to handle groups?

The group is bit tricky, as openid connect spec seems do not have a group terms,
It will need some design to cover both our cases :)
