### ISSUE TITLE
copr server seems unhealthy state again

### ISSUE THREAD

**Issue by mtasaka** [fedora-copr/copr#2424]
Again as of 2022/12/06 12:42 JST (=UTC+9h), copr server again seems unhealthy. 80+ tasks are currently under "pending" seemingly being not being processed, although only 5 task is "running".

Would you again investigate the current status? Thank you!

**Comment by mtasaka** [comment]
As of 2022/12/06 15:32 JST, 207 tasks are "pending" and only 1 task is "running".

**Comment by FrostyX** [comment]
Thank you for the report @mtasaka,
I unintentionally caused this when trying to fix the broken OpenID login issue.
Copr should be healthy now.
