### ISSUE TITLE
IPv6-only builders are IMHO misconfigured 

### ISSUE THREAD

**Issue by FrostyX** [fedora-copr/copr#2426]
Sorry for abusing the upstream issue tracker for ansible issues of the Fedora Copr instance.

IMHO our IPV6-only builders don't have the network configured properly. 

I can see IPv6 addresses on eth0 and eth1

```
[root@copr-hv-x86-64-01-dev-XXX ~]# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 52:54:00:XX:XX:XX  txqueuelen 1000  (Ethernet)
        ...

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::2adc:XXX:XXXX:XXXX  prefixlen 64  scopeid 0x20<link>
        inet6 2620:52:3:1:XXXX:XXXX:XXXX:XXXX  prefixlen 128  scopeid 0x0<global>
        ether 52:54:XX:XX:XX:XX  txqueuelen 1000  (Ethernet)
        ...
```

But there is no default gateway

```
[root@copr-hv-x86-64-01-dev-00000848-20221201-194425 ~]# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
```

There isn't any chance for them to `curl` anything? Or is it?

**Comment by FrostyX** [comment]
My bad, I should have used `route -6`
But I still have issues to `curl` anything, so keeping open.

**Comment by FrostyX** [comment]
The issue was caused by a missing DNS configuration. The `/etc/resolv.conf` was empty. I manually added

```
nameserver 2001:4860:4860::8888
nameserver 2001:4860:4860::8844
```

and `ping` and `curl` works fine. I think we need to add this into our builder playbooks.

**Comment by xsuchy** [comment]
Isn't this fault of AWS or NetworkManager? This should be set automatically from DHCP6.

**Comment by kenyon** [comment]
`ifconfig` and `route` are deprecated on Linux, and sometimes give confusing or incorrect output. The iproute2 commands are the replacements: https://baturin.org/docs/iproute2/

**Comment by FrostyX** [comment]
I think this was a duplicate of #2433
