### ISSUE TITLE
fedora-eln builds failing for not having the epel-rpm-macros common for the RHEL

### ISSUE THREAD

**Issue by xambroz** [fedora-copr/copr#2427]
Hello,
some of my packages fail because they are missing epel-rpm-macros in the build repository.
As ELN builds otherwise mimic the RHEL, please would it be possible to add epel-rpm-macros there?

For example:
https://download.copr.fedorainfracloud.org/results/rebus/infosec/fedora-eln-x86_64/05096388-radare2/root.log.gz

Thank you
Michal Ambroz

**Comment by praiskup** [comment]
Hi @xambroz, can you please report this to https://github.com/fedora-eln/eln/issues ?

**Comment by sgallagher** [comment]
Fedora ELN is not EPEL. It's an early view of RHEL 10. It is not expected to have epel-rpm-macros and it would be inappropriate for it to do so.

That said, if there are macros from EPEL that you think are worth adding to RHEL 10, I suggest submitting them to the `redhat-rpm-config` package in Rawhide, which will be inherited into ELN.
