### ISSUE TITLE
armhfp builds failing with out of memory error on dnf install

### ISSUE THREAD

**Issue by xsuchy** [fedora-copr/copr#2429]
Can we investigate why these builds fails?
See
https://github.com/packit/packit-service/issues/1798
https://dashboard.packit.dev/results/copr-builds/548596

**Comment by TomasTomecek** [comment]
I wonder if this is related to the amount of load happening on the arm builders.

**Comment by FrostyX** [comment]
@xsuchy, I can reproduce this locally:

```
$ sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2022-70f96b283e
$ /usr/bin/copr-rpmbuild --verbose --drop-resultdir --task-url https://copr.fedoraproject.org/backend/get-build-task/5079689-fedora-36-armhfp --chroot fedora-36-armhfp

fedora                                                         6.2 MB/s |  76 MB     00:12    
updates                                                        3.4 MB/s |  28 MB     00:08    
Out of memory allocating 671088640 bytes!
qemu: uncaught target signal 6 (Aborted) - core dumped

It looks like a mock issue to me.

**Comment by xsuchy** [comment]
I have reproduced this with just DNF. Filed 
https://bugzilla.redhat.com/show_bug.cgi?id=2152259

**Comment by praiskup** [comment]
> I wonder if this is related to the amount of load happening on the arm builders.

Just to answer @TomasTomecek, I don't think so.  Aarch64 is built in AWS (natively), while armhfp is built using our x86_64 builders (emulated).
