### ISSUE TITLE
Homepage user count issue

### ISSUE THREAD

**Issue by pkking** [fedora-copr/copr#2448]
Recently i notice our new deployed homepage displayed a wrong user count like `openEuler Copr hosts 4 projects from
0 openEuler contributors`, i checked the db, there are 2 user records, should `get_multiple_with_projects` go without `~` ?
```
    @classmethod
    def get_multiple_with_projects(cls):
        """
        Return all users that have at least one project (deleted projects
        counts as well)
        """
        return User.query.filter(~User.coprs.any())
```

**Comment by xsuchy** [comment]
@FrostyX this was part of https://pagure.io/copr/copr/pull-request/1970#
Do you remember why the tilda? I agree with @ppking that it does not make sense there.
