### ISSUE TITLE
build_proxy.create_from_distgit does not use default dist-fit for package

### ISSUE THREAD

**Issue by tstellar** [fedora-copr/copr#2455]
Take this example program:

```
from copr.v3 import Client

owner = 'tstellar'
project = 'dist-git-test'
package = 'a52dec'
committish = 'c9s'
config_file = 'fedora.cfg'

client = Client.create_from_config_file(config_file)
client.project_proxy.add(owner, project, ['fedora-37-x86_64'])
pkg_data = { "distgit" : 'centos-stream', 'committish' : committish }
client.package_proxy.add(owner, project, package, 'distgit', pkg_data)
client.build_proxy.create_from_distgit(owner, project, package, committish = committish
```

The create_from_distgit call fails here, because it tries to use the fedora dist-git URL instead of the 'centos-stream' URL.  I would expect that if distgit is not specified, then it would fallback to the distgit value associated with the pakcage.

**Comment by praiskup** [comment]
Thank you for the report!

The `build_proxy.create_from_distgit` api call doesn't require a prior creation of the package by `package_proxy.add()`.  It creates the build on its own -> therefore you have to specify the  [distgit instance](https://github.com/fedora-copr/copr/blob/d1c77fc9627181a2a5851d3bc6f193c2b0f66320/frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_builds.py#L235).

Alternatively, when you have the package defined already, you can [just rebuild it](https://github.com/fedora-copr/copr/blob/d1c77fc9627181a2a5851d3bc6f193c2b0f66320/cli/copr_cli/main.py#L919-L921) without specifying anything else than the package name.

**Comment by tstellar** [comment]
> Thank you for the report!
> 
> The `build_proxy.create_from_distgit` api call doesn't require a prior creation of the package by `package_proxy.add()`. It creates the build on its own -> therefore you have to specify the [distgit instance](https://github.com/fedora-copr/copr/blob/d1c77fc9627181a2a5851d3bc6f193c2b0f66320/frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_builds.py#L235).
> 
> Alternatively, when you have the package defined already, you can [just rebuild it](https://github.com/fedora-copr/copr/blob/d1c77fc9627181a2a5851d3bc6f193c2b0f66320/cli/copr_cli/main.py#L919-L921) without specifying anything else than the package name.

OK, I see, so I'm just using the wrong function and should use package_proxy.build() instead.

**Comment by praiskup** [comment]
OK, closing as resolved.  Thank you.
