### ISSUE TITLE
Limit download-build to fedora-review files

### ISSUE THREAD

**Issue by FrostyX** [fedora-copr/copr#2459]
We have `copr download-build <id>` command to download all build results. It is now possible, to filter the results to download only RPM packages using `--rpms` parameter and/or spec file using the `--spec` parameter.

I would like to add a `--fedora-review` or `--review` option to download only the `fedora-review` results.

**Comment by praiskup** [comment]
This is nice to have for the Fedora Review Service.

**Comment by FrostyX** [comment]
This might not be an easyfix after all. Currently, we download the build results using `wget`

```python
cmd = ['wget', '-r', '-nH', '--no-parent', '--reject', '"index.html*"', '-e', 'robots=off', '--no-verbose']
```

Filtering to only spec files and/or RPMs is done by

```python
if args.rpms:
    cmd.extend(["-A", "*.rpm"])

if args.spec:
    cmd.extend(["-A", "*.spec"])
```

So I thought it would be as easy as

```python
if args.review:
    cmd.extend(["-A", "fedora-review/*"])
```

but that doesn't work.

**Comment by praiskup** [comment]
Would some dummy solution like `-A review.txt -A rpmlint.xt ... ` work?

**Comment by FrostyX** [comment]
Nope, it downloads nothing :-/
