### ISSUE TITLE
unable to set chroot-specific configuration "additional_modules"

### ISSUE THREAD

**Issue by TomasTomecek** [fedora-copr/copr#2463]
We have just implemented configuration of chroot-specific options in Packit. Unfortunately, getting this exception:

> Module name 'foreman:el8 ruby:2.7 nodejs:17' must consist of two parts separated with colon, e.g. module:stream

Which is strange, because this is the call we are making:

```
[2023-01-10 15:29:48,061: INFO/ForkPoolWorker-1] Trying to get packit-stg/TomasTomecek-foreman-1 Copr project. The project will be created if it does not exist.
[2023-01-10 15:29:48,312: INFO/ForkPoolWorker-1] There is chroot-specific configuration for centos-stream-8-x86_64
[2023-01-10 15:29:48,562: INFO/ForkPoolWorker-1] Update packit-stg/TomasTomecek-foreman-1 centos-stream-8-x86_64: {'additional_repos': ['http://koji.katello.org/releases/yum/foreman-nightly/el8/x86_64/'], 'additional_modules': ['foreman:el8', 'ruby:2.7', 'nodejs:17']}
```

is this syntax wrong?

```
'additional_modules': ['foreman:el8', 'ruby:2.7', 'nodejs:17']
```

Context: https://github.com/TomasTomecek/foreman/pull/1/checks?check_run_id=10555208826

**Comment by praiskup** [comment]
Tha API documentation has a bug from eece7ac2724b1289a3069095a286884db0cc90b3 - the API option accepts a comma-separated list of modules, same as the Copr cli:

    $ copr edit-chroot --help | grep -A2 -- '^  --modules' 
      --modules MODULES     comma separated list of modules that will be enabled
                            or disabled in the given chroot, e.g.
                            'module1:stream,!module2:stream'

**Comment by praiskup** [comment]
Thank you for the report!

**Comment by evgeni** [comment]
@praiskup but the `get-chroot` call gives an array?

```console
% copr get-chroot @theforeman/pr-testing-playground/centos-stream-8-x86_64
{
    "additional_modules": [
        "ruby:2.7,",
        "nodejs:12,",
        "foreman:el8"
    ],
    "additional_packages": [],
    "additional_repos": [],
    "comps_name": null,
    "delete_after_days": null,
    "isolation": "unchanged",
    "mock_chroot": "centos-stream-8-x86_64",
    "ownername": "@theforeman",
    "projectname": "pr-testing-playground",
    "with_opts": [],
    "without_opts": []
}
```

That seems inconsistent?

**Comment by TomasTomecek** [comment]
I only just noticed that the list also contains the commas.

Thank you, I'm going to update this in Packit.

**Comment by praiskup** [comment]
> @praiskup but the get-chroot call gives an array?

Indeed, another glitch.  What do you think we should do about that?  Keep the array and drop the commas, or return the comma-separated string?

**Comment by praiskup** [comment]
I mean, this will require **some** backward incompatible fix no matter what.

**Comment by evgeni** [comment]
Given the data is later interpreted as a list, I think I would prefer it to be exposed everywhere as a list.

But I am also not the one who has to implement it (neither on the copr side, nor on the packit side), so maybe not the loudest voice to hear to :)

**Comment by TomasTomecek** [comment]
My expectation was that I would pass a list of str there:

```
    "additional_modules": [
        "ruby:2.7",
        "nodejs:12",
        "foreman:el8"
    ],
```

this is also fine though less clear:
```
    "additional_modules": "ruby:2.7,nodejs:12,foreman:el8"
```

I can see you store it as a string in DB:

https://github.com/fedora-copr/copr/blob/main/frontend/coprs_frontend/coprs/models.py#L1646

I think it's okay to keep it as the string everywhere :) just let me know what you chose so I can do that in Packit as well.

**Comment by praiskup** [comment]
Eventually, it should be OK to keep using string, but also accept the array format (preferred by @forstyx).  I updated the PR.  The PR also fixes the GET requests -> removing the trailing commas.
