### ISSUE TITLE
RHEL chroots only support x86_64

### ISSUE THREAD

**Issue by karelvanhecke** [fedora-copr/copr#2472]
Currently RHEL chroots for 7, 8 & 9 are only available for x86_64 architectures. 
EPEL (which is RHEL + EPEL) already supports architectures other than x86_64. Is there any reason only the x86_64 architecture is enabled for the RHEL chroots?

**Comment by praiskup** [comment]
We try not to enable chroots nobody needs just to save some storage.  These architectures for RHEL were not requested so far.  What architectures are you interested in?

**Comment by karelvanhecke** [comment]
I'd like to build against AARCH64 for RHEL 9.

**Comment by praiskup** [comment]
The chroot has been added.  Happy building!
