### ISSUE TITLE
Don't rebuild the same package version again (when rebuild with Anitya is on)

### ISSUE THREAD

**Issue by befeleme** [fedora-copr/copr#2506]
Repo configuration: Build method: PyPI, spec creator: pyp2spec, autorebuild with Anitya: on.

In @copr/PyPI it happens that a package is repeatedly built with the same version, see for example:
https://copr.fedorainfracloud.org/coprs/g/copr/PyPI/package/python-openapi-core/
https://copr.fedorainfracloud.org/coprs/g/copr/PyPI/package/python-assemblyline-core/

This is also an issue for packages that were built successfully:
https://copr.fedorainfracloud.org/coprs/g/copr/PyPI/package/python-pulp-maven-client/

If a package was already attempted to build, it most probably shouldn't resubmit itself again and again.

**Comment by praiskup** [comment]
I can see in the log:
```
name: assemblyline-core, latest_build_version: 4.3.1~~dev109-1, new_updated_version 4.3.1.dev109
```
So we are mismatching the RPM version with the PyPI version. I don't think it matters to much because we now skip the pre-release versions anyway.  But just to make the code a bit cleaner, let's stop even comparing the last build version with a pre-release PyPI version.
