### ISSUE TITLE
PID1 problem - backend waitting for ssh multiplexing process

### ISSUE THREAD

**Issue by pkking** [fedora-copr/copr#2518]
Hi, im facing a problem in our container environment.
Each time i start a new build, the rpm build task will hang minutes after the srpm build task finished.
After some investigations, i found something:

1. when i started a build task, a ssh keepalive process will hold the connection to the builder, and the process's parent is 1(which is `copr-backend`)
2. when copr-rpmbuild finished, the backend task will call `os.waitpid` waiting all the children and it will not return until the ssh keepalive timeout(which is 900s in the builder ssh config)
3. after sometime, the ssh process exit and the rpm build tasks continue.

Seems the `os.waitpid` will be blocked by the ssh keepalive process !!

My workaroud is unshare the PID namespace(add  `sharePidNamespace: true` in deplyment) with all containers in backend pod, but im not a k8s expert, so any suggestion appreicated!

**Comment by praiskup** [comment]
Thank you for the report!

What keepalive process do you have in mind?

**Comment by pkking** [comment]
> Thank you for the report!
> 
> What keepalive process do you have in mind?

in my env, the `ps -ef` output:
```
copr           1       0  0 Jan30 ?        00:00:12 Build dispatcher - processing tasks
copr         162       1 10 06:29 ?        00:00:00 Builder for task 17: Job 17, host info: ResallocHost, ticket_id=75, hostname=10.0.0.157 (command: /usr/bin/copr-backend-process-build --daemon --build-id 17 
copr         167       1  0 06:29 ?        00:00:00 ssh: /home/copr/ssh_socket_10.0.0.157_22_root [mux]
copr         169     146  0 06:29 pts/1    00:00:00 ps -ef
```
the process `ssh: /home/copr/ssh_socket_10.0.0.157_22_root [mux]` will stay for miniutes and since its PPID is 1(our backend process), when backend all `os.waitpid` will wait until the ssh process exit, the can be reproduce in our k8s config, i think in openshift env its the same.

**Comment by pkking** [comment]
Finally find the [problem](https://stackoverflow.com/questions/44316361/difference-between-docker-entrypoint-and-kubernetes-container-spec-command), the k8s config using `command: ["/run-backend", "--sign-host", "copr-keygen", "/usr/bin/copr-run-dispatcher", "builds"]` lauched the backend directly, which should be launched by tini in pod.

**Comment by praiskup** [comment]
But there's ENTRYPOINT with /usr/bin/tini, what am I missing?

**Comment by pkking** [comment]
> But there's ENTRYPOINT with /usr/bin/tini, what am I missing?

The ENTRYPOINT in DOCKERFILE will be overwritten by the `command` in k8s yaml, so in our pod, the `command: ["/run-backend", "--sign-host", "copr-keygen", "/usr/bin/copr-run-dispatcher", "builds"]` cause the backend process start as `PID 1`

[As a note in k8s doc](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/)
> Note: The command field corresponds to entrypoint in some container runtimes.

**Comment by praiskup** [comment]
I assume we have to drop ENRYPOINTs, and keep just COMMANDs that will use `tini` directly.  Am I right?  If so, could you please fix the Dockerfiles?

**Comment by pkking** [comment]
The dockerfile is ok, ENRYPOINT launch the tini and CMD will then run it as a child process under tini.
The backend.yml need to be fixed, because the ENRYPOINT in dockerfile will be replaced by k8s [command](https://github.com/fedora-copr/copr/blob/357d80e759962183e0832efe87e29c641884a4fd/openshift/services/backend.yml.j2#L139) directive, which will start backend directly. But im not sure this will also happend in openshift scenario, if you can test to confirm, i'd like to make a pr :)

**Comment by praiskup** [comment]
But even [backend.yaml explicitly overrides command statements](https://github.com/fedora-copr/copr/blob/a9609d802486311d9ca3948212c5a54d4069ee3f/kubernetes/kustomize/backend.yaml#L72).  What am I missing?

**Comment by pkking** [comment]
Oh, sorry for missing the context, the code in this repo is a bit outdated, we are using [this](https://github.com/opensourceways/infra-openeuler/blob/8b8fa2e41c09f7d825224312f9deca30eb17168d/applications/openeuler-cn4-copr/copr-backend.yaml#LL99)

**Comment by praiskup** [comment]
Ok, I tested the OpenShift case -> and tini is not visible in `ps aux`.  So it appears ENTRYPOINT is ignored there as well.

**Comment by pkking** [comment]
Gotcha, i will make a PR to fix both kubernetes and openshift :)

**Comment by praiskup** [comment]
The images are to be updated (no automatic builds), but they **are** generated from the Dockerfiles within `./docker` subdirectory.
