### ISSUE TITLE
Web UI, sorting builds by build time does not work

### ISSUE THREAD

**Issue by hroncok** [fedora-copr/copr#2519]
![screenshot](https://user-images.githubusercontent.com/2401856/215458565-737d0938-50df-4b70-a46d-3b1352649add.png)

The sort appears to be quite arbitrary. When I sort in the other order, I get the pending builds first and the order seems to reverse-match the one on the screenshot (but I haven't checked that thoroughly).

**Comment by praiskup** [comment]
thank you for the report
