### ISSUE TITLE
Weird trend in copr-backend storage consumption

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2523]
See the stats:
https://copr-be.cloud.fedoraproject.org/stats/distro.html

We increased storage consumption a lot within the last four weeks.  We need to understand why, and break the trend.
This might block a Rawhide to F38 branching task.

![Screenshot_20230202_125639](https://user-images.githubusercontent.com/3277839/216318405-c6f5745c-9eb6-47eb-9be6-db39f22f6336.png)

**Comment by praiskup** [comment]
The storage consumption is now alarming IMO.  2.8T remains

**Comment by FrostyX** [comment]
2.5T remains, and nagios started reporting warnings.

**Comment by praiskup** [comment]
https://nagios.fedoraproject.org/nagios/cgi-bin//extinfo.cgi?type=2&host=copr-be.aws.fedoraproject.org&service=Disk+space+on+Copr+Backend+used+for+build+results

**Comment by praiskup** [comment]
This seems to be related to the weird [increase](https://copr-be.cloud.fedoraproject.org/stats/projects.html) of [xsnrg/indi-3rdparty-bleeding](https://copr.fedorainfracloud.org/coprs/xsnrg/indi-3rdparty-bleeding/).

@xsnrg can you please take a look why your project consumes now +2T compared to the previous month?
Also, is it possible to start packaging differently - e.g. unbundling?  I'm not sure why it eats so much.
TBH there are not so many packages, but they are built relatively frequently and they are large.

```
[root@copr-be fedora-rawhide-x86_64][PROD]# du --max-depth=1 -h | grep -- -aok$
313M    ./05459020-indi-aok
312M    ./05288200-indi-aok
410M    ./05522800-indi-aok
313M    ./05459190-indi-aok
313M    ./05459132-indi-aok
313M    ./05458852-indi-aok
313M    ./05496928-indi-aok
313M    ./05508305-indi-aok
313M    ./05351754-indi-aok
313M    ./05458908-indi-aok
313M    ./05459076-indi-aok
410M    ./05522931-indi-aok
410M    ./05522613-indi-aok
410M    ./05522865-indi-aok
410M    ./05518992-indi-aok
312M    ./05290128-indi-aok
312M    ./05290285-indi-aok
313M    ./05394952-indi-aok
312M    ./05290214-indi-aok
313M    ./05502834-indi-aok
313M    ./05373270-indi-aok
313M    ./05362774-indi-aok
313M    ./05371872-indi-aok
313M    ./05458964-indi-aok
312M    ./05304200-indi-aok
410M    ./05517507-indi-aok
312M    ./05329526-indi-aok
```

All of those ^^^ were built in the last 14 days -> which means we still [preserve them](https://docs.pagure.org/copr.copr/user_documentation.html#how-long-do-you-keep-the-builds).

There are 1500 directories in the rawhide chroot with >= 100M, but in average is 300M, which brings is an extraordinarily big average value.

If there's nothing that can be done in the project itself, there are other options:
- we can set e.g. max number of builds per package to 3 (but after three consecutive failures the package would disappear from the repository)
- we can lower the build preservation period to say 3 days for this project

Also, while working on #2536, we should do something about this as well (I can see there are
2 forks already - even though the forks might be incomplete, dunno).

**Comment by praiskup** [comment]
@xsnrg ping on this ^^

**Comment by xsnrg** [comment]
Hello all. There are quite a few things at play here. First, there has been more activity around trying to make sure all the packages are built. Some were missing copr configs, so there are just more packages period.

Next, I added builds for aarch64 where before I was only building x86-64. This likely doubled (or more?)

I have also been getting a large number of failed builds for reasons that do not seem to be related to the code. I haven't had time to track this down yet, but there have been a lot of rebuilds. It is cases of 6 successful architecture builds, and one random failure that when re-run is fine. Here is an example: https://copr.fedorainfracloud.org/coprs/xsnrg/indi-3rdparty-bleeding/package/indi-apogee/

I keep 10 builds, which I realize is a high number, but as you said, when you have failures, you could end up without a working package. If we could change this to keep a smaller number of builds, but always keep the most recent successful one, that would be great, and would allow me to reduce the number of builds kept.

As it is, I can go through and reduce to 5, which should cut storage down a good deal for the things in my control. If there are automatic retention things I cannot adjust, as mentioned, then those adjustments are options as well.

I will change everything to 5 now.

Jim

**Comment by xsnrg** [comment]
Now that I am looking at these, the `max builds` setting does not seem to be respected. Is the garbage collector running okay? Some configs have 51 builds showing.

**Comment by praiskup** [comment]
@xsnrg thank you for helping us here!

> Now that I am looking at these, the max builds setting does not seem to be respected. Is the garbage collector running okay? Some configs have 51 builds showing.

The garbage collector is run overnight, so it takes some time till your
change gets processed.  And whatever you did, it actually helped us a bit
(we got ~500G free space).  But obviously, there is also some problem
because at least [indi-apogee](https://copr.fedorainfracloud.org/coprs/xsnrg/indi-3rdparty-bleeding/package/indi-apogee/) package is not removed.  I'll investicate.

**Comment by praiskup** [comment]
Uhhh, the garbage collector indeed fails:

```
Traceback (most recent call last):
  File "/usr/share/copr/coprs_frontend/manage.py", line 139, in <module>
    app.cli()
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/copr/coprs_frontend/manage.py", line 105, in wrapper
    sys.exit(bool(function(*args, **kwargs)))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/copr/coprs_frontend/commands/__init__.py", line 10, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/share/copr/coprs_frontend/commands/clean_old_builds.py", line 15, in clean_old_builds
    BuildsLogic.clean_old_builds()
  File "/usr/share/copr/coprs_frontend/coprs/logic/builds_logic.py", line 1300, in clean_old_builds
    cls.delete_build(build.copr.user, build)
  File "/usr/share/copr/coprs_frontend/coprs/logic/builds_logic.py", line 1165, in delete_build
    cls.check_build_to_delete(user, build)
  File "/usr/share/copr/coprs_frontend/coprs/logic/builds_logic.py", line 1151, in check_build_to_delete
    raise InsufficientRightsException(
coprs.exceptions.AccessRestricted: You are not allowed to delete build `5212532`.
```

**Comment by xsnrg** [comment]
The space freed was just manually removing hundreds of builds at a time. It sounds like the automation failing is the larger issue. Is there no alerting on failed runs?

**Comment by xsnrg** [comment]
I am experiencing more and more backend failures with Createrepo even though the front end build is successful. I am now wondering if this is due to the number of builds more than anything. If I have time tonight, I will manually remove builds while we wait on the PR to get merged for the nightly cron job to work again.
```  File "/usr/lib/python3.11/site-packages/copr_backend/helpers.py", line 149, in run_cmd
    raise CommandException(exc_msg)
copr_backend.helpers.CommandException: Command '/usr/bin/timeout --kill-after=240 180 /usr/bin/appstream-builder --temp-dir=/var/lib/copr/public_html/results/xsnrg/indi-3rdparty-bleeding/fedora-38-x86_64/tmp --cache-dir=/var/lib/copr/public_html/results/xsnrg/indi-3rdparty-bleeding/fedora-38-x86_64/cache --packages-dir=/var/lib/copr/public_html/results/xsnrg/indi-3rdparty-bleeding/fedora-38-x86_64 --output-dir=/var/lib/copr/public_html/results/xsnrg/indi-3rdparty-bleeding/fedora-38-x86_64/appdata --basename=appstream --include-failed --min-icon-size=48 --veto-ignore=missing-parents --enable-hidpi --origin=xsnrg/indi-3rdparty-bleeding' failed, exit code '124


[2023-02-16 19:02:44,221][ ERROR][PID:1699490] Createrepo failed```

**Comment by praiskup** [comment]
> The space freed was just manually removing hundreds of builds at a time.

Thank you for this!

> It sounds like the automation failing is the larger issue. Is there no alerting on failed runs?

There is not. :(

> I am experiencing more and more backend failures with Createrepo even though the front end build is successful.

Please turn off the appstream metadata (project settings).  This is a known issue;  appstream-builder is
very I/O demanding and it simply takes too long for too large/too many packages.

**Comment by xsnrg** [comment]
> Please turn off the appstream metadata (project settings). This is a known issue; appstream-builder is very I/O demanding and it simply takes too long for too large/too many packages.

done.
