### ISSUE TITLE
Rubygem rebuild jump into a edit page

### ISSUE THREAD

**Issue by pkking** [fedora-copr/copr#2532]
Seems the rubyGem source type package will redirect the rebuild button to a edit page, user can manually add a build but cannot rebuild a existed package, want to know why this, is there any background i need to know?

**Comment by praiskup** [comment]
Thank you for the report, this is a bug.  It should point you to a rebuild page.  Patches are welcome!

**Comment by praiskup** [comment]
Hint given by the page:

    Package rubygem-0xffffff doesn't have the default source method set,
    but it is required for the rebuild request. Please configure some source
    method first
