### ISSUE TITLE
searching with whoosh in Fedora Copr is too slow

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2534]
Follow-up from [the red hat bug 2168394](https://bugzilla.redhat.com/show_bug.cgi?id=2168394).

The Fedora Copr search is too slow.  The Python Whoosh library behind the
search box is probably slow by design for reasonably large databases and
[doesn't scale](https://github.com/whoosh-community/whoosh/issues/554) [well](https://groups.google.com/g/whoosh/c/QM_P8cGi4v4/m/pZv-zxkFBQAJ).

    $ du --max-depth=0 -h /var/lib/copr/data/whooshee/copr_whoosheer
    568M    /var/lib/copr/data/whooshee/copr_whoosheer

It seems reasonably big, even though we use just one whoosheer.  And when being
used, the process memory consumption goes to unreasonable sizes.  Single query
means ~3GB of eaten RAM - and the memory is not used wisely actually (multiple
requests can end up with >= 8GB and so on).

We can either consider optimizing the searching (smaller DB, dedicate a running daemon
with preloaded DB in memory, fix leaks etc.) or migrate somewhere else (our own
hosted lucene-based stuff, use the AWS cloudsearch service, revamp elasticsearch).

We should keep whoosh as opt-in, the instance we have in Red Hat is reasonably fast
with Whoosh (smaller DB).

**Comment by praiskup** [comment]
Short term workaround for the performance issue :-(

```patch
diff --git a/frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_projects.py b/frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_projects.py
index 860f04b1e3..6e7dba2979 100644
--- a/frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_projects.py
+++ b/frontend/coprs_frontend/coprs/views/apiv3_ns/apiv3_projects.py
@@ -100,6 +100,8 @@ def get_project_list(ownername=None, **kwargs):
 @query_params()
 # @TODO should the param be query or projectname?
 def search_projects(query, **kwargs):
+    raise BadRequest("Searching in Fedora Copr is too demanding and is temporarily disabled: "
+                     "https://github.com/fedora-copr/copr/issues/2534")
     try:
         search_query = CoprsLogic.get_multiple_fulltext(query)
         paginator = Paginator(search_query, models.Copr, **kwargs)
diff --git a/frontend/coprs_frontend/coprs/views/coprs_ns/coprs_general.py b/frontend/coprs_frontend/coprs/views/coprs_ns/coprs_general.py
index 9550639223..24e85dd8e8 100644
--- a/frontend/coprs_frontend/coprs/views/coprs_ns/coprs_general.py
+++ b/frontend/coprs_frontend/coprs/views/coprs_ns/coprs_general.py
@@ -141,6 +141,8 @@ def coprs_by_user(username=None, page=1):
 @coprs_ns.route("/fulltext/", defaults={"page": 1})
 @coprs_ns.route("/fulltext/<int:page>/")
 def coprs_fulltext_search(page=1):
+    raise BadRequest("Searching in Fedora Copr is too demanding and is temporarily disabled: "
+                     "https://github.com/fedora-copr/copr/issues/2534")
     params = flask.request.args
     allowed_keys = ["fulltext", "projectname", "ownername", "packagename"]
     for key in params.keys():
```

**Comment by FrostyX** [comment]
I did some experiments with the whoosh cache on production so it is a bit smaller now. But before that, I did a backup and it was much worse than the number in the issue description.

```
[root@copr-fe ~][PROD]# du --max-depth=0 -h /home/jkadlcik/copr_whoosheer/
1.2G    /home/jkadlcik/copr_whoosheer/
```

Please see #2578 which tries to fix this.

Whoosh is quite smart and rebuilds the cache in temporary directories, so it can then switch to the new version in one atomic operation. My hypothesis (not confirmed) is that when we run `copr-frontend update-indexes-quick`, it doesn't properly clean up. We run it hourly, so the garbage can pile on quickly.

So far I reworked the `update-indexes` (not quick variant) to be fast enough to be run daily, so we can periodically rebuild the whoosh cache from scratch and keep it small. I am not sure what effect it will have on the search speed and memory usage but it'll for sure keep the index small.

**Comment by praiskup** [comment]
Just a quick search again, solr seams to be a long shot for us (not in distributions).

[xapian seems easy](https://getting-started-with-xapian.readthedocs.io/en/latest/practical_example/index.html)
[sphinx no so easy](http://sphinxsearch.com/docs/sphinx3.html#getting-started-on-linux-and-macos)

Both xapian and sphinx are in Fedora though.

**Comment by praiskup** [comment]
Well, `lucene.noarch : High-performance, full-featured text search engine` is in Fedora.

**Comment by FrostyX** [comment]
I applied the changes from PR #2578 as a hotfix, and did

```
[root@copr-fe ~][PROD]# sudo -u copr-fe /usr/bin/copr-frontend update-indexes
[root@copr-fe ~][PROD]# du --max-depth=0 -h /var/lib/copr/data/whooshee/copr_whoosheer
143M    /var/lib/copr/data/whooshee/copr_whoosheer
```

So I enabled searching again and tried

```
parallel curl ::: $(for i in {1..100}; do echo "https://copr.fedorainfracloud.org/coprs/fulltext/?fulltext=foo"; done)
```

At most, the load spiked to

![Screenshot_2023-03-16_22-17-04](https://user-images.githubusercontent.com/2151771/225755961-984302cf-bfca-4fd1-b6fb-9e00248c7e59.png)

The memory usage went down afterward, so there doesn't seem to be any leak.

**Comment by praiskup** [comment]
That sounds promising but I tested one search, and it took at least 20s, maybe more ... then I tried the parallel example
![Screenshot_20230317_071947](https://user-images.githubusercontent.com/3277839/225828331-35ced68d-9f73-419c-b37f-b33e2809fa6c.png)

**Comment by FrostyX** [comment]
The `update-indexes-quick` is still broken:

```
[root@copr-fe ~][PROD]# du --max-depth=0 -h /var/lib/copr/data/whooshee/copr_whoosheer
143M    /var/lib/copr/data/whooshee/copr_whoosheer

[root@copr-fe ~][PROD]# sudo -u copr-fe /usr/bin/copr-frontend update-indexes-quick 120
[root@copr-fe ~][PROD]# du --max-depth=0 -h /var/lib/copr/data/whooshee/copr_whoosheer
223M    /var/lib/copr/data/whooshee/copr_whoosheer

[root@copr-fe ~][PROD]# sudo -u copr-fe /usr/bin/copr-frontend update-indexes-quick 120
[root@copr-fe ~][PROD]# du --max-depth=0 -h /var/lib/copr/data/whooshee/copr_whoosheer
325M    /var/lib/copr/data/whooshee/copr_whoosheer
```

It grows and grows. I temporarily disabled the cron job for running the `update-indexes-quick` command.

**Comment by FrostyX** [comment]
It can be easily fixed by running `writer.commit()` with `optimize=True` but that makes it run ~3 minutes on the production machine, which is the same as update-indexes (non quick), making the quick variant useless.

I think we should run the non-quick variant daily to make sure the cache doesn't get out of hand, get rid of the `update-indexes-quick` command completely, and update the cache from the logic code (e.g. when a new project is created, when a new package is added, etc).

Or alternatively, we can take the easy route and replace `update-indexes-quick` in `cron.hourly` with `update-indexes` and be done with it.

**Comment by praiskup** [comment]
Technically I have nothing against this; please do it.  But I can't believe it is the major search engine we want to have and spending hours on it doesn't make sense; it is <= 30k projects, and the search takes >= 10s and eats GBs of RAM :-(  I think we grow over the maintenable limit, and we can't easily avoid.
