### ISSUE TITLE
RFE: Add the ability to configure build timeouts for packages

### ISSUE THREAD

**Issue by Conan-Kudo** [fedora-copr/copr#2562]
When configuring packages in COPR to track Dist-Git, I cannot set the timeout for automatically triggered builds:

<img width="869" alt="image" src="https://user-images.githubusercontent.com/276796/222904557-58c4e468-eb93-4d10-a834-1b3205c1c73f.png">

This is a problem because the standard timeout isn't good enough in some cases for packages. Can you please add the ability to configure the timeout for automatically kicked off builds?

**Comment by praiskup** [comment]
There was #1591 we closed in favor of #2541.  We could start implementing #2541 "epic" WRT the timeout field I guess.

**Comment by ericcurtin** [comment]
👍

**Comment by praiskup** [comment]
Ok, let's move this to #2541.
