### ISSUE TITLE
Performance issues on frontend and dist-git

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2571]
https://pagure.io/fedora-infrastructure/issue/11174
https://pagure.io/fedora-infrastructure/issue/11176

This is related to https://github.com/fedora-copr/copr/issues/2410 and also related to https://github.com/fedora-copr/copr/issues/2534

I tried to stop `copr-dist-git` service, and it killed all the background jobs (should be independent daemons that survive service restart):

```
Mar 10 18:06:19 copr-dist-git.aws.fedoraproject.org systemd[1]: copr-dist-git.service: Killing process 274064 (tar) with signal SIGKILL.
Mar 10 18:06:19 copr-dist-git.aws.fedoraproject.org systemd[1]: copr-dist-git.service: Killing process 274089 (rpm2archive) with signal SIGKILL.
Mar 10 18:06:19 copr-dist-git.aws.fedoraproject.org systemd[1]: copr-dist-git.service: Killing process 274090 (tar) with signal SIGKILL.
Mar 10 18:06:19 copr-dist-git.aws.fedoraproject.org systemd[1]: copr-dist-git.service: Killing process 274115 (rpm2archive) with signal SIGKILL.
Mar 10 18:06:19 copr-dist-git.aws.fedoraproject.org systemd[1]: copr-dist-git.service: Killing process 274116 (tar) with signal SIGKILL.
Mar 10 18:06:19 copr-dist-git.aws.fedoraproject.org systemd[1]: copr-dist-git.service: Killing process 274118 (rpm2archive) with signal SIGKILL.
Mar 10 18:06:19 copr-dist-git.aws.fedoraproject.org systemd[1]: copr-dist-git.service: Killing process 274119 (tar) with signal SIGKILL.
```

**Comment by praiskup** [comment]
There's "process in D state" problem, but not on the storage volume - this time it is the root (gp2 80GB) partition:

![Screenshot_20230310_200158](https://user-images.githubusercontent.com/3277839/224403652-747c6035-bf49-4798-841a-11fc38900063.png)

**Comment by praiskup** [comment]
Not 100% but `rpm2archive` seems to overload swap because the files we read are in /tmp, and they are on tmpfs:
```
copr-di+  284559  0.2  0.1  14680  4728 ?        D    18:32   0:06 rpm2archive -n -
copr-di+  284653  0.3  0.0  14608  3412 ?        D    18:32   0:07 rpm2archive -n -
copr-di+  286518  0.2  0.1  14784  5860 ?        D    18:42   0:03 rpm2archive -n -
copr-di+  286853  0.1  0.1  14784  6920 ?        D    18:45   0:02 rpm2archive -n -
copr-di+  286939  0.1  0.1  14784  6772 ?        D    18:45   0:02 rpm2archive -n -
copr-di+  286972  0.2  0.1  14784  6984 ?        D    18:46   0:03 rpm2archive -n -
copr-di+  287161  0.1  0.1  14784  7032 ?        D    18:47   0:02 rpm2archive -n -
copr-di+  287164  0.2  0.1  14784  7016 ?        D    18:47   0:02 rpm2archive -n -
copr-di+  287217  0.1  0.1  14784  7092 ?        D    18:47   0:02 rpm2archive -n -
```

**Comment by praiskup** [comment]
Temporarily?  switched to t3a.xlarge and decreased the number of parallel importer workers to 8.

**Comment by praiskup** [comment]
@xsuchy's idea: let's have a provisioned IOPS volume for SWAP

**Comment by xsuchy** [comment]
This: https://aws.amazon.com/ebs/pricing/ 
Provisioned IOPS SSD (io2) - Storage | $0.125/GB-month
And use it as a small volume (1-3GB) for a swap with higher priority. And then rest of the swap on current volume that has slower IOPS and smaller burst volume.

**Comment by praiskup** [comment]
Closing in favor of #3089.
