### ISSUE TITLE
Disable appstream-builder for existing Copr projects

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2577]
Per discussion in:
https://lists.fedorahosted.org/archives/list/copr-devel@lists.fedorahosted.org/thread/JP4TBPHD6HZOBWU4VEBKLGUHEC6CBDC3/
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/X63HU2ETJJ5NLSU64HMGVU74A2J2WNLT/

We'll go and `update copr set appstream = false'.

**Comment by praiskup** [comment]
Don't do for:
- [phracek/PyCharm/](https://copr.fedorainfracloud.org/coprs/phracek/PyCharm/) (per fedora devel list)

**Comment by FrostyX** [comment]
```
coprdb=# update copr set appstream=false where id!=2115;
UPDATE 85363
```
