### ISSUE TITLE
Make copr_messaging optional

### ISSUE THREAD

**Issue by pkking** [fedora-copr/copr#2589]
In openEuler community, we do not shipped any message bus like fedmsg and so we can't get pkgs like fedora-messaging and fedmsg.
Is there any workaround to make these pkg optional?

**Comment by praiskup** [comment]
There are ways to make package optional in Rpm (conditional deps, soft deps, etc.).
But there's a low motivation in the Copr team to make messaging optional (even if unused, it typically costs very small amount of storage to have the libraries installed).

**Comment by pkking** [comment]
I'd like submit a PR to make backend work without copr_messaging :)

**Comment by praiskup** [comment]
Sure, patches are welcome!  The "optional dependencies" is a non-trivial topic, so be prepared we'll review it very carefully. :)

**Comment by praiskup** [comment]
See also: https://github.com/fedora-copr/copr/pull/2596
