### ISSUE TITLE
Set timeouts on ssh.run_expensive() somehow?

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2592]
Build in https://copr.fedorainfracloud.org/coprs/g/copr/copr-pull-requests/build/5698554/
is stuck for 3.5 hours, claiming:
```
[2023-03-23 12:57:55,913][  INFO][PID:2283073] Marking build as starting
[2023-03-23 12:57:56,348][  INFO][PID:2283073] Trying to allocate VM
[2023-03-23 12:57:59,380][  INFO][PID:2283073] Allocated host ResallocHost, ticket_id=1664162, hostname=2620:52:3:1:dead:beef:cafe:c253
[2023-03-23 12:57:59,381][  INFO][PID:2283073] Allocating ssh connection to builder
[2023-03-23 12:57:59,381][  INFO][PID:2283073] Checking that builder machine is OK
```

So the code https://github.com/fedora-copr/copr/blob/c7883cb822b6f282016e9d092fbcacba91796bcd/backend/copr_backend/background_worker_build.py#L231 got stuck, somehow.

But the ssh connection is established, and we get responses for the keepalive pings:

    ssh -F /home/copr/.ssh/config mockbuilder@2620:52:3:1:dead:beef:cafe:c253 /usr/bin/test -f /etc/mock/fedora-rawhide-ppc64le.cfg

No new SSH connections can be established.  So Resalloc's "connection monitoring"
watcher fails, ticket is "FAILED", and we are "DELETING" the resource.  But the
termination SSH session appears to be in the very same situation:

    ssh root@2620:52:3:1:dead:beef:cafe:c253 subscription-manager unregister

Looks like all the SSH connections should have **some** reasonable timeout.

**Comment by praiskup** [comment]
There must be some other weird issue;  I killed the neverending `/usr/bin/test -f` process, copr took another builder and proceeded the build - but it stays in `starting` state (not running).

**Comment by praiskup** [comment]
Hm, actually -> the SSH behavior is different.  Any attempt to connect over
SSH actually hangs.  The process is obviously able to setup the channel
(keep-alive packages seem to pass by) but the command itself hangs.

Strace says:
```
[root@copr-be ~][PROD]# strace -p 3366450
strace: Process 3366450 attached
pselect6(7, [3], [], NULL, {tv_sec=14, tv_nsec=256077006}, NULL) = 0 (Timeout)
getpid()                                = 3366450
getrandom("\x48\xaa\x32\x09", 4, 0)     = 4
pselect6(7, [3], [3], NULL, {tv_sec=20, tv_nsec=0}, NULL) = 1 (out [3], left {tv_sec=19, tv_nsec=999997600})
write(3, "\0\0\0 \17\226\372\371\323b\254`^x&(8\21|\305G\225q\"\220\1\\\223g\233\21g"..., 52) = 52
pselect6(7, [3], [], NULL, {tv_sec=20, tv_nsec=0}, NULL) = 1 (in [3], left {tv_sec=19, tv_nsec=905746305})
read(3, "\0\0\0\0204 \271T\370\262=\225\374\301\17g\321\336\312\222\252\255\26\377\334\360\272Oc\366.l"..., 8192) = 36
getpid()                                = 3366450
pselect6(7, [3], [], NULL, {tv_sec=20, tv_nsec=0}, NULL) = 0 (Timeout)
getpid()                                = 3366450
getrandom("\xcd\xcd\x56\x95", 4, 0)     = 4
pselect6(7, [3], [3], NULL, {tv_sec=20, tv_nsec=0}, NULL) = 1 (out [3], left {tv_sec=19, tv_nsec=999997190})
write(3, "\0\0\0 Rt\207\10\333n_\276\224F\314~\323\2536\20\320\323q\\\232\307\230&\f\n\372\17"..., 52) = 52
pselect6(7, [3], [], NULL, {tv_sec=20, tv_nsec=0}, NULL) = 1 (in [3], left {tv_sec=19, tv_nsec=921618030})
read(3, "\0\0\0\20\202\205Ho\250\246\276\313r\217\273\264\226\263uB\336\35\30\257\316\362\270\302D\212\346:"..., 8192) = 36
getpid()                                = 3366450
pselect6(7, [3], [], NULL, {tv_sec=20, tv_nsec=0}, NULL
...
```
@Jakuje, does't this sound familiar to you?  Both systems are F37, client openssh-clients-8.8p1-7.fc37.x86_64 server openssh-server-8.8p1-7.fc37.ppc64le

**Comment by Jakuje** [comment]
I do not recall seeing anything like that. Maybe Dmitri/Zoltan who worked on OpenSSH recently can have some insights:

https://src.fedoraproject.org/rpms/openssh/commits/rawhide

For the timeouts, there is a new functionality ChannelTimeout, which should do the job for you:

https://man.openbsd.org/sshd_config.5#ChannelTimeout

Unfortunately, its only in 9.2, which is not yet in Fedora:

https://www.openssh.com/txt/release-9.2

**Comment by praiskup** [comment]
We should at least have a better timeout management per run_expensive() call.

**Comment by praiskup** [comment]
This happens when the disk fails, and every process that tries to touch the disk ends up in `D` uninterruptable state - including new SSH connection attempts.  Old SSH connections just keep doing keepalive packet handover and it is hard to detect this is happening.  If you have a way how to detect this @Jakuje let us know, please.  In the meantime, I'm closing this duplicate to #2888 which has more info.
