### ISSUE TITLE
download stats or footnote on copr project front pages apprear to be wrong

### ISSUE THREAD

**Issue by knurd** [fedora-copr/copr#2601]
From outside observation it looks to me like either the package download stats on the front page of each copr project are miscalculated or the footnote explaining their meaning is wrong. 

The footnote says this about the number:

> * Total number of packages downloaded in the last seven days.

But that's afaics can't be right, as quite a few numbers are non-zero even when the repos are empty -- and they don't change either.

Take for example https://copr.fedorainfracloud.org/coprs/g/kernel-vanilla/mainline/ (screenshot attached), which is empty since at least two weeks now (and will stay empty for three or for more weeks) ; nevertheless the page claims that quite a few packages were downloaded in the past seven days (and the numbers didn't change in the past few days). That's kinda odd.

![Screenshot from 2023-03-28 06-12-57](https://user-images.githubusercontent.com/2239565/229064029-ff5f6c7e-897e-4425-8653-6e4f259e2643.png)

**Comment by FrostyX** [comment]
Thank you for the feedback @knurd,

> Total number of packages downloaded in the last seven days.

Oh yea, that's not correct. You are right. It shows the total number of downloads now, we should fix the footnote.
