### ISSUE TITLE
Please handle temporary copr-frontend failures transparently

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2609]
Original issue: https://bugzilla.redhat.com/show_bug.cgi?id=1639815
Opened: 2018-10-16 16:25:38
Opened by: Nicolas Mailhot

---

#### Nicolas Mailhot commented at 2018-10-16 16:25:38:
So sometimes when infra is loaded copr-cli gets a_

Error: Unknown response from the server. Code: 504, raw response:_
 <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>504 Gateway Timeout</title>
</head><body>
<h1>Gateway Timeout</h1>
<p>The gateway did not receive a timely response
from the upstream server or application.</p>
</body></html>

And then it barfs.

It should handle this case, retry after a while, and fail only if the retry fails (and fail with a nice message, not "I don't understand my own server-side")

---

#### Pavel Raiskup commented at 2020-12-11 16:15:07:
*** Bug 1720855 has been marked as a duplicate of this bug. ***

**Comment by FrostyX** [comment]
> It should handle this case, retry after a while, and fail only if the retry fails (and fail with a nice message, not "I don't understand my own server-side")

I can't find the PR but `copr-cli` now tries multiple attempts in such cases.

**Comment by praiskup** [comment]
ea06ca5f1182e14517bd2174df4035473d81e323
