### ISSUE TITLE
Project search doesn't filter as expected

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2620]
Original issue: https://bugzilla.redhat.com/show_bug.cgi?id=1919104
Opened: 2021-01-22 07:36:19
Opened by: Zbigniew Jędrzejewski-Szmek

---

#### Zbigniew Jędrzejewski-Szmek commented at 2021-01-22 07:36:19:
Description of problem:
I wanted to search for coprs related to "git" (in hope of finding a version that is newer than the one in F33). The description of the search box says "Search projects by name, os or arch". Typing "git" into the search box returns 343 answers, and most of them have "git" in none of those three properties.

Version-Release number of selected component (if applicable):
whatever's runing on https://copr.fedorainfracloud.org/ right now.

---

#### Miroslav Suchý commented at 2021-01-24 22:10:57:
IIRC it search description and installation instructions (and package name btw). And e.g.
https://copr.fedorainfracloud.org/coprs/packit/packit-hello-world-214-stg/
has "git" several times in the installation instructions.

---

#### Miroslav Suchý commented at 2021-01-24 22:13:44:
Hmm, we can give a boost to some fields.

Here is a relevant documentation https://whoosh.readthedocs.io/en/latest/schema.html#field-boosts

But it will be tricky to find a good balance.

---

#### Pavel Raiskup commented at 2021-10-11 07:48:16:
Well, the search is actually done full-text, through project summary, description,
etc.  I think that the `Search projects by name, os or arch` is misleading here.
Should we just change the search box placeholder?

I also filled https://pagure.io/copr/copr/issue/1947 .

Zbyszek, I'm thinking what to do with this issue.  Would those two ^^ things
resolve the bug for you?

---

#### Zbigniew Jędrzejewski-Szmek commented at 2021-10-11 12:50:53:
+1

---

#### Pavel Raiskup commented at 2021-12-23 10:10:38:
FTR, boosters could be added here:
https://pagure.io/copr/copr/blob/33c132689774b97d58227097979dd0fdbf64fe43/f/frontend/coprs_frontend/coprs/whoosheers.py#_16-33

There's also bug 1870320 that asks for documenting "how to search".

**Comment by FrostyX** [comment]
Hello Zbigniew,
it is now possible to search explicitly by only a project name, owner name, etc.
https://docs.pagure.org/copr.copr/release-notes/2021-11-11.html#searching-by-attributes

I think this solves your issue? Please feel free to reopen if not.
