### ISSUE TITLE
kstars 3rd party drivers - build fails to link to sv305m camera

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2628]
Original issue: https://bugzilla.redhat.com/show_bug.cgi?id=2183850
Opened: 2023-04-02 18:25:44
Opened by: dansawyeror

---

#### dansawyeror commented at 2023-04-02 18:25:44:
Description of problem: kstars / indi / 3rdparty drivers fail to link to svbony driver. It is not clear if the driver is acutally built. This is likely a build problem. 

Version-Release number of selected component (if applicable): 2.0.2

How reproducible: 100% 

Steps to Reproduce:
1. install latest versions of kstars / indi / 3rd party drivers
2. connect a sv305 camera via USB
3. start kstars, configure sv305 (CCD) camera
4. attempt to connect by starting indi
5. connection fails 

Actual results: Connection fails

Expected results: indi connects to device

Additional info: The exact same hardware setup works and conects via alternate application AstroDMX.

**Comment by xsuchy** [comment]
I fail to recognize how this is related to Copr. Closing.

**Comment by praiskup** [comment]
I suppose the original problem is related to [this project](https://copr.fedorainfracloud.org/coprs/xsnrg/indi-3rdparty-bleeding/).  Use the discussion there if you still face the issues.  Copr administrators/maintainers do not take care of the hosted projects, please consult with the project owner (likely @xsnrg) for potential fixes.

**Comment by dansawyer** [comment]
Thanks for the pointer. How can (likely @xsnrg)  be contacted? That link simply shows 'Jim'. Is there a board for that project?

**Comment by xsnrg** [comment]
yes, this is not a  Copr problem. I replied to the comment in the copr repo chat as well, but will do so here also. @dansawyer  please use the forum dedicated to INDI clients, where many of the code authors will see it here: https://indilib.org/forum/clients.html

**Comment by FrostyX** [comment]
@dansawyer, you can find contact information for any Fedora user on the Fedora Accounts page:
https://accounts.fedoraproject.org/user/xsnrg/
