### ISSUE TITLE
Copr build system should respect ExcludeArch and ExclusiveArch

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2630]
Original issue: https://bugzilla.redhat.com/show_bug.cgi?id=1622575
Opened: 2018-08-27 13:34:44
Opened by: Pavel Raiskup

---

#### Pavel Raiskup commented at 2018-08-27 13:34:44:
E.g. 
https://copr.fedorainfracloud.org/coprs/praiskup/libpq-lib-deps/build/791384/

There's ExclusiveArch statement, which should avoid building the
package against i386.

---

#### Pavel Raiskup commented at 2019-01-09 08:22:58:
After PR 438, it should be much easier to implement this feature since
there's now a single point in the logic where we decide what chroots
should be a particular package built against (based on chroot wildcards,
but ExcludeArch would be very similar).

---

#### Orion Poplawski commented at 2023-02-27 14:45:38:
This would be greatly appreciated.  See also https://github.com/fedora-copr/copr/issues/2137

**Comment by FrostyX** [comment]
Can we consider this done by PR #2769?

**Comment by fberat** [comment]
Looks like not:
https://copr.fedorainfracloud.org/coprs/fberat/gcc-14_500/build/6738124/

**Comment by praiskup** [comment]
I'd say this one in particular is fixed by #2769, @fberat the build is deleted - don't you remember the point?

**Comment by fberat** [comment]
@praiskup That is related to #3061. The build was the one that generated the:

`error: Architecture is excluded: i686`

**Comment by praiskup** [comment]
Ah, OK, thank you for the follow-up.  Since we have 3061, I'm closing this RFE (it is implemented, even though with known issues).
