### ISSUE TITLE
Let's have separate webhooks for each package in copr

### ISSUE THREAD

**Issue by FrostyX** [fedora-copr/copr#2640]
Original issue: https://bugzilla.redhat.com/show_bug.cgi?id=1344191
Opened: 2016-06-09 06:08:47
Opened by: Pavel Raiskup

---

#### Pavel Raiskup commented at 2016-06-09 06:08:47:
ATM, webhook in Copr triggers build of all packages that are configured to be
built by webhook.  Because different package might come from different source
repositories, it is at least wasting of resources to spin the builds for all
packages when only one of them was changed;  but it also very likely will
break the repository.

---

####  commented at 2016-06-13 05:08:47:
Good point!

---

#### Pavel Raiskup commented at 2017-12-15 09:03:40:
(In reply to Pavel Raiskup from comment #0)
> Because different package might come from different source repositories, it
> is at least wasting of resources

Seems like there's some work-around for this trying to match source repository
where the webhook comes from with the "SCM's git repo" url.  This is however
rather non-flexible - giving the CI work-flow artificial limits.  Eg:

Per https://docs.pagure.org/copr.copr/webhook_hacking.html#webhook-hacking

The payload dict requested ^^ is just pain, one would like to do just
'curl https://copr.fedorainfracloud.org/webhooks/github/16322/0bdb2d04-30f5-41d5-8e9d-da27c38ef426/' and that's it.

Per https://docs.pagure.org/copr.copr/user_documentation.html
> The only source type which make sense together with webhooks is “SCM”.

Meh, this is rather ugly limitation :(.  The CI (e.g. some Jenkins jobs)
can create the tarball + spec => and srpm, and provide that srpm on some
public url (so srpm-url method might succeed).

**Comment by praiskup** [comment]
This has likely been resolved by the custom method/custom webhook (which is per-package).  Please reopen if you disagree.
