### ISSUE TITLE
Allow adding packages to minimal buildroot "per-project"

### ISSUE THREAD

**Issue by FrostyX** [fedora-copr/copr#2650]
Original issue: https://bugzilla.redhat.com/show_bug.cgi?id=1440234
Opened: 2017-04-07 16:03:12
Opened by: Pavel Raiskup

---

#### Pavel Raiskup commented at 2017-04-07 16:03:12:
ATM, I can add packages to minimal buildroot "per-chroot", which is simply
way too much clicking when project has many chroots..

Especially if I need to temporarily remove the package from minimal
buildroot, and then put it back.

So it would be nice to have a new field like:

  Settings -> Build options -> Minimal buildroot packages

(so both per-chroot and per-project options would be there, similarly to
what we have for additional repositories)

**Comment by praiskup** [comment]
Will be implemented in #2541.
