### ISSUE TITLE
Generally check if we can build in a project before uploading

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2658]
This RFE is about adding a check that allows us to build with given arguments first, before we actually start uploading large srpms.  See the example:
```
$ copr build ping --chroot centos-stream+epel-next-9-x86_64 /tmp/quick-package/dummy-pkg-20230406_1042-1.src.rpm
Uploading package /tmp/quick-package/dummy-pkg-20230406_1042-1.src.rpm
 |################################| 8.0 kB 19.4 kB/s eta 0:00:00

Something went wrong:
Error: Bad request parameters: {'chroots': ["'centos-stream+epel-next-9-x86_64' is not a valid choice for this field."]}
```

**Comment by praiskup** [comment]
This is a follow-up for #134 (I actually wanted to have something like _this_ those days, but I have forgotten the details in the meantime).

**Comment by FrostyX** [comment]
Currently the `/root/copr/beaker-tests/Sanity/copr-cli-basic-operations/build-spec.sh` test fails because of a regression from _the permission checking PR_. Once this issue is fixed, the test should start passing again.

**Comment by FrostyX** [comment]
For the record, this issue happens not only in case of nonexisting chroot but also nonexisting CoprDir

```
$ copr build frostyx/local:foo ~/rpmbuild/SRPMS/rofi-themes-base16-0.1.0-2.fc36.src.rpm
Uploading package /home/jkadlcik/rpmbuild/SRPMS/rofi-themes-base16-0.1.0-2.fc36.src.rpm
 |################################| 74.2 kB 27.0 MB/s eta 0:00:00

Something went wrong:
Error: Please use directory format local:custom:<SUFFIX_OF_CHOICE> or local:pr:<ID> (for automatically removed directories)
```

**Comment by praiskup** [comment]
Exactly, in my opinion we want to have some `--dry-run`-like upload build route, doing all the checks we would do once more post-upload? (except for race conditions, which we don't need to have solved in this case, it should cover everything).

**Comment by FrostyX** [comment]
Exactly what I am implementing right now :-)
