### ISSUE TITLE
Add Amazon Linux chroots

### ISSUE THREAD

**Issue by FrostyX** [fedora-copr/copr#2666]
@Conan-Kudo asked on IRC for this

Mock configs already merged
https://github.com/rpm-software-management/mock/pull/1047

we are waiting for new `mock-core-configs` release now.

**Comment by praiskup** [comment]
Chroots created:

    amazonlinux-2023-x86_64
    amazonlinux-2023-aarch64

**Comment by Conan-Kudo** [comment]
@stewartsmith @nmeyerhans Is there a logo icon SVG that could be used for COPR Amazon Linux chroots? We currently have no icon...

**Comment by davdunc** [comment]
![AWS_logo_RGB](https://user-images.githubusercontent.com/297012/234446105-bd8fbe53-4aa4-4ec7-82db-2bac3e7fda7b.svg)

**Comment by praiskup** [comment]
Help with this is welcome, we need a PR against copr project, adding `amazonlinux.png` into [this directory](https://github.com/fedora-copr/copr/tree/main/frontend/coprs_frontend/coprs/static/chroot_logodir).

**Comment by stewartsmith** [comment]
Yeah, there is an Amazon Linux logo now. I'll spin up a CR for it
