### ISSUE TITLE
undo the `dnf versionlock` for pyrhon-rpkg on dist-git machines

### ISSUE THREAD

**Issue by nikromen** [fedora-copr/copr#2670]
This is just a tracking issue that is blocked by #2317  and #2608

undo the versionlock on our dist-git dev and prod machines once these two issues mentioned above are resolved

**Comment by praiskup** [comment]
FTR, there's the https://copr.fedorainfracloud.org/coprs/g/copr/copr-dev/build/5928016/ build in copr-dev, so our CI should be fixed (bumped epoch in the older package).  We should delete that build when this issue get's resolved.

**Comment by praiskup** [comment]
Done, `dnf versionlock clear` on dist-git.
