### ISSUE TITLE
Statistics of who is using a service

### ISSUE THREAD

**Issue by xsuchy** [fedora-copr/copr#2673]
I want to have a heatmap statistics on who is using our service. I have this code
  https://gist.github.com/xsuchy/eb5d8394cafd428176138ac4fbb881e2
but this needs to be incorporated in copr code.
It will be great if the users could be grouped in groups (e.g. Python team, Cloud SIG,...) and this can be configured in a configuration file.

**Comment by praiskup** [comment]
https://github.com/fedora-copr/copr/pull/2676
