### ISSUE TITLE
Licensing and Forbidden Items links in docs are archived

### ISSUE THREAD

**Issue by penn5** [fedora-copr/copr#2681]
At https://github.com/fedora-copr/copr/blob/main/doc/user_documentation.rst#faq the links to Licensing and Forbidden Items are no longer updated

**Comment by FrostyX** [comment]
Hello @penn5,
thank you for the report.

I updated the allowed licenses URL in PR #2682 but I don't know how to update the forbidden items URL. Is there any replacement of this page? Even this page
https://docs.fedoraproject.org/en-US/package-maintainers/New_Package_Process_for_Existing_Contributors/
points to the old wiki.

**Comment by praiskup** [comment]
Triage time: We don't have the forbidden items (yet?) or something similar. Can we drop the link or add a link to "bad licenses" page?

**Comment by praiskup** [comment]
Closing as fixed by #2899, thank you for the report, @penn5
