### ISSUE TITLE
Enlarge disk on copr-dist-git

### ISSUE THREAD

**Issue by FrostyX** [fedora-copr/copr#2684]
We are running out of disk space - or possibly inodes

**Comment by praiskup** [comment]
Green again: https://nagios.fedoraproject.org/nagios/cgi-bin//status.cgi?host=copr-dist-git.aws.fedoraproject.org&style=detail

**Comment by praiskup** [comment]
Discussed with @xsuchy this is a false alarm:
```
Filesystem     Inodes IUsed IFree IUse% Mounted on
/dev/nvme1n1p1   313M   46M  268M   15% /var/lib/dist-git
```
