### ISSUE TITLE
Enable modules for el8

### ISSUE THREAD

**Issue by xsuchy** [fedora-copr/copr#2703]
It seems we cannot create modules for EL8.

From my inbox:

I had read through that and ran into:

```
copr-cli build-module --yaml modulemd/modulemd-foreman-el8.yaml @theforeman/foreman-nightly

Something went wrong:
Error: Unexpected platform 'el8', it should be e.g. f28 or -f30
```

On Fri, May 5, 2023 at 9:25 AM Miroslav Suchý wrote:

    Dne 05. 05. 23 v 15:19 Eric Helms napsal(a):
    > We have to create a module for our repositories to properly function. I am thinking we are going to just need as part
    > of our process copying the Copr repositories to a stage environment to inject the modular metadata and then for
    > testing before we promote them to our release location.

    http://frostyx.cz/posts/how-to-build-modules-in-copr

    Miroslav

**Comment by FrostyX** [comment]
For the record, I reproduced this issue using:
https://github.com/theforeman/foreman-packaging/blob/rpm/3.6/modulemd/modulemd-foreman-el8.yaml
