### ISSUE TITLE
repo with 2 builds of same nevra is giving user the older build to install

### ISSUE THREAD

**Issue by jn64** [fedora-copr/copr#2704]
Reference to this bug https://github.com/agriffis/neovim/issues/19

This copr agriffis/neovim-nightly has 2 builds of the package `python3-neovim` with same nevra: `python3-neovim-0.4.3.0.git.601.71102c0-1.fc38.noarch`

1. [Build 04765755 from 2022-08-25](https://download.copr.fedorainfracloud.org/results/agriffis/neovim-nightly/fedora-38-x86_64/04765755-python-neovim/)
2. [Build 05726828 from 2023-03-29](https://download.copr.fedorainfracloud.org/results/agriffis/neovim-nightly/fedora-38-x86_64/05726828-python-neovim/)

On F38, when I do `dnf install python3-neovim`, it gives me the older build 04765755 (confirmed by comparing the rpm in the dnf cache to the one I downloaded from the chroot).

As a user I would expect that I get the newest version/build when I install a package by name. Of course, packages shouldn't have same nevra, but if they do, shouldn't the repodata point to the newest one?

**Comment by FrostyX** [comment]
@praiskup, this is a frequent question, so I was convinced we have this documented somewhere. But I couldn't any mention of this in FAQ or anywhere else in the documentation. Did I miss it, or we really don't have this? Maybe we should have?

**Comment by praiskup** [comment]
I don't think this is documented somewhere.  There's also a bit more interesting aspect;  we run the prunerepo utility on the directory, and one of the NVRs should get removed.  Which one?  Is it deterministic?

I also think we should have this documented;  together with the work-arounds (like the `%buildtag` use).
