### ISSUE TITLE
Document what needs to be audited

### ISSUE THREAD

**Issue by xsuchy** [fedora-copr/copr#2706]
It will be nice to have documentation that states:

* what credentials need to be rotated
* what to check when we audit who has an access

**Comment by praiskup** [comment]
no progress

**Comment by praiskup** [comment]
no progress

**Comment by praiskup** [comment]
no progress

**Comment by praiskup** [comment]
no progress

**Comment by praiskup** [comment]
Work in progress, note I've filled Fedora Infra issue for better credential maintenance https://pagure.io/fedora-infrastructure/issue/11612

**Comment by praiskup** [comment]
I still need to document the way to rotate those.  So far I just cleaned up ansible.git a bit:

https://pagure.io/fedora-infra/ansible/c/bb04ae62adf461216f488bf125e7fe0dc970330c
https://pagure.io/fedora-infra/ansible/c/8abbdbaea50843c0d1eb77dc4f7301d6fbf53d20
https://pagure.io/fedora-infra/ansible/c/4792241cfef8f5ba9cf9c17197a8368e0727e5f1
https://pagure.io/fedora-infra/ansible/c/63e981214948678c30fed1c65b624bffa5055fcb
https://pagure.io/fedora-infra/ansible/c/47b91aae1f837668fa7f6766c56fa7001d8a0055
https://pagure.io/fedora-infra/ansible/c/41af546c0d9d1a8b868b039ad00b7f152b66581b

I still need to request the corresponding removals from ``ansible-private.git``.
