### ISSUE TITLE
Enlarge disk on copr-dist-git && decrease nagios quota for backend

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2737]

**Comment by praiskup** [comment]
copr-be resolved for now: https://pagure.io/fedora-infra/ansible/c/2ed4e90feb53a79141c92c18ff53aaf20035367f
We should mark Fedora 36 EOL this week, so hopefully we'll save some disk space there...

**Comment by praiskup** [comment]
BE quota warning threshold decreased to 8% of free space.
DG got an automatic cleanup in the meantime

**Comment by praiskup** [comment]
We discussed with @xsuchy this is a false alarm:
```
[root@copr-be ~][PROD]# df -hi /var/lib/copr/public_html
Filesystem                                          Inodes IUsed IFree IUse% Mounted on
/dev/mapper/copr--backend--data-copr--backend--data   384M   40M  345M   11% /var/lib/copr/public_html
```

**Comment by FrostyX** [comment]
Nagios started complaining about dist-git again, so I enlarged it data volume from 5T to 5.5T.
