### ISSUE TITLE
A count at overview page

### ISSUE THREAD

**Issue by pkking** [fedora-copr/copr#2770]
We added the packages count at the homepage, wondering if upstream like this patch :) 
![图片](https://github.com/fedora-copr/copr/assets/2853724/9410d4a9-9b9d-4427-b70b-995a7bd2aad3)

**Comment by praiskup** [comment]
Triage: We are not sure if this is very useful (too many packages in rubygems/pypi, too many duplicates). Eventually it is up to you, we can have this even as an optional feature.

**Comment by pkking** [comment]
Glad to make a PR😸
