### ISSUE TITLE
readthedocs deprecations

### ISSUE THREAD

**Issue by xsuchy** [fedora-copr/copr#2771]
I get this in my inbox:

Hello,
--
The Read the Docs build system will start requiring a configuration file v2 (.readthedocs.yaml) starting on September 25, 2023. We are sending weekly notifications about this issue to all impacted users, as well as temporary build failures (brownouts) as the date approaches for those who haven't migrated their projects.  The timeline for this deprecation is as follows:       Monday, July 24, 2023: Do the first brownout (temporarily enforce this deprecation) for 12 hours: 00:01 PST to 11:59 PST (noon)     Monday, August 14, 2023: Do a second brownout (temporarily enforce this deprecation) for 24 hours: 00:01 PST to 23:59 PST (midnight)     Monday, September 4, 2023: Do a third and final  brownout (temporarily enforce this deprecation) for 48 hours: 00:01 PST  to September 5, 2023 23:59 PST (midnight)     Monday, September 25, 2023: Fully remove support for building documentation without configuration file v2.   We have identified that the following projects which you maintain are impacted by this deprecation:        copr-backend      copr-keygen      copr-messaging      python-copr     Please add a configuration file to your projects to ensure that they  continue building successfully and to stop receiving these  notifications.  For more information on how to create a required configuration file, read our blog post  Get in touch with us via our support and let us know if you are unable to use a configuration file for any reason.
Keep documenting,                       Read the Docs

Hello,
The Read the Docs build system will start requiring a configuration file v2 (.readthedocs.yaml) starting on September 25, 2023. We are sending weekly notifications about this issue to all impacted users, as well as temporary build failures (brownouts) as the date approaches for those who haven't migrated their projects. The timeline for this deprecation is as follows:

    Monday, July 24, 2023: Do the first brownout (temporarily enforce this deprecation) for 12 hours: 00:01 PST to 11:59 PST (noon)
    Monday, August 14, 2023: Do a second brownout (temporarily enforce this deprecation) for 24 hours: 00:01 PST to 23:59 PST (midnight)
    Monday, September 4, 2023: Do a third and final brownout (temporarily enforce this deprecation) for 48 hours: 00:01 PST to September 5, 2023 23:59 PST (midnight)
    Monday, September 25, 2023: Fully remove support for building documentation without configuration file v2.

We have identified that the following projects which you maintain are impacted by this deprecation:

    [copr-backend](https://readthedocs.org/projects/copr-backend/)
    [copr-keygen](https://readthedocs.org/projects/copr-keygen/)
    [copr-messaging](https://readthedocs.org/projects/copr-messaging/)
    [python-copr](https://readthedocs.org/projects/python-copr/)

Please add a configuration file to your projects to ensure that they continue building successfully and to stop receiving these notifications. For more information on how to create a required configuration file, [read our blog post](https://blog.readthedocs.com/migrate-configuration-v2/) Get in touch with us [via our support](https://readthedocs.org/support/) and let us know if you are unable to use a configuration file for any reason.
Keep documenting,
Read the Docs

**Comment by FrostyX** [comment]
Copr-cli and copr-messaging build successfully now but

backend fails with

```
$ python -m pip install --exists-action=w --no-cache-dir -r backend/docs/requirements.txt

Collecting PyYAML (from -r backend/docs/requirements.txt (line 1))
  Downloading PyYAML-6.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (757 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 757.9/757.9 kB 17.8 MB/s eta 0:00:00
Collecting setproctitle (from -r backend/docs/requirements.txt (line 3))
  Downloading setproctitle-1.3.2-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (31 kB)
Collecting redis (from -r backend/docs/requirements.txt (line 4))
  Downloading redis-4.6.0-py3-none-any.whl (241 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 241.1/241.1 kB 295.4 MB/s eta 0:00:00
Requirement already satisfied: mock in /home/docs/checkouts/readthedocs.org/user_builds/copr-backend/envs/latest/lib/python3.11/site-packages (from -r backend/docs/requirements.txt (line 6)) (1.0.1)
Requirement already satisfied: requests in /home/docs/checkouts/readthedocs.org/user_builds/copr-backend/envs/latest/lib/python3.11/site-packages (from -r backend/docs/requirements.txt (line 7)) (2.31.0)
Collecting python-daemon (from -r backend/docs/requirements.txt (line 8))
  Downloading python_daemon-3.0.1-py3-none-any.whl (31 kB)
Collecting bunch (from -r backend/docs/requirements.txt (line 9))
  Downloading bunch-1.0.1.zip (11 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-lvnddkt8/bunch_694d8783b04b4201b4c1106aeff7ec6f/setup.py", line 11, in <module>
          package_file = open(join(HERE, 'bunch/__init__.py'), 'rU')
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      ValueError: invalid mode: 'rU'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

and keygen with:

```
$ python -m sphinx -T -E -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html

Running Sphinx v1.8.6
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/copr-keygen/envs/latest/lib/python3.11/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/copr-keygen/envs/latest/lib/python3.11/site-packages/sphinx/builders/latex/__init__.py", line 37, in <module>
    from sphinx.writers.latex import DEFAULT_SETTINGS, LaTeXWriter, LaTeXTranslator
  File "/home/docs/checkouts/readthedocs.org/user_builds/copr-keygen/envs/latest/lib/python3.11/site-packages/sphinx/writers/latex.py", line 33, in <module>
    from sphinx.util.template import LaTeXRenderer
  File "/home/docs/checkouts/readthedocs.org/user_builds/copr-keygen/envs/latest/lib/python3.11/site-packages/sphinx/util/template.py", line 17, in <module>
    from sphinx.jinja2glue import SphinxFileSystemLoader
  File "/home/docs/checkouts/readthedocs.org/user_builds/copr-keygen/envs/latest/lib/python3.11/site-packages/sphinx/jinja2glue.py", line 16, in <module>
    from jinja2 import FileSystemLoader, BaseLoader, TemplateNotFound, \
ImportError: cannot import name 'contextfunction' from 'jinja2' (/home/docs/checkouts/readthedocs.org/user_builds/copr-keygen/envs/latest/lib/python3.11/site-packages/jinja2/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/copr-keygen/envs/latest/lib/python3.11/site-packages/sphinx/cmd/build.py", line 300, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/copr-keygen/envs/latest/lib/python3.11/site-packages/sphinx/application.py", line 224, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/copr-keygen/envs/latest/lib/python3.11/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/copr-keygen/envs/latest/lib/python3.11/site-packages/sphinx/registry.py", line 475, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension sphinx.builders.latex (exception: cannot import name 'contextfunction' from 'jinja2' (/home/docs/checkouts/readthedocs.org/user_builds/copr-keygen/envs/latest/lib/python3.11/site-packages/jinja2/__init__.py))

Extension error:
Could not import extension sphinx.builders.latex (exception: cannot import name 'contextfunct
```
