### ISSUE TITLE
rpm-ostree copr bulids not triggering via webhook

### ISSUE THREAD

**Issue by cgwalters** [fedora-copr/copr#2772]
The builds for https://copr.fedorainfracloud.org/coprs/g/CoreOS/continuous/package/rpm-ostree/ are not being automatically triggered.  I've verified the webhook URL on github, and in that UI I see successful deliveries.

I think we discussed this before but didn't get it debugged.

**Comment by praiskup** [comment]
per IRC: walters> last timestamp is 2023-06-14 07:58:47

**Comment by praiskup** [comment]
@cgwalters the rpm-ostree package has a "trailing slash" configured in the clone_url field,
which breaks our current logic. Can you drop it?  There's #2775, but releasing
that one might take some time (days or weeks).
