### ISSUE TITLE
Test that the dynamic subpackages feature works in Copr

### ISSUE THREAD

**Issue by FrostyX** [fedora-copr/copr#2780]
And what will happen if it has?
+ do a showcase and test case

**Comment by FrostyX** [comment]
Please test if such SRPM can be built in Mock, and then in Copr.

**Comment by praiskup** [comment]
We need to know if (a) mock is able to build this and (b) then if copr can build this.  If not, we need to submit corresponding issues.

**Comment by praiskup** [comment]
$RPM_SPECPARTS_DIR is a separate directory that Copr/Mock knows nothing about.  But we should test that this actually works.

**Comment by nikromen** [comment]
no progress

**Comment by nikromen** [comment]
recording https://drive.google.com/file/d/1UiruD-5IrqLEKYVt4YNNTJtO4TBRuukG/view?usp=sharing

**Comment by FrostyX** [comment]
I wasn't at the meeting but IIRC we wanted to have a beaker test for this feature. Or did it turn out that we don't need to?

**Comment by praiskup** [comment]
It seems like a purely rpmbuild-specific feature; there shouldn't be a high probability for Mock/Copr to break it.
