### ISSUE TITLE
Can't upload-SRPM into custom copr directories (Error: Dirname doesn't exist)

### ISSUE THREAD

**Issue by jn64** [fedora-copr/copr#2786]
`copr-cli build --help` and manual says I can specify the repo in the form `project:<tag>`, but it doesn't work. I tried with a few different repos under my user.

Error:

```
$ copr-cli build playground:foo bar.src.rpm

Something went wrong:
Error: Dirname 'playground:foo' doesn't exist in 'jn64/playground' copr

$ copr-cli --version
copr version 1.109
```

Quoting the manual:

> Finally, instead of just project name, you can also pass project:tag. In that
> case, the build will land into the project side repository instead of the
> main repository. The side repository of the name project:tag will be
> automatically created if it doesn’t exist yet. You can e.g. use this feature
> to launch test builds while the main user-facing repository stays intact. You
> can specify any tag that is appropriate for the given build(s).

**Comment by praiskup** [comment]
Indeed, thank you for the report.

Source RPM upload  via `build` seems to be broken, while e.g. `build-distgit` works:

```
$ copr build-distgit ping:non-existing --chroot fedora-rawhide-x86_64 --name cpio

Something went wrong:
Error: Please use directory format ping:custom:<SUFFIX_OF_CHOICE> or ping:pr:<ID> (for automatically removed directories)
$ copr build-distgit ping:custom:dir --chroot fedora-rawhide-x86_64 --name cpio
Build was added to ping:
  https://copr.fedorainfracloud.org/coprs/build/6112997
...
```

**Comment by jn64** [comment]
Tangentially related: if/when this side tag works, is there any way to move a build from a side tag to the main repo? It would allow Copr users to have a kind of "updates testing" workflow and save time/resources on re-building the exact same build if their testing passes.
