### ISSUE TITLE
reserved instances for aarch64?

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2797]
> An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 4): There is no Spot capacity available that matches your request.

So I increased the number of non-spot instances to 18 temporarily, and we should rever when things are OK again.

**Comment by praiskup** [comment]
Hm, eventually increased to 36 (8 preallocated even for no traffic).

**Comment by praiskup** [comment]
I tend to think we should go with "reserved" instances here, instead of "spot".

**Comment by FrostyX** [comment]
We should run playbook and see if it it works now.

**Comment by praiskup** [comment]
no progress

**Comment by nikromen** [comment]
no progress

**Comment by xsuchy** [comment]
Done + pools.yaml refactored.
We now have 3 aarch64 reserved instances. In config we have:

https://pagure.io/fedora-infra/ansible/blob/main/f/roles/copr/backend/templates/resalloc/pools.yaml#_281
