### ISSUE TITLE
FTI and FTBFS after python 3.12, etc.

### ISSUE THREAD

**Issue by xsuchy** [fedora-copr/copr#2811]
* [x] https://bugzilla.redhat.com/show_bug.cgi?id=2219964 (copr-dist-git)
 * [x] https://bugzilla.redhat.com/show_bug.cgi?id=2225742 (copr-frontend - proposed fix against [python-sqlalchemy-utils](https://bugzilla.redhat.com/show_bug.cgi?id=2220523))
 * [x] https://bugzilla.redhat.com/show_bug.cgi?id=2220591 (rpkg)
 * [x] https://bugzilla.redhat.com/show_bug.cgi?id=2226400 (rpkg-macros)
 * [x] https://bugzilla.redhat.com/2208579 (rpm-git-tag-sort) 
 * [ ] https://bugzilla.redhat.com/show_bug.cgi?id=2220589 (resalloc-openstack)

**Comment by FrostyX** [comment]
I added RHBZ 2226400 to this issue as well.
Also, I am switching all the bugs to the ASSIGNED state to hopefully stop the FTBFS email spam.
