### ISSUE TITLE
Do we support multi group alias for one group or not?

### ISSUE THREAD

**Issue by pkking** [fedora-copr/copr#2825]
Opened the issue because im confused by these [code](https://github.com/fedora-copr/copr/blob/main/frontend/coprs_frontend/coprs/views/groups_ns/groups_general.py#L32C1-L49C67):
```
        if fas_group not in flask.g.user.user_teams:
            raise InsufficientRightsException(
                "User '{}' doesn't have access to fas group {}"
                .format(flask.g.user.username, fas_group))

        alias = form.name.data
        group = UsersLogic.get_group_by_fas_name_or_create(
            fas_group, alias)

        db.session.add(group)
        db.session.commit()

        flask.flash(
            "FAS group {} is activated in the Copr under the alias {} "
            .format(fas_group, alias)
        )
        return flask.redirect(url_for(
            "groups_ns.list_projects_by_group", group_name=alias))
```
The code above will allow user submit more than one alias for a group, but if the group already has a alias, it just will always return it instead of create another alias, so the code behave is wired:
1. if we allow multi alias for one group, the maybe we should make a new method `get_group_by_fas_name_and_alias_or_create` to both match the alias and group name
2. if just one alias is allowed, the redirect should be using `group.name` instead of  `alias`

**Comment by praiskup** [comment]
There's just 1:1 mapping, and `if form.validate_on_submit()` does some checking.  There's though a race condition that we should fix, perhaps by installing unique key https://github.com/fedora-copr/copr/blob/7442ec4303f2e0ba2e31a6555c4da34b96de0ee1/frontend/coprs_frontend/coprs/models.py#L2210

**Comment by pkking** [comment]
Otherwise, the `form.validate_on_submit()` just check if the alias already existed, but if we try to add another alias for a group, it will try to redirect to `/group/g/<new alias>/coprs` which will return 404, i think we should just redirect to  `/group/g/<existed alias>/coprs`.
