### ISSUE TITLE
s390x machines fail to start

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2829]
```
ibm_cloud_sdk_core.api_exception.ApiException: Error: A non-dedicated host VSI with this profile (2 vCPUs) will put user over quota. Allocated to instances: 200, Allocated to dedicated hosts: 0, Quota: 200, Code: 400
```

**Comment by praiskup** [comment]
We are affected by IBM Cloud ticket:
[Severity 4: BaremetalNicSpec not found](https://cloud.ibm.com/#)
New | CS3485778 | 2 days ago

**Comment by praiskup** [comment]
I did this hot fix in production:
```
    try:
        response_list = service.list_floating_ips().get_result()['floating_ips']
        for floating_ip in response_list:
            if floating_ip["name"].startswith(instance_name):
                log.debug("Found floating IP %s", floating_ip["name"])
                floating_ip_id = floating_ip["id"]
    except:
        pass
```

It is a bit hard to believe it actually helps the situation :-(  but it does, I applied this yesterday and s390x builds are being processed.

**Comment by nikromen** [comment]
> I did this hot fix in production:
> 
> ```
>     try:
>         response_list = service.list_floating_ips().get_result()['floating_ips']
>         for floating_ip in response_list:
>             if floating_ip["name"].startswith(instance_name):
>                 log.debug("Found floating IP %s", floating_ip["name"])
>                 floating_ip_id = floating_ip["id"]
>     except:
>         pass
> ```
> 
> It is a bit hard to believe it actually helps the situation :-( but it does, I applied this yesterday and s390x builds are being processed.

I can't see the hotfix in our production anymore - perhaps due to new release? Seems like the ticket was resolved by imb

> [Severity 4: BaremetalNicSpec not found](https://cloud.ibm.com/#)

btw this link is broken

**Comment by FrostyX** [comment]
We don't have the workaround in production anymore and it seems to be working.
