### ISSUE TITLE
epel7 + ppc64le: GCC build failures

### ISSUE THREAD

**Issue by lzaoral** [fedora-copr/copr#2875]
For some reason, builds of C/C++ software that use the distribution `CFLAGS` do not build succesfully.  E.g.:

* `cscppc` - https://download.copr.fedorainfracloud.org/results/lzaoral/test_builds/epel-7-ppc64le/06277487-smatch/builder-live.log.gz
* `smatch` - https://download.copr.fedorainfracloud.org/results/lzaoral/test_builds/epel-7-ppc64le/06277487-smatch/builder-live.log.gz

All the linked builds fail with the following `gcc` error:
```
foo.c:1:0: error: bad value (power8) for -mtune= switch
```

However, corresponding `koji` scratch builds finish fine. E.g. https://koji.fedoraproject.org/koji/buildinfo?buildID=2274342.

**Comment by praiskup** [comment]
Is it possible that Koji runs Power9 builders?  EPEL7 packages should stay compatible with Power8 I think.

**Comment by lzaoral** [comment]
@praiskup Sure!  Sorry for a late response, last week was rather busy.

**Comment by praiskup** [comment]
As @lzaoral pointed out, we actually install x86_64 packages for ppc64le chroots on ppc64le hosts :-/  the reason is that centos:7 image is probably not multi-arch image.

**Comment by praiskup** [comment]
Worked-around by disabling bootstrap_image for epel-7-ppc64, as that's probably the only affected chroot:
https://pagure.io/fedora-infra/ansible/c/7fab4cba72b1e443b5da1ad87a2abdd78474125c?branch=main

**Comment by praiskup** [comment]
Asking Podman upstream how to enforce the arch-native "podman pull": https://github.com/containers/podman/issues/19717

**Comment by praiskup** [comment]
This is going to be fixed by updating builders to Mock 5.1.
