### ISSUE TITLE
The %buildtag is not part of build.pkg_version

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2881]
E.g. in `copr monitor iucar/cran`, build before the update yesterday and after:

```
    {   
        "build_id": 5785431,
        "chroot": "fedora-38-x86_64",
        "name": "openbugs",
        "pkg_version": "3.2.3-1.copr5785431",
        "state": "succeeded"
    }   
    ,   
    {   
        "build_id": 5812006,
        "chroot": "fedora-39-x86_64",
        "name": "R",
        "pkg_version": "4.3.0-1",
        "state": "forked"
    }   
```

See the difference in `pkg_version`.  I'm not sure this is correct, while `%disttag` and other chroot-specific macros are correctly ignored, `%disttag` seems like the info which is chroot-agnostic and should be present (potentially help with sorting the builds in the monitor output).

**Comment by praiskup** [comment]
triage time: the %buildtag is only defined at SRPM/RPM build time, not while using python-specfile

**Comment by FrostyX** [comment]
This seems like a NOTABUG to me. When I open the `openbugs.spec`, there is

```
Release:        1%{?dist}%{?buildtag}
```

But when I open the `R.spec`, there is

```
Release:        1%{?dist}
```

That's the reason why there is no `.coprXYZ` in the release.

**Comment by praiskup** [comment]
Can you take a look at this build? https://copr.fedorainfracloud.org/coprs/praiskup/gnupg2-no-file-is-digest-patch/build/6361819/
