### ISSUE TITLE
Is obs-sign using the downstream "file-is-digest" patch?

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2885]
https://src.fedoraproject.org/rpms/gnupg2/blob/rawhide/f/gnupg-2.4.1-file-is-digest.patch#_76

But we produce V4 signatures, so it seems we don't need that patch?

Per report from @Jakuje

**Comment by Conan-Kudo** [comment]
It is still needed for the Open Build Service to run with Fedora's obs-sign package.

**Comment by praiskup** [comment]
Indeed, obs-sign by default expects `--files-are-digests` (OpenSUSE downstream patch for gnupg2) while fedora has a different downstream patch with `--file-is-digest`.  So fedora needs a downstram-patch for obs-sign, too chaning the parameter.
