### ISSUE TITLE
More reliable SSH connection to builders

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2888]
There's an interesting situation that has been bothering me for quite some time, and I finally got to a debugging.  Here we go:

1. resalloc-server is controlling hypervisors over virsh+ssh, and VMs started there over SSH, too
2. resalloc-server successfully allocates a new VM on our hypervisor
3. resalloc ticket taken by Copr worker daemon is assigned to that machine
4. some disk failure occurs on the hypervisor, causing every attempt to read/write something on '/' ends up in an uninterruptable process ('D' in ps aux)
5. this affects VMs as well
6. any new attempt to establish a new SSH connection to the hypervisor or VM on it fails
7. resalloc is able to detect this situation, and request the VM removal (but not successfully, of course, no new SSH connection can be established to hypervisor to terminate the machine)
8. Copr doesn't recognize this situation;  we have opened an SSH connection to the worker to run `copr-rpmbuild-log` process, but that is `D` process hanging forever, and the already opened SSH connection stays forever (it doesn't touch disk, so the remote sshd simply keeps posting keepalive packets to keep the SSH connection alive)
9. Since the SSH connection persists, we wait indefinitely keeping the task in a "running" state
10. This likely doesn't timeout (I haven't checked), because the timeout is implemented remotely over `copr-rpmbuild`.

**Comment by praiskup** [comment]
This is a very interesting situation from the `ssh` client's perspective.  The controlling channel is kept open to a totally broken machine.  There's no way to detect the underlying process (application in shell) hung up because it never returns back from the `D` state.

It would be nice to resolve this from the Resalloc side, but we have no SSH connection to the hypervisor to perform additional actions (like shutting down the machine which would terminate the SSH connection from the remote side).
This coming to my mind over again, but I don't really want to implement "ssh checking" in Copr again. Ideas?

**Comment by praiskup** [comment]
To be more precise, resalloc-server attempts to remove the resource (VM), but unsuccessfully. So the resource is eventually removed from resalloc's database (and later garbage collected, once hypervisor comes up again), and the ticket is `state=FAILED`.  But we neither periodically check for the ticket state in Copr to recover from this -> we simply rely on the SSH connection stability.

I'm experimenting with ssh [`ControMaster=auto`](https://pagure.io/fedora-infra/ansible/c/5ea82ed5912a033ce778270c74cd171f1ff0dda4?branch=main) again which could help a bit?

In the future it would perhaps allow us to implement a periodic "keepalive" action (instead of the built-in keepalive packets).  Something like:

```bash
while true; do
    timeout 60 ssh <remote host> 'touch > /affected-disk-mount/file'
done
```

**Comment by praiskup** [comment]
Since we implemented "timeout" for every SSH connection in (TODO PR ID), we mostly need to resolve point 8. (indefinitely running copr-rpmbuild-log process which is tail -F alias).  For this, we need to periodically check if resalloc ticket isn't in "FAILED" state.

**Comment by FrostyX** [comment]
Triage: So we basically need to modify our health-check to run some command like `cat /etc/os-release` or whatever?

**Comment by praiskup** [comment]
I think we should periodically check that the ticket isn't FAILED, close it (if so) and askf for a new ticket.
