### ISSUE TITLE
mageia-cauldron forked to mga10

### ISSUE THREAD

**Issue by ghibo** [fedora-copr/copr#2891]
Hi.

Actually, among the current chroot build options in copr, there is also:

mageia8-{aarch64,i586,x86_64}
mageia-cauldron-{aarch64,i586,x86_64}

However a few days ago mageia-cauldron was forked to mga10, so COPR now it's missing mageia9. Would it be possible to add the chroot build options for mageia9?

Thanks.

**Comment by praiskup** [comment]
We can do this once there's Mock 5.1 release with updated configs. https://github.com/rpm-software-management/mock/issues/1204

**Comment by FrostyX** [comment]
I added `mageia-9-x86_64`, `mageia-9-i586`, and `mageia-9-aarch64`.

**Comment by praiskup** [comment]
Cool, thanks!
