### ISSUE TITLE
Not packaged script: copr-backend-unknown-resalloc-tickets 

### ISSUE THREAD

**Issue by pkking** [fedora-copr/copr#2898]
Seems this useful script was not packaged in `backend`, recently i found it's useful since some of the ticket were not closed automatically :)
Is there any background i missed?

**Comment by FrostyX** [comment]
Hello @pkking,
this one?

https://github.com/fedora-copr/copr/blob/main/backend/run/copr-backend-unknown-resalloc-tickets.py

It should be packaged:

```
bash-5.2$ rpm -ql copr-backend |grep bin |grep unknown
/usr/bin/copr-backend-unknown-resalloc-tickets.py
```

**Comment by pkking** [comment]
Ah yes, i found it, as the file permission is `644`, so i missed it.
But it seems lack of `resalloc-server` package?
```
bash-5.1$ python3 /usr/bin/copr-backend-unknown-resalloc-tickets.py                                                                                                                                                                      
Traceback (most recent call last):                                                                                                                                                                                                       
  File "/usr/bin/copr-backend-unknown-resalloc-tickets.py", line 18, in <module>                                                                                                                                                         
    from resallocserver.app import session_scope                                                                                                                                                                                         
ModuleNotFoundError: No module named 'resallocserver' 
```

**Comment by praiskup** [comment]
It seems the script directly accesses Resalloc's database;  so you need to
configure the `server.yaml` and install resalloc-server also inside the backend
container (don't run it).

The thing is;  list of tickets is not something we want to publish over
Resalloc's API, so the backend container (as the client of resalloc using
/bin/resalloc cli) doesn't have the info how to log-in to a remote database.

**Comment by pkking** [comment]
> It seems the script directly accesses Resalloc's database; so you need to configure the `server.yaml` and install resalloc-server also inside the backend container (don't run it).
> 
> The thing is; list of tickets is not something we want to publish over Resalloc's API, so the backend container (as the client of resalloc using /bin/resalloc cli) doesn't have the info how to log-in to a remote database.

My case is there were some tickets stay unclosed status, so i should close them myself.

Eventually i ran the code in my `resalloc` container and print all the need-to-close ticket ids, and close them all :)

**Comment by FrostyX** [comment]
> Eventually i ran the code in my resalloc container and print all the need-to-close ticket ids, and close them all :)

Sounds good. Case closed then? Or is some further action required?

**Comment by praiskup** [comment]
> Eventually i ran the code in my resalloc container and print all the need-to-close ticket ids, and close them all :)

Well, the script in question is comparing the opened ticket IDs with ticket IDs assigned to running **backend** processes as seen in the `ps aux` output.  I actually bet that it is roughly equivalent to `resalloc-maint ticket-list`.

**Comment by praiskup** [comment]
I'm closing, but feel free to reopen if you think we can do something for this.
