### ISSUE TITLE
Some builds are stuck in the running state

### ISSUE THREAD

**Issue by FrostyX** [fedora-copr/copr#2936]
Some builds appear to be stuck in the running state. I briefly looked at the logs and it seems there is more than one cause.

![Screenshot_2023-10-02_12-27-04](https://github.com/fedora-copr/copr/assets/2151771/7d8ac22e-ff85-4937-a1ac-cbde60b110b7)

**Comment by FrostyX** [comment]
There was no way for us to switch them back to a pending state, obtain a new builder, and try again. I needed to fail all those builds, so I apologize for any inconvenience if this affected you. Please resubmit your builds if needed.

**Comment by praiskup** [comment]
> I needed to fail all those builds, so I apologize for any inconvenience if this affected you.

Killing the background worker (at least with 9) should indeed restart the build (worker disappears without telling the dispatcher, so the dispatcher starts a new worker instead).  If this isn't the actual behavior, it is a bug.

**Comment by praiskup** [comment]
hm, I suppose `kill -9` would be better next time (the background worker could actually partly recover from INT and have a chance to mark the build as failed).
