### ISSUE TITLE
Repos are ignored when retriggering custom build method

### ISSUE THREAD

**Issue by mfocko** [fedora-copr/copr#2941]
### How to reproduce

1. Build a package with custom method, using SRPM build dependencies from external/additional repo
2. Retrigger the build via Copr UI
3. Watch it fail

### Expected behavior

Additional repositories are preserved.

### Actual behavior

Additional repositories are ignored.

### Info

* Original build: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/package/netavark/
  * Logs: https://download.copr.fedorainfracloud.org/results/rhcontainerbot/podman-next/srpm-builds/06483363/builder-live.log.gz
* Retriggered build: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/6493814/
  * Logs: https://download.copr.fedorainfracloud.org/results/rhcontainerbot/podman-next/srpm-builds/06493814/builder-live.log.gz

CC @lsm5

**Comment by lbarcziova** [comment]
Another occurrence of this: https://download.copr.fedorainfracloud.org/results/rhcontainerbot/podman-next/srpm-builds/06564320/builder-live.log.gz

**Comment by FrostyX** [comment]
There is not only a problem with retriggering but also with submitting new custom build using web UI and wanting to use repos. They are completely being ignored in the web UI. So the first step of the reproducer

> 1. Build a package with custom method, using SRPM build dependencies from external/additional repo

Must IMHO be via API/copr-cli

Fixed in PR #2970
