### ISSUE TITLE
Blog post about per-team builders

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2946]
We have all the tooling in place to let our teams "sponsor" their own builders (e.g. via EC2, IBM Cloud, etc. accounts).  We just need to announce that this is possible.

**Comment by kwk** [comment]
@praiskup this sounds interesting. What about builders with commodity hardware GPUs that you'll probably not find in any cloud what exactly are the other accounts that this can connect to?

**Comment by kwk** [comment]
Is there any update on this?

**Comment by praiskup** [comment]
> Is there any update on this?

Sorry, no progress so far.  I hope for this week.

Anyway, you seem to be interested - the point here is to let people know they can give us cloud access tokens, and Copr admins - using those tokens - can configure a new [pool of workers](https://download.copr.fedorainfracloud.org/resalloc/pools).

The current implementation allows us to configure "dedicated builders" only, so your team has the access to them, but your builds need to request them explicitly (similarly to the powerful builders feature) and such builds never get any other builders.

**Comment by praiskup** [comment]
Proposal: https://github.com/praiskup/praiskup.github.io/pull/7
