### ISSUE TITLE
COPR lost the ability to run fedora-review around 2023-10-13

### ISSUE THREAD

**Issue by smooge** [fedora-copr/copr#2953]
I am working on a review for a package and using COPR to do the builds and run fedora-review. On Wednesday (2023-10-11) I was able to do a build and get a fedora-review working. When I tried to do one on Friday (2023-10-13), the build said it completed correctly, but no rpms were in the build and no fedora-review was seen. In the build.log the following message was found:

```
Last metadata expiration check: 0:04:22 ago on Fri Oct 13 16:37:34 2023.
Last metadata expiration check: 0:04:25 ago on Fri Oct 13 16:37:34 2023.
INFO:  ExclusiveArch dependency checking disabled, enable with EXARCH flag

WARNING: Illegal return from /usr/share/fedora-review/scripts/generic-large-docs.sh, code 80, output: stdout:Documentation size is 0 bytes in 1 files.
 stderr:/usr/share/fedora-review/scripts/generic-large-docs.sh: line 23: bc: command not found

Review template in: /var/lib/copr-rpmbuild/results/composefs/review.txt
fedora-review is automated tool, but *YOU* are responsible for manually
reviewing the results and finishing the review. Do not just copy-paste
```

https://copr.fedorainfracloud.org/coprs/smooge/composefs/builds/
working review: https://copr.fedorainfracloud.org/coprs/smooge/composefs/build/6517526/
broken review: https://copr.fedorainfracloud.org/coprs/smooge/composefs/build/6523959/

https://download.copr.fedorainfracloud.org/results/smooge/composefs/fedora-rawhide-x86_64/06523959-composefs/ is empty except for build logs.

Talked with praiskup on irc and it looks like some package which required bc no longer does so and so the review failed which stopped the final steps of copying in the rpms and such.

**Comment by praiskup** [comment]
applied [a patch](https://pagure.io/fedora-infra/ansible/c/a2d5a783f726e6b10407543fc9839c8ffd7c16f5) in prod, does it help?

**Comment by praiskup** [comment]
Per @smooge report, the work-around helped.

**Comment by FrostyX** [comment]
Already fixed in the upstream
https://pagure.io/FedoraReview/c/ebfdc2bbbd2374fe7cbf9415051cc9d3f7253bdd

But we need to keep our patch until new `fedora-review` release.
