### ISSUE TITLE
Enable powerful workers for `@asahi/kernel`

### ISSUE THREAD

**Issue by Conan-Kudo** [fedora-copr/copr#2966]
Per #2241 and #2925, I'd like for `@asahi/kernel` to have the powerful builders enabled for all chroots there for the `kernel` package in there.

**Comment by praiskup** [comment]
This should be deployed to production:
https://pagure.io/fedora-infra/ansible/c/b1d0d6c626cd9494efb60eac48e24e3090840ecd

Can you test?

**Comment by praiskup** [comment]
Closing as resolved. :-) happy building
