### ISSUE TITLE
copr is not getting full information from my external repository

### ISSUE THREAD

**Issue by katnatek** [fedora-copr/copr#2968]
I use the free branch of blogdrake's repositories in my builds and was working fine, but for mageia 9 is ignoring the noarch repository

For example, https://download.copr.fedorainfracloud.org/results/katnatek/blogdrake/mageia-9-i586/06565822-bottles/builder-live.log.gz complains about blueprint-compiler, but the package is there https://ftp.blogdrake.net/mageia/mageia9/free/noarch/blueprint-compiler-0.10.0-0.1bdk_mga9.noarch.rpm

This is my repo file 
[BDK-free.repo.txt](https://github.com/fedora-copr/copr/files/13171665/BDK-free.repo.txt)

**Comment by praiskup** [comment]
Thank you for the report, but this seems like an user error.  See the job specification in the builder-live.log:
```
...
 'repos': [{'baseurl': 'https://download.copr.fedorainfracloud.org/results/katnatek/blogdrake/mageia-9-i586/',
            'id': 'copr_base',
            'name': 'Copr repository',
            'priority': None},
           {'baseurl': 'http://ftp.blogdrake.net/mageia/9/free/i586/',
            'id': 'http_ftp_blogdrake_net_mageia_9_free_i586',
            'name': 'Additional repo http_ftp_blogdrake_net_mageia_9_free_i586'}],
...
```

The `blueprint-compiler` is present in the `noarch` repo, but you only specified the arch-specific repo in Copr.
Closing as invalid, but feel free to reopen.

**Comment by katnatek** [comment]
> Thank you for the report, but this seems like an user error. See the job specification in the builder-live.log:

That was a test using a static url, BTW I use a repo file per repository and works but not like me too much

**Comment by katnatek** [comment]
> Not sure I understand. Both the repositories need to be configured in Copr:

I was used to setting the external repo with https://ftp.blogdrake.net/mageia/$releasever/free//$basearch , and I test https://ftp.blogdrake.net/mageia/9/free/i586 (or x86_64) (for i586 I have a i386 symlink)

I also note a bug on mageia 9 dnf, with the original configuration was not found the xml metadata for noarch but the url reported look like if  $releasever is empty :s

Thank you for your interest, I now use https://ftp.blogdrake.net/mageia/$releasever/free//$basearch
https://ftp.blogdrake.net/mageia/$releasever/free/noarch/ for the external repos in copr and that works
