### ISSUE TITLE
Enable powerful workers for `ngompa/kernel-ark-exp-dev`

### ISSUE THREAD

**Issue by Conan-Kudo** [fedora-copr/copr#2985]
I'd like for `ngompa/kernel-ark-exp-dev` to have access to powerful workers for my kernel development work for Fedora and CentOS Hyperscale. I need both aarch64 and x86_64 workers.

**Comment by Conan-Kudo** [comment]
cc: @davdunc @davide125 @michel-slm

**Comment by praiskup** [comment]
Thank you for the ticket, done: https://pagure.io/fedora-infra/ansible/c/eb7fe4b5ba85d0e5174610657d58dadb1adc05a4
