### ISSUE TITLE
Enable powerful workers on `@centoshyperscale/kernel`

### ISSUE THREAD

**Issue by Conan-Kudo** [fedora-copr/copr#2986]
I'd like for `@centoshyperscale/kernel` to have access to powerful workers for CentOS Hyperscale `kernel` package work. This needs both x86_64 and aarch64.

**Comment by Conan-Kudo** [comment]
cc: @davdunc @davide125 @michel-slm

**Comment by praiskup** [comment]
Thank you for the ticket, done: https://pagure.io/fedora-infra/ansible/c/eb7fe4b5ba85d0e5174610657d58dadb1adc05a4
