### ISSUE TITLE
Request high-performance builders for @fedora-llvm-team/llvm-snapshots

### ISSUE THREAD

**Issue by kwk** [fedora-copr/copr#2987]
Hi, I'd like to [request high-performance builders](https://docs.pagure.org/copr.copr/user_documentation/powerful_builders.html#how-to-request-high-performance-builders) for these projects/packages:

@fedora-llvm-team/llvm-snapshots/x86_64/llvm
@fedora-llvm-team/llvm-snapshots/x86_64/clang

The effect of this should be visible in our build times:

https://kwk.github.io/llvm-daily-fedora-rpms/fig-llvm.html

FYI: @tstellar @nikic @tuliom

**Comment by nikic** [comment]
I'm not sure this makes sense. Our slow builds are ppc64le and s390x, so having fast x86_64 or aarch64 builds doesn't buy us a lot.

Given that these machines have high cost and limited supply, we're probably not the best users for them.

**Comment by praiskup** [comment]
Thank you for the ticket, done: https://pagure.io/fedora-infra/ansible/c/eb7fe4b5ba85d0e5174610657d58dadb1adc05a4

**Comment by kwk** [comment]
As discussed with @praiskup offline, we'll keep an eye on the build performance. I want to find out what the optimum performance is that we can get now. After that we can give the machines back. It could be that we come up with a way to cancel builds on slower architectures earlier if they fail on the fast ones. Maybe that saves costs then?

**Comment by praiskup** [comment]
@kwg sounds reasonable. Actually, as discussed in https://github.com/fedora-copr/copr/issues/2241 it seems that the builds on powerful builders, because they finish much faster, aren't [significantly more expensive](https://docs.google.com/spreadsheets/d/1JZSmy6ECYZmpcleg4zENo_dvAx3IAr7AsKlrBP9__6s/edit?usp=sharing).

**Comment by kwk** [comment]
@praiskup I've made a follow-up request here: https://pagure.io/fedora-infra/ansible/pull-request/1625 . I forgot that we build in incubator projects and each day those have a different name which is now caught by a new regex.

**Comment by kwk** [comment]
As discussed in chat with @praiskup we want to reopen this issue to get fast builders for aarch64, ppc64le, and s390x architectures. I've created the PR for this here: https://pagure.io/fedora-infra/ansible/pull-request/2810

@praiskup can you please reopen this issue because I don't have the permission to do so.

**Comment by praiskup** [comment]
Thank you for the update here, and for the PR.  I think we can just keep this closed as the PR is now deployed.
