### ISSUE TITLE
Copr uses non-standard `username` field of OIDC UserInfo

### ISSUE THREAD

**Issue by Bob131** [fedora-copr/copr#3008]
I ran into a hitch trying to use [Forgejo](https://forgejo.org) as an OpenID Connect provider for Copr: in two places ([here](https://github.com/fedora-copr/copr/blob/44aa094c5389eb8e9caf106f37ff85a4c9111a8d/frontend/coprs_frontend/coprs/auth.py#L395) and [here](https://github.com/fedora-copr/copr/blob/44aa094c5389eb8e9caf106f37ff85a4c9111a8d/frontend/coprs_frontend/coprs/views/misc.py#L118)) the code assumes that the UserInfo contains a field ("claim"?) named `username`. AFAICT (and I apologise if this is incorrect; I'm not familiar with OpenID) this is a non-standard Ipsilonism (see [OpenID Connect Core 1.0 §5.1](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims)); at the very least, [Forgejo doesn't provide it](https://codeberg.org/forgejo/forgejo/src/commit/99a93025d27480aa5a6f7e923558a292dcbde28c/routers/web/auth/oauth.go#L269).

It's not obvious to me how to replace the reliance on `username`, though: [OIDCC §5.7](https://openid.net/specs/openid-connect-core-1_0.html#ClaimStability) says of `preferred_username`

>Claims such as email, phone_number, and preferred_username and MUST NOT be used as unique identifiers for the End-User.

It happens to be the case, however, that Forgejo's value for `preferred_username` _is_ unique, and I can imagine that would probably be common for OIDC providers. Maybe there could be an option in `copr.conf` along the lines of `OIDC_UNIQUE_PREFERRED_USERNAMES`?

**Comment by nikromen** [comment]
> Maybe there could be an option in copr.conf along the lines of OIDC_UNIQUE_PREFERRED_USERNAMES?

Yes, it is surely possible. If the default behaviour of Copr stays unchanged and it will not affect us. If you implement a different behavior that's possible to change by config then we are fine with that. Do you want to submit a patch for it? We'll happily review it.

**Comment by Bob131** [comment]
Sure, I can give that a stab.
