### ISSUE TITLE
Permissions not correct for `mvadkert` on https://copr.fedorainfracloud.org/coprs/g/teemtee/tmt/

### ISSUE THREAD

**Issue by thrix** [fedora-copr/copr#3009]
Even if I am in the group correctly set, I had to ask for permission to be able to resubmit.

Internal link:
https://redhat-internal.slack.com/archives/C04N9MT0KCL/p1700481588754019

**Comment by praiskup** [comment]
The trick - if I remember correctly - is that we should not just log-out/log-in from/to Copr, but also in FAS/Ipsilon.  We should at least document this.
