### ISSUE TITLE
Is copr-cli compatible with wget2?

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#3010]
There is the "download-build" feature in copr-cli.  Fedora plans to move to wget2:
https://fedoraproject.org/wiki/Changes/Wget2asWget

It would be nice to quickly check if wget2 as wget will continue working "correctly" for us.

**Comment by nikromen** [comment]
Regarding my research wget2 is compatible with wget and how we use it. To be 100% sure I ran beaker tests with the alias wget=wget2 and there were no problems whatsoever.

**Comment by praiskup** [comment]
Are you sure the alias worked? :-)

**Comment by praiskup** [comment]
@nikromen is going to run the test which covers `copr download-build` use-case.

**Comment by nikromen** [comment]
works
