### ISSUE TITLE
Fedora ELN build failures: missing xmlto

### ISSUE THREAD

**Issue by minfrin** [fedora-copr/copr#3014]
Currently builds of httpd are failing for Fedora ELN, due to a missing xmlto package.

```
Package findutils-1:4.9.0-6.eln131.aarch64 is already installed.
Package pkgconf-pkg-config-1.9.5-2.eln131.aarch64 is already installed.
No matching package to install: 'xmlto'
Not all dependencies satisfied
Error: Some packages could not be found.

Copr build error: Build failed
```

xmlto is available on rawhide.

https://copr.fedorainfracloud.org/coprs/minfrin/patched/build/6680087/

**Comment by FrostyX** [comment]
Hello @minfrin,
thank you for the report.

There is nothing we can do about this though, I can you please report the issue directly to the Fedora ELN folks?
https://github.com/fedora-eln/eln/issues

**Comment by minfrin** [comment]
Added as https://github.com/fedora-eln/eln/issues/172, thank you.
