### ISSUE TITLE
Enlarge the disk on Fedora Copr dist-git

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#3020]
I measured the cleanup crawler running time, and it took about 25h this week.  So I don't think it is a good idea to run this daily or so.  When the cleanup script finished, we had 4T used and 1T free. I'd propose to:

- [x] Increase the cron job cleanup frequency from 30 days to 14 days
- [x] Give the storage +1TB

**Comment by FrostyX** [comment]
Nagios alerts started coming again.

```
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme1n1p1  5.3T  4.5T  613G  89% /var/lib/dist-git
```

**Comment by praiskup** [comment]
The +1 TB is done.

**Comment by praiskup** [comment]
Increased cron job frequency: https://pagure.io/fedora-infra/ansible/c/5766ff851c5ccb571468c945c997f1bb1285b830
