### ISSUE TITLE
spec release field with undefined srpm macro causes no rpms to be saved

### ISSUE THREAD

**Issue by juhp** [fedora-copr/copr#3024]
See this pathological build: https://copr.fedorainfracloud.org/coprs/petersen/haskell-language-server/build/6682636/

- For both builds (one success and one failure) no srpm was saved
- For the successful build no rpms were saved!

This seems due to the srpm having:

Package: [ haskell-language-server-ghc9.4 ](https://copr.fedorainfracloud.org/coprs/petersen/haskell-language-server/package/haskell-language-server-ghc9.4/)
Version: 2.4.0.0-2.ghc%{ghc_version}

vs

File Name: haskell-language-server-ghc9.4-2.4.0.0-2.fc40.ghc9.4.7.src.rpm

Compare this with a good srpm: https://copr.fedorainfracloud.org/coprs/petersen/haskell-language-server/build/6685124/
where you can see the srpms were saved for both success and failed builds.

My guess is that copr might be looking for `haskell-language-server-ghc9.4-2.4.0.0-2.ghc%{ghc_version}*` and so ignored the `haskell-language-server-ghc9.4-2.4.0.0-2.fc40.ghc9.4.8*` or something like that perhaps?

**Comment by praiskup** [comment]
Thank you for the report, but I see this (in my location, BRQ):
```
$ lftp -e 'ls | grep rpm; exit' https://download.copr.fedorainfracloud.org/results/petersen/haskell-language-server/fedora-rawhide-x86_64/06682636-haskell-language-server-ghc9.4/
cd ok, cwd=/results/petersen/haskell-language-server/fedora-rawhide-x86_64/06682636-haskell-language-server-ghc9.4                                                                 
-rw-r--r--  --  haskell-language-server-ghc9.4-2.4.0.0-2.fc40.ghc9.4.8.x86_64.rpm
-rw-r--r--  --  haskell-language-server-ghc9.4-2.4.0.0-2.fc40.ghc%{ghc_version}.src.rpm
$ lftp -e 'ls | grep rpm; exit' https://download.copr.fedorainfracloud.org/results/petersen/haskell-language-server/fedora-rawhide-x86_64/06685124-haskell-language-server-ghc9.4/
cd ok, cwd=/results/petersen/haskell-language-server/fedora-rawhide-x86_64/06685124-haskell-language-server-ghc9.4                                                                 
-rw-r--r--  --  haskell-language-server-ghc9.4-2.4.0.0-2.fc40.ghc9.4.8.x86_64.rpm
-rw-r--r--  --  haskell-language-server-ghc9.4-2.4.0.0-2.fc40.ghc9.4.8.src.rpm
```

You seem to face the [FAQ: Build succeeded, but I don’t see the built results?](https://docs.pagure.org/copr.copr/user_documentation.html#build-succeeded-but-i-don-t-see-the-built-results)

**Comment by praiskup** [comment]
This is tricky thing, and we should tweak the caches somehow #2169

**Comment by juhp** [comment]
Okay you are right, I am wrong:

https://copr-be.cloud.fedoraproject.org/results/petersen/haskell-language-server/fedora-rawhide-x86_64/06682636-haskell-language-server-ghc9.4/

**Comment by juhp** [comment]
I will delete that unwanted build now anyway with the bad nvrs
