### ISSUE TITLE
Conflicting packages - limesuite

### ISSUE THREAD

**Issue by canislupus11** [fedora-copr/copr#3027]
Fedora 38 and: 

#dnf install limesuite
Last metadata expiration check: 0:00:28 ago on Mon Nov 27 00:37:07 2023.
Error: 
 Problem: problem with installed package cryfs-0.11.3-1.fc38.x86_64
  - package cryfs-0.11.3-1.fc38.x86_64 from @System requires libspdlog.so.1.11()(64bit), but none of the providers can be installed
  - package cryfs-0.11.3-1.fc38.x86_64 from fedora requires libspdlog.so.1.11()(64bit), but none of the providers can be installed
  - cannot install both spdlog-1.12.0-2.1.fc38.x86_64 from copr:copr.fedorainfracloud.org:rezso:SDR and spdlog-1.11.0-5.fc38.x86_64 from @System
  - cannot install both spdlog-1.11.0-5.fc38.x86_64 from fedora and spdlog-1.12.0-2.1.fc38.x86_64 from copr:copr.fedorainfracloud.org:rezso:SDR
  - package python3-gnuradio-3.11.0.0-20231117.0.git49033801.fc38.x86_64 from copr:copr.fedorainfracloud.org:rezso:SDR requires libspdlog.so.1.12()(64bit), but none of the providers can be installed
  - problem with installed package python3-gnuradio-3.10.4.0-6.fc38.x86_64
  - package python3-gnuradio-3.10.4.0-6.fc38.x86_64 from @System requires libSoapySDR.so.0.8()(64bit), but none of the providers can be installed
  - package python3-gnuradio-3.10.4.0-6.fc38.x86_64 from fedora requires libSoapySDR.so.0.8()(64bit), but none of the providers can be installed
  - cannot install both SoapySDR-0.8.1-20230605.1.gitbb33b2d2.fc38.x86_64 from copr:copr.fedorainfracloud.org:rezso:SDR and SoapySDR-0.8.1-8.fc38.x86_64 from @System
  - cannot install both SoapySDR-0.8.1-8.fc38.x86_64 from fedora and SoapySDR-0.8.1-20230605.1.gitbb33b2d2.fc38.x86_64 from copr:copr.fedorainfracloud.org:rezso:SDR
  - package limesuite-23.11.0-20231119.0.gitc2d9e877.fc38.x86_64 from copr:copr.fedorainfracloud.org:rezso:SDR requires libSoapySDR.so.0.8-3()(64bit), but none of the providers can be installed
  - conflicting requests
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages)

**Comment by praiskup** [comment]
Thank you for the report, but you opened a ticket here against the build system (the infrastructure folks, not responsible for the content). This issue seems like a Fedora 38 vs. [copr project](https://copr.fedorainfracloud.org/coprs/rezso/SDR) incompatibility.  Please log in and [contact the maintainer of the repository](https://copr.fedorainfracloud.org/coprs/rezso/).
