### ISSUE TITLE
The Fedora Copr Frontend backup doesn't seem to work

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#3035]
There's just `/backups/coprdb-2023-03-20.dump.xz` file, and the one that I created now.  We should check it is working.

**Comment by praiskup** [comment]
We should consider using a different compression algorithm, xz is too slow (20 minutes is a painful waiting during outage windows).

**Comment by FrostyX** [comment]
The backups are run from Cron

```
/etc/cron.d/cron-backup-database-coprdb:0 0 * * * postgres /usr/local/bin/backup-database coprdb
```

And today's backup is there:

```
[root@copr-fe ~][PROD]# ls /backups -l
total 551408
-rw-r--r--. 1 postgres postgres 564637872 Jan  8 01:40 coprdb-2024-01-08.dump.xz
```
