### ISSUE TITLE
Verbose DNF5 logs in Fedora Copr

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#3040]
So far I deployed `package_manager=dnf5` [release](https://rpm-software-management.github.io/mock/Release-Notes-Configs-39.3) only on our [staging instance](https://copr.stg.fedoraproject.org/).  But the DNF5 logs there are pretty ugly, snippet:

```
Installing groups:                                                                   
 Buildsystem building group                                                          

Transaction Summary:
 Installing:      152 packages

Total size of inbound packages is 52 MiB. Need to download 52 MiB.
After this operation 180 MiB will be used (install 180 MiB, remove 0 B).
[?25l[  1/152] bash-0:5.2.21-2.fc40.x86_64   0% |   0.0   B

[  1/152] bzip2-0:1.0.8-16.fc39.x86_64 100% |  52.3 KiB
[  2/152] bash-0:5.2.21-2.fc40.x86_64   0% |   0.0   B
[  3/152] coreutils-0:9.4-1.fc40.x86_64   0% |   0.0   B

[  2/152] cpio-0:2.14-5.fc40.x86_64 100% | 279.5 KiB
[  3/152] bash-0:5.2.21-2.fc40.x86_64   1% |  34.3 KiB
[  4/152] coreutils-0:9.4-1.fc40.x86_64  14% | 162.1 KiB

[  3/152] coreutils-0:9.4-1.fc40.x86_64 100% |   1.1 MiB
[  4/152] bash-0:5.2.21-2.fc40.x86_64  27% | 514.3 KiB
[  5/152] diffutils-0:3.10-3.fc39.x86_64  64% | 258.3 KiB

[  4/152] diffutils-0:3.10-3.fc39.x86_64 100% | 398.3 KiB
[  5/152] bash-0:5.2.21-2.fc40.x86_64  27% | 514.3 KiB
[  6/152] fedora-release-common-0:40-0.20.noarch   0% |   0.0   B
...
```
It seems that we should either revisit the stdout/stderr filter installed in Mock, or the one we have in `copr-rpmbuild`.  Not sure, or maybe there are some options in DNF5 to make the output more "logger" friendly? @evan-goode

**Comment by evan-goode** [comment]
I think https://github.com/rpm-software-management/mock/pull/1261 is the main problem here, but even after changing Mock to invoke DNF 5 with a pipe on stdout and not a PTY, the logs are still garbled due to https://github.com/rpm-software-management/dnf5/issues/1058.
