### ISSUE TITLE
copr-pypi has stopped building packages 

### ISSUE THREAD

**Issue by 9001** [fedora-copr/copr#3056]
looks like something died; no packages have been built since 2023-11-28, 17:07 UTC

timewise, this overlaps with #2964 / https://pagure.io/fedora-infrastructure/issue/11648 

if this should be brought up somewhere else then please point me in the right direction 👍 and thx for the service!

**Comment by praiskup** [comment]
Last build: https://copr.fedorainfracloud.org/coprs/g/copr/PyPI/build/6702502/
