### ISSUE TITLE
copr with dnf5 cannot handle file dependency?

### ISSUE THREAD

**Issue by mtasaka** [fedora-copr/copr#3070]
So I see copr again uses dnf4, however anyway I report this issue, because probably in the future copr will use dnf5 again. Not sure where to ask, but firstly here.

With copr / dnf5, it seems dnf5 cannot handle file dependency.

Example: mapserver has BuildRequires for specific file: https://src.fedoraproject.org/rpms/mapserver/blob/e4691be9fd071d880107f6c0b3b56d4ca80618a5/f/mapserver.spec#_69

> BuildRequires:  /usr/share/fonts/dejavu-sans-fonts/DejaVuSans.ttf

With dnf5, it seems dnf5 cannot find this:
https://copr.fedorainfracloud.org/coprs/mtasaka/rubydep-heavypkg-test-3-2/build/6764308/

```
Failed to resolve the transaction:
No match for argument: /usr/share/fonts/dejavu-sans-fonts/DejaVuSans-Bold.ttf
No match for argument: /usr/share/fonts/dejavu-sans-fonts/DejaVuSans.ttf
```

But this is actually provided by dejavu-sans-fonts-2.37-21.fc40.noarch :
https://koji.fedoraproject.org/koji/buildinfo?buildID=2305078

And after switching back to dnf4, build for mapserver is successful:
https://copr.fedorainfracloud.org/coprs/mtasaka/rubydep-heavypkg-test-3-2/build/6766623/

**Comment by praiskup** [comment]
From what I've heard, this is expected.  But I'd let @evan-goode comment on this one.
Have we already adjusted the Fedora Packaging Guidelines related to non-/bin and non-/etc (build)requirements?

**Comment by evan-goode** [comment]
Yes, this is expected. DNF 5 does not download filelist metadata by default, and soon, DNF 4 will also not download filelists: https://discussion.fedoraproject.org/t/f40-change-proposal-dnfconditionalfilelists-system-wide/94939. The performance cost of filelists is very high, and few packages use these path dependencies.

The [Packaging Guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/#_file_and_directory_dependencies) were updated [here](https://pagure.io/packaging-committee/pull-request/1321) to say packages "must not" depend on paths outside of `/usr/bin`, `/usr/sbin`, or `/etc`.

**Comment by xsuchy** [comment]
Closing as this is DNF new feature. Feel free to discuss it under DNF Change proposal.
