### ISSUE TITLE
Error connecting to the udisks daemon

### ISSUE THREAD

**Issue by ycollet** [fedora-copr/copr#3080]
I've got a build on COPR which fails with this error:
```
Error connecting to the udisks daemon: Could not connect: No such file or directory
```
The build is located here:
https://copr.fedorainfracloud.org/coprs/ycollet/audinux/build/6823916/

**Comment by FrostyX** [comment]
Hello @ycollet,
thank you for the report.

Did you try to build the package locally using Mock and/or rpmbuild? Can this be maybe a missing dependency?

**Comment by ycollet** [comment]
I finally built the package.
I think there was a build problem in the package and upstream made a new release which fixed the build.
This error message was a little bit misleading :)
Do you want me to close the ticket ?

**Comment by FrostyX** [comment]
Ah, I am glad it is sorted out :-)
