### ISSUE TITLE
Sort the per-owner group so that temporary projects are after normal projects

### ISSUE THREAD

**Issue by ekohl** [fedora-copr/copr#3087]
For https://copr.fedorainfracloud.org/groups/g/theforeman/coprs/ we have a lot of scratch repositories (which we use to test PRs), but because of that you lose track of the real repositories. Because the real names are also prefixes for the names of temporary you can't use search either.

Some solutions that come to mind:
* Allow pinning some repositories (like GitHub does)
* Allow filtering (hide temporary repositories)
* Stricter searching

And there may be more solutions.

**Comment by FrostyX** [comment]
Hello @ekohl,
thank you for the feedback.

> Allow pinning some repositories (like GitHub does)

Actually, we have this for quite some time - https://frostyx.cz/posts/create-your-portfolio-with-pinned-projects

**Comment by praiskup** [comment]
This seems implemented then.  Closing (feel free to reopen or add suggestions!)

**Comment by ekohl** [comment]
Sorry for not getting around to it earlier. I wasn't a member of our `@theforeman` group so I couldn't test it.

It does appear you can only pin 4, so it's not a solution. For Foreman we have a few repositories:

* foreman
* foreman-plugins
* katello
* pulpcore
* candlepin

For each of these there are various release streams. `foreman`, `foreman-plugins` and `katello` each have 3 or 4 (nightly, 2 latest supported versions and sometimes a release candidate). Pulpcore has a slightly different model for the number of supported versions, but with a similar end result.

So I still think you should be able to hide all temporary repositories on your overview.

**Comment by praiskup** [comment]
Triage time:
- this is especially painful because #3046 -> it's going to clean most of the projects in given project
- we could as an easy fix propose sorting the projects so that temporary projects have lower priority ... after the normal projects
