### ISSUE TITLE
copr-dist-git problems -> low memory, high IOPS for swap

### ISSUE THREAD

**Issue by nikromen** [fedora-copr/copr#3089]
two options to solve this:
- request stronger machine
- provision disk that can manage more IOPS

**Comment by praiskup** [comment]
Some proposals are in a private thread: https://redhat-internal.slack.com/archives/C04QH3LP0NQ/p1704647679308729

**Comment by praiskup** [comment]
Similar problem occurred a while ago, there was like >= 100 cgit processes;  I dropped the executable bit on the cgit (temporarily) binary, and the system almost immediately recovered.

**Comment by praiskup** [comment]
Seems like this is related also to #2410 (the file has now >= 100MB).

**Comment by praiskup** [comment]
Triage brainstorm:
@praiskup do we have a limit for parallelism? (max 10 cgit processes..)
@xsuchy one of the options is block robots, but it has consequences

Seems like the easiest option is to bump to the instance (see the slack chat above).

**Comment by praiskup** [comment]
Doubled RAM, +33% IOPS, +33% price: https://instances.vantage.sh/aws/ec2/r5a.xlarge

**Comment by praiskup** [comment]
r7a is the newer generation actually

**Comment by FrostyX** [comment]
I upgraded the instance to [r7a.xlarge](https://instances.vantage.sh/aws/ec2/r7a.xlarge)
