### ISSUE TITLE
Package FedoraDistroAliases to Fedora

### ISSUE THREAD

**Issue by nikromen** [fedora-copr/copr#3090]
ssia

**Comment by praiskup** [comment]
Please consider pinging to python3-bodhi maintainers first.

**Comment by praiskup** [comment]
Relates to this PR: https://github.com/rpm-software-management/tito/pull/476

**Comment by FrostyX** [comment]
Upstream: https://github.com/rpm-software-management/fedora-distro-aliases
PyPI: https://pypi.org/project/fedora-distro-aliases/
Package Review: https://bugzilla.redhat.com/show_bug.cgi?id=2257845

**Comment by FrostyX** [comment]
The review was done by Michel Lind,
I already submitted Bodhi updates - https://bodhi.fedoraproject.org/updates/FEDORA-2024-cbe16bd838
