### ISSUE TITLE
failed or cancelled builds cause the next successful build to have an empty Chroot directory after it finishes

### ISSUE THREAD

**Issue by matte-schwartz** [fedora-copr/copr#3103]
You can see an example of a build that failed and I had to tweak several times here with the empty directory bug: https://download.copr.fedorainfracloud.org/results/matte-schwartz/Neptune-Mirror/fedora-39-x86_64/06889681-kernel/

I can retrieve the packages from COPR via dnf once they are built, but the web interface just shows me the three log files. I've noticed this in other repositories too.

**Comment by praiskup** [comment]
Thank you for the report, this is in FAQ, and we should fix the CDN configuration, but the results are there - you just faced a temporarily cached page: #2169
