### ISSUE TITLE
MOTD for builders with user SSH access

### ISSUE THREAD

**Issue by FrostyX** [fedora-copr/copr#3119]
Followup after #2977,
we should configure MOTD for our builders with user SSH access.

Ideally, we should print the output of `copr-builder help`

**Comment by praiskup** [comment]
vmhost-p09-copr01.rdu-cc.fedoraproject.org

**Comment by praiskup** [comment]
> Ideally, we should print the output of copr-builder help

I'm not 100% motd should run Python scripts, it non-error-prone as possible (simple permission issues can cause a non-working SSH, etc.)

**Comment by praiskup** [comment]
Ufff... :) After meetings and debugging (facing ugly non-determinism), it seems that the problem is that we use SSH's ControlMaster feature to cache connections to our builders and that the MOTD is **only** printed out when a **new connection** is established.

**Comment by nikromen** [comment]
This fixes it: https://pagure.io/fedora-infra/ansible/pull-request/1797#
and https://github.com/fedora-copr/copr/pull/3156

**Comment by praiskup** [comment]
Can you please configure this for the Internal Copr instance?
