### ISSUE TITLE
Blog post about SSH to builders

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#3127]

**Comment by FrostyX** [comment]
Draft: https://github.com/FrostyX/frostyx.github.io/blob/master/_drafts/copr-user-ssh.md
On Monday, we are planning a mini Copr release with some fixes for the feature and then I am publishing the blog post.

**Comment by praiskup** [comment]
> we are planning a mini Copr release with some fixes for the feature

Deployed (no outage needed this time).
