### ISSUE TITLE
Hide temporary projects from the search results

### ISSUE THREAD

**Issue by msrb** [fedora-copr/copr#3136]
Hide temporary projects from search results, or show them after regular projects.

I was wondering if there is a copr repository with the latest-greatest `fedora-license-data` package, so I tried searching for the name in Fedora Copr.
The results were 23 pages of Packit temporary projects. `fedora-license-data` utilizes Packit for MR builds (good!), so this is expected. However, I think it would make sense to simply hide temporary projects from Copr search by default. Right now I have no idea if there is actually a real non-temporary `fedora-license-data` Copr project, without going through 23 pages of results.

**Comment by FrostyX** [comment]
Hello @msrb,
thank you for the RFE.

I think it makes good sense and we also have a similar RFE for listing user projects (not searching) the same way - temporary projects at the end.
