### ISSUE TITLE
Custom method is broken because of DNF vs DNF5

### ISSUE THREAD

**Issue by FrostyX** [fedora-copr/copr#3140]
We discovered this with @praiskup while upgrading builders to F39 (but it is unrelated)

Custom method builds fail with:

```
INFO: Package manager dnf5 detected and used (direct choice)
Start: installing minimal buildroot with dnf5
execv(/usr/bin/dnf5) failed: No such file or directory
WARNING: DNF5 command failed, retrying, attempt #2, sleeping 10s
execv(/usr/bin/dnf5) failed: No such file or directory
WARNING: DNF5 command failed, retrying, attempt #3, sleeping 10s
execv(/usr/bin/dnf5) failed: No such file or directory
```

Relevant:

```
INFO: Not updating bootstrap chroot, bootstrap_image_ready=True
```

which is set in `rpmbuild/mock-custom-build.cfg.j2`.

Full error:

[builder-live.log.gz.txt](https://github.com/fedora-copr/copr/files/14238750/builder-live.log.gz.txt)

This is probably because Mock says that rawhide is a DNF5 distribution but the container doesn't have DNF5. The proposed solution is to temporarily replace the `mock-custom-build.cfg.j2` in ansible and set `bootstrap_image_ready=False` (for rawhide)

**Comment by praiskup** [comment]
The logic behind `bootstrap_image_ready` was that the image should always contain the default `package_manager` (and the plugins-core is not needed for the custom chroot preparation).

It's not truth with https://fedoraproject.org/wiki/Changes/BuildWithDNF5 -> Rawhide images contain DNF4, while the expected `package_manager` in bootstrap is `dnf5`.

**Comment by FrostyX** [comment]
I did https://pagure.io/fedora-infra/ansible/c/cce5ad78f461edbcd552f758ee808f1ce5348cb4 and an analogical change for the internal Copr.

**Comment by praiskup** [comment]
I think we still need to handle `fedora-40` which has been branched now? 

With `fedora-rawhide`, this is going to become non-problem because it will be DNF5-native distro (dnf5 will be available in the fedora:rawhide container image).  But the problem of DNF4-native F40 built by DNF5 will remain forever.

**Comment by praiskup** [comment]
I think this deserves an upstream `copr-rpmbuild` fix, wdyt?

**Comment by FrostyX** [comment]
> Well, I don't know. F40 uses fedora-branched.tpl template and it configures config_opts['package_manager'] = 'dnf'

Related issue: https://bugzilla.redhat.com/show_bug.cgi?id=2264535

**Comment by praiskup** [comment]
> Well, I don't know. F40 uses fedora-branched.tpl template and it configures config_opts['package_manager'] = 'dnf', so it shouldn't be an issue (at the moment)?

> Related issue: https://bugzilla.redhat.com/show_bug.cgi?id=2264535

Hehe - the fact that it flips back to `dnf` instead of `dnf5` *is an issue*!

**Comment by FrostyX** [comment]
Hotfixed on both Fedora Copr and Internal Copr for Rawhide and F40 chroots and we have I PR #3144 with a proper fix for F40.
