### ISSUE TITLE
Do not create discussion if "Project will not be listed on home page" in the project creation page

### ISSUE THREAD

**Issue by istiak101** [fedora-copr/copr#3148]
Currently any project created on COPR also creates a discussion on https://discussion.fedoraproject.org.

Do not create discussion if "Project will not be listed on home page" is selected.

Thanks

**Comment by FrostyX** [comment]
Thank you for the feedback @istiak101,
I think that's a good idea. One potential problem is that the setting can be changed anytime in the future, so we need to make sure the discussion thread is created then.

Additionally, we should not create discussion threads for temporary Copr projects.

**Comment by praiskup** [comment]
Triage: @xsuchy's idea -> Could we have a button for "starting discussion" (no matter if temporary project or not)?

**Comment by FrostyX** [comment]
I don't think this is fixed though.
