### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by istiak101** [fedora-copr/copr#3150]
Is COPR team willing to ship dark mode? I can send a dark mode patch.

**Comment by istiak101** [comment]
I also would like to send a bootstrap version bump patch for bit more modern look.

**Comment by praiskup** [comment]
> Is COPR team willing to ship dark mode? I can send a dark mode patch.

Patches are welcome! :) Just note there should be some button to let users choose, keeping the default as-is.

> I also would like to send a bootstrap version bump patch for bit more modern look.

Definitely a good idea.  Just note that we are using bootstrap from the Fedora package, so perhaps we need to update the Fedora package, too?

**Comment by FrostyX** [comment]
Hello @istiak101,
thank you for the RFE.

> Is COPR team willing to ship dark mode?

In my opinion, absolutely, we are willing to ship dark mode.
However on our list of priorities it is ... not at the top, so without a patch, it may or may not be done sometime in the future.

>  I can send a dark mode patch.

That would be very much appreciated and sped up the process a lot.

> I also would like to send a bootstrap version bump patch for bit more modern look.

+1 from me. We are using a very old bootstrap version, the code is bundled in our repository, ... it's a mess.

**Comment by istiak101** [comment]
> Patches are welcome! :) Just note there should be some button to let users choose, keeping the default as-is.

Isn't following system theme a good idea? Okay I will keep a button just in case for override.

> Definitely a good idea. Just note that we are using bootstrap from the Fedora package, so perhaps we need to update the Fedora package, too?

https://github.com/fedora-copr/copr/blob/main/frontend/coprs_frontend/coprs/static/css/bootstrap-theme.css
Pagure uses the Fedora one but this one looks static? Source view from COPR also indicates this.

> That would be very much appreciated and sped up the process a lot.

Sure, working on a patch.
