### ISSUE TITLE
Copr Release

### ISSUE THREAD

**Issue by FrostyX** [fedora-copr/copr#3151]
- [x] #3162
- [x] #3041 
- [ ] ~~#3130~~  skipped for this release
- [ ] #3170

**Comment by FrostyX** [comment]
ETA next Wednesday

**Comment by xsuchy** [comment]
This week - announce and schedule outage, run beaker test. Deployment next week.

**Comment by praiskup** [comment]
Packages are tagged, built, deployed on stage and tested (both Copr instances).

**Comment by FrostyX** [comment]
The release will be on Thursday 2024-03-07

**Comment by praiskup** [comment]
https://pagure.io/fedora-infrastructure/issue/11808

**Comment by andykimpe** [comment]
in other words this intervention will begin in a few minutes

remember to deactivate the warning message at the end of this maintenance

hoping that the French multi-departmental incident of the internet operator Bouygues Télécom this morning 2024-03-07 06:53 UTC or 07:53 CET

do not delay this update

although if a was resolved by the operator a 2024-03-07 09:53 UTC or 10:53 CET

this message was written on 2024-03-07 11:26 UTC

and for my part I have not launched any build
