### ISSUE TITLE
Copr-release + Use single-digit package versioning

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#3164]
What do you think about having just single-digit versions?

Currently, we have two-digit versions (some are 3-digits by mistake), `major.minor` but we never actually bumped `major` which leads to a ridiculous version like:

```
copr-backend    1.173
copr-frontend   1.202
copr-common     0.21.1
...
```
My bet that the `0 -> 1` bump in backend/frontend/etc.` was only done to not go [0ver](https://0ver.org/).

What I propose is to use `1 -> 2 -> ... -> inf`.

**Comment by FrostyX** [comment]
I am bumping up the priority for this issue. Not because of the single-digit versioning but because we need to do a new release soon. I already hotfixed a few issues in production.

**Comment by FrostyX** [comment]
The release fixes https://bugzilla.redhat.com/show_bug.cgi?id=2291505 and maybe other Bugzilla. We shouldn't forget to mention them in the Bodhi update.

**Comment by nikromen** [comment]
openmandriva fails but this is known issue -> https://github.com/rpm-software-management/mock/issues/1066

**Comment by praiskup** [comment]
We re-discussed this today, and the idea was to do major bump everywhere right now, to avoid 0ver, and to shorten the versions from 3 digits to two.
