### ISSUE TITLE
Make "rebuild with ssh access" use "mock --no-clean-after"

### ISSUE THREAD

**Issue by mjg** [fedora-copr/copr#3181]
Recently, copr and ui learned how to re-run a build with ssh access. This gives a chance to inspect more than the build products, especially when there are none. But so far, inspecting the build dir requires another manual mock run.

I suggest to run mock with "--no-cleanup-after" when run from "rebuild with ssh access". This saves resources because there is no need for another mock run, and the chroot is life-time limited anyways so that the secondary artefacts "lie there" for at most half an hour by default.

**Comment by praiskup** [comment]
Released and in production! Enjoy.
