### ISSUE TITLE
Log-detective button for source-rpm builds

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#3183]
Example build: https://copr.fedorainfracloud.org/coprs/g/copr/PyPI/build/7141457/

When the source build fails, the button still offers links to the RPM build roots that did not even start (so there are no logs).

**Comment by FrostyX** [comment]
There is:

```jinja
{% for chroot in chroots %}
<li><a href="{{ url |format(build.id, chroot.name) }}">Report {{ chroot.name }}</a></li>
{% else %}
<li><a href="{{ url |format(build.id, 'srpm-builds') }}">Report SRPM build</a></li>
{% endfor %}
```

So this won't probably happen for all SRPM but _only_ for builds that specified their chroots in advance and failed on SRPM.
