### ISSUE TITLE
download.copr.fedorainfracloud.org cache invalidation issue

### ISSUE THREAD

**Issue by teohhanhui** [fedora-copr/copr#3190]
/cc @xsuchy - referring to https://fedora-copr.github.io/posts/copr-cdn

For this COPR build: https://copr.fedorainfracloud.org/coprs/teohhanhui/wine/build/7181806/

https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/ has all the files as expected:
<details><summary>Details</summary>
<p>

> [chroot_scan](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/chroot_scan)/	2024-Mar-19 07:30:24	-- 	Directory
> [fedora-review](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/fedora-review)/	2024-Mar-19 10:04:43	-- 	Directory
> [backend.log.gz](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/backend.log.gz)	2024-Mar-19 10:04:43	3.97K 	GZ Compressed Archive
> [build-07181806.rsync.log](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/build-07181806.rsync.log)	2024-Mar-19 10:04:11	2.92K 	LOG File
> [build.info](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/build.info)	2024-Mar-19 07:28:42	59.00B 	INFO File
> [build.log.gz](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/build.log.gz)	2024-Mar-19 07:30:24	961.00B 	GZ Compressed Archive
> [builder-live.log.gz](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/builder-live.log.gz)	2024-Mar-19 10:04:07	372.60K 	GZ Compressed Archive
> [configs.tar.gz](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/configs.tar.gz)	2024-Mar-19 10:04:07	36.59K 	GZ Compressed Archive
> [hw_info.log.gz](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/hw_info.log.gz)	2024-Mar-19 07:30:27	1.35K 	GZ Compressed Archive
> [results.json](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/results.json)	2024-Mar-19 10:04:07	7.08K 	JSON File
> [root.log.gz](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/root.log.gz)	2024-Mar-19 07:30:24	17.33K 	GZ Compressed Archive
> [state.log.gz](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/state.log.gz)	2024-Mar-19 07:30:24	341.00B 	GZ Compressed Archive
> [success](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/success)	2024-Mar-19 08:26:38	4.00B 	Text File
> [wine-9.1-2.new_wow64.fc39.src.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-9.1-2.new_wow64.fc39.src.rpm)	2024-Mar-19 10:04:37	37.87M 	RPM File
> [wine-9.1-2.new_wow64.fc39.x86_64.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-9.1-2.new_wow64.fc39.x86_64.rpm)	2024-Mar-19 10:04:26	10.67K 	RPM File
> [wine-alsa-9.1-2.new_wow64.fc39.x86_64.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-alsa-9.1-2.new_wow64.fc39.x86_64.rpm)	2024-Mar-19 10:04:19	116.09K 	RPM File
> [wine-alsa-debuginfo-9.1-2.new_wow64.fc39.x86_64.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-alsa-debuginfo-9.1-2.new_wow64.fc39.x86_64.rpm)	2024-Mar-19 10:04:22	110.47K 	RPM File
> [wine-arial-fonts-9.1-2.new_wow64.fc39.noarch.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-arial-fonts-9.1-2.new_wow64.fc39.noarch.rpm)	2024-Mar-19 10:04:12	99.07K 	RPM File
> [wine-cms-9.1-2.new_wow64.fc39.x86_64.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-cms-9.1-2.new_wow64.fc39.x86_64.rpm)	2024-Mar-19 10:04:16	975.00K 	RPM File
> [wine-common-9.1-2.new_wow64.fc39.noarch.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-common-9.1-2.new_wow64.fc39.noarch.rpm)	2024-Mar-19 10:04:20	62.32K 	RPM File
> [wine-core-9.1-2.new_wow64.fc39.x86_64.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-core-9.1-2.new_wow64.fc39.x86_64.rpm)	2024-Mar-19 10:04:33	190.29M 	RPM File
> [wine-core-debuginfo-9.1-2.new_wow64.fc39.x86_64.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-core-debuginfo-9.1-2.new_wow64.fc39.x86_64.rpm)	2024-Mar-19 10:04:38	6.61M 	RPM File
> [wine-courier-fonts-9.1-2.new_wow64.fc39.noarch.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-courier-fonts-9.1-2.new_wow64.fc39.noarch.rpm)	2024-Mar-19 10:04:35	88.38K 	RPM File
> [wine-debuginfo-9.1-2.new_wow64.fc39.x86_64.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-debuginfo-9.1-2.new_wow64.fc39.x86_64.rpm)	2024-Mar-19 10:04:40	206.63K 	RPM File
> [wine-debugsource-9.1-2.new_wow64.fc39.x86_64.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-debugsource-9.1-2.new_wow64.fc39.x86_64.rpm)	2024-Mar-19 10:04:24	3.06M 	RPM File
> [wine-desktop-9.1-2.new_wow64.fc39.noarch.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-desktop-9.1-2.new_wow64.fc39.noarch.rpm)	2024-Mar-19 10:04:21	108.16K 	RPM File
> [wine-devel-9.1-2.new_wow64.fc39.x86_64.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-devel-9.1-2.new_wow64.fc39.x86_64.rpm)	2024-Mar-19 10:04:28	6.99M 	RPM File
> [wine-devel-debuginfo-9.1-2.new_wow64.fc39.x86_64.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-devel-debuginfo-9.1-2.new_wow64.fc39.x86_64.rpm)	2024-Mar-19 10:04:39	1.25M 	RPM File
> [wine-filesystem-9.1-2.new_wow64.fc39.noarch.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-filesystem-9.1-2.new_wow64.fc39.noarch.rpm)	2024-Mar-19 10:04:19	1.66M 	RPM File
> [wine-fixedsys-fonts-9.1-2.new_wow64.fc39.noarch.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-fixedsys-fonts-9.1-2.new_wow64.fc39.noarch.rpm)	2024-Mar-19 10:04:16	22.84K 	RPM File
> [wine-fonts-9.1-2.new_wow64.fc39.noarch.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-fonts-9.1-2.new_wow64.fc39.noarch.rpm)	2024-Mar-19 10:04:26	10.22K 	RPM File
> [wine-ldap-9.1-2.new_wow64.fc39.x86_64.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-ldap-9.1-2.new_wow64.fc39.x86_64.rpm)	2024-Mar-19 10:04:34	1.35M 	RPM File
> [wine-marlett-fonts-9.1-2.new_wow64.fc39.noarch.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-marlett-fonts-9.1-2.new_wow64.fc39.noarch.rpm)	2024-Mar-19 10:04:22	21.96K 	RPM File
> [wine-ms-sans-serif-fonts-9.1-2.new_wow64.fc39.noarch.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-ms-sans-serif-fonts-9.1-2.new_wow64.fc39.noarch.rpm)	2024-Mar-19 10:04:40	1.59M 	RPM File
> [wine-opencl-9.1-2.new_wow64.fc39.x86_64.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-opencl-9.1-2.new_wow64.fc39.x86_64.rpm)	2024-Mar-19 10:04:23	118.45K 	RPM File
> [wine-opencl-debuginfo-9.1-2.new_wow64.fc39.x86_64.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-opencl-debuginfo-9.1-2.new_wow64.fc39.x86_64.rpm)	2024-Mar-19 10:04:29	28.44K 	RPM File
> [wine-pulseaudio-9.1-2.new_wow64.fc39.x86_64.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-pulseaudio-9.1-2.new_wow64.fc39.x86_64.rpm)	2024-Mar-19 10:04:17	82.67K 	RPM File
> [wine-pulseaudio-debuginfo-9.1-2.new_wow64.fc39.x86_64.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-pulseaudio-debuginfo-9.1-2.new_wow64.fc39.x86_64.rpm)	2024-Mar-19 10:04:27	78.08K 	RPM File
> [wine-small-fonts-9.1-2.new_wow64.fc39.noarch.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-small-fonts-9.1-2.new_wow64.fc39.noarch.rpm)	2024-Mar-19 10:04:14	24.92K 	RPM File
> [wine-symbol-fonts-9.1-2.new_wow64.fc39.noarch.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-symbol-fonts-9.1-2.new_wow64.fc39.noarch.rpm)	2024-Mar-19 10:04:24	35.87K 	RPM File
> [wine-system-fonts-9.1-2.new_wow64.fc39.noarch.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-system-fonts-9.1-2.new_wow64.fc39.noarch.rpm)	2024-Mar-19 10:04:13	28.60K 	RPM File
> [wine-systemd-9.1-2.new_wow64.fc39.noarch.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-systemd-9.1-2.new_wow64.fc39.noarch.rpm)	2024-Mar-19 10:04:25	10.78K 	RPM File
> [wine-tahoma-fonts-9.1-2.new_wow64.fc39.noarch.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-tahoma-fonts-9.1-2.new_wow64.fc39.noarch.rpm)	2024-Mar-19 10:04:38	117.72K 	RPM File
> [wine-tahoma-fonts-system-9.1-2.new_wow64.fc39.noarch.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-tahoma-fonts-system-9.1-2.new_wow64.fc39.noarch.rpm)	2024-Mar-19 10:04:20	11.65K 	RPM File
> [wine-times-new-roman-fonts-9.1-2.new_wow64.fc39.noarch.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-times-new-roman-fonts-9.1-2.new_wow64.fc39.noarch.rpm)	2024-Mar-19 10:04:36	105.95K 	RPM File
> [wine-times-new-roman-fonts-system-9.1-2.new_wow64.fc39.noarch.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-times-new-roman-fonts-system-9.1-2.new_wow64.fc39.noarch.rpm)	2024-Mar-19 10:04:29	10.42K 	RPM File
> [wine-twain-9.1-2.new_wow64.fc39.x86_64.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-twain-9.1-2.new_wow64.fc39.x86_64.rpm)	2024-Mar-19 10:04:12	240.21K 	RPM File
> [wine-twain-debuginfo-9.1-2.new_wow64.fc39.x86_64.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-twain-debuginfo-9.1-2.new_wow64.fc39.x86_64.rpm)	2024-Mar-19 10:04:15	23.71K 	RPM File
> [wine-webdings-fonts-9.1-2.new_wow64.fc39.noarch.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-webdings-fonts-9.1-2.new_wow64.fc39.noarch.rpm)	2024-Mar-19 10:04:27	20.95K 	RPM File
> [wine-wingdings-fonts-9.1-2.new_wow64.fc39.noarch.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-wingdings-fonts-9.1-2.new_wow64.fc39.noarch.rpm)	2024-Mar-19 10:04:18	23.15K 	RPM File
> [wine-wingdings-fonts-system-9.1-2.new_wow64.fc39.noarch.rpm](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine-wingdings-fonts-system-9.1-2.new_wow64.fc39.noarch.rpm)	2024-Mar-19 10:04:14	10.38K 	RPM File
> [wine.spec](https://copr-be.cloud.fedoraproject.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/wine.spec)	2024-Mar-19 07:28:45	113.83K 	SPEC File

</p>
</details> 

https://download.copr.fedorainfracloud.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/ only shows 3 files:

> [backend.log](https://download.copr.fedorainfracloud.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/backend.log)	2024-Mar-19 09:48:50	4.81K 	LOG File
> [build.info](https://download.copr.fedorainfracloud.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/build.info)	2024-Mar-19 07:28:42	59.00B 	INFO File
> [builder-live.log](https://download.copr.fedorainfracloud.org/results/teohhanhui/wine/fedora-39-x86_64/07181806-wine/builder-live.log)	2024-Mar-19 08:26:38	7.48M 	LOG File

Please see the HAR files here: https://gist.github.com/teohhanhui/4ef2741223c0937d8fb1cd340732e072

**Comment by FrostyX** [comment]
Thank you for the report @teohhanhui 

This is a common issue that people encounter. So much so that we needed to explain it in FAQ
https://docs.pagure.org/copr.copr/user_documentation.html#build-succeeded-but-i-don-t-see-the-built-results

I agree it is confusing but don't worry, it doesn't affect users that enabled your project on their system and installing  packages from it.

**Comment by teohhanhui** [comment]
Actually it does affect `dnf`... I tried `sudo dnf5 clean all` and `sudo dnf5 install wine` but it was still seeing the old build. Only with the downloaded `wine-9.1-2.new_wow64.fc39.x86_64.rpm` did it work correctly.

**Comment by teohhanhui** [comment]
Looks like it's probably some `dnf` peculiarities that I wasn't familiar with. Sorry for the noise...
