### ISSUE TITLE
could you please add c10e

### ISSUE THREAD

**Issue by vbenes** [fedora-copr/copr#3193]
We need to build for c10s, could you please add the target? 

Thank you so much,
Vladimir

**Comment by FrostyX** [comment]
Hello @vbenes,
I think we can but `centos-stream-10-*` chroots aren't in the `mock-core-configs` yet, so it will take some time.
https://github.com/rpm-software-management/mock/tree/main/mock-core-configs/etc/mock

**Comment by praiskup** [comment]
FTR: https://github.com/rpm-software-management/mock/pull/1348

**Comment by FrostyX** [comment]
Working on a Mock release: https://github.com/rpm-software-management/mock/pull/1356

**Comment by FrostyX** [comment]
Done, these are now available: 

- centos-stream-10-x86_64 
- centos-stream-10-ppc64le 
- centos-stream-10-aarch64 
- centos-stream-10-s390x
