### ISSUE TITLE
How to automatically obtain build task status changes?

### ISSUE THREAD

**Issue by shishupei** [fedora-copr/copr#3200]
I want to be able to automatically go to the next business process when the build task state changes. such as requesting a specific api or sending a message.

**Comment by FrostyX** [comment]
You can do this by listening Fedora Messaging messages - https://fedora-messaging.readthedocs.io/en/stable/user-guide/schemas.html#copr

**Comment by praiskup** [comment]
Alternatively, you can use polling, that's what `copr-cli build` actually does.
