### ISSUE TITLE
Enable powerful workers for jordalgo/fedora-6.8-sched_ext

### ISSUE THREAD

**Issue by jordalgo** [fedora-copr/copr#3203]
Similar to https://github.com/fedora-copr/copr/issues/2985 - I was also hoping to have access to powerful workers for my kernel development work for Fedora and [sched_ext](https://github.com/sched-ext/scx). I need workers for aarch64, x86_64, ppc64le, and s390x.

https://copr.fedorainfracloud.org/coprs/jordalgo/fedora-6.8-sched_ext/

Thanks in advance!

cc @Conan-Kudo @davide125 @michel-slm

**Comment by praiskup** [comment]
Done: https://pagure.io/fedora-infra/ansible/c/c1d6f853bf53e5093033edda3700f430ee4c3041
But note that we do not have powerful builders for ppc64le, yet. See: #3092
