### ISSUE TITLE
Handle http source download

### ISSUE THREAD

**Issue by musuruan** [fedora-copr/copr#3221]
Currently it is not possibile to build packages that have an http source using rpkg (see #3079). only https and ftps sources are allowed.

It would be useful to support http too.

Thanks,

Andrea

**Comment by nikromen** [comment]
We  unfortunately plan to drop the rpkg feature since it isn't maintainer anymore :/
Regarding the HTTP method, this is doable in the build tab via a custom method where you can write your own script using http.
