### ISSUE TITLE
Disks bottlenecks copr backend

### ISSUE THREAD

**Issue by nikromen** [fedora-copr/copr#3234]
Sometimes it seems like backend won't recognize that build already finished so it remains in `running` state, resulting in blocking resources and queue starts grow. This happened at least 3 times during last month.

systemctl restart copr-backend.target and systemctl restart resalloc helps backend to recover itself

**Comment by praiskup** [comment]
The problem was a huge load caused by disk (raid10, not the raid1 part) I/O.
This is a recurring problem (jirka claims it happened for the 3rd time now).  We should decrease some quota at least.

**Comment by FrostyX** [comment]
Month and half OK, reopen if this happens again.

**Comment by nikromen** [comment]
It happened again. I temporarily decreased the number of running tasks to lower the load on disks. And a week ago we faced the same issue from stats on AWS but we didn't catch it?

**Comment by xsuchy** [comment]
I switched all disks to st1.
