### ISSUE TITLE
c9s-build x86_64 repo is accessible from COPR, but aarch64 is not

### ISSUE THREAD

**Issue by michel-slm** [fedora-copr/copr#3235]
I have the following custom repo defined in @centoshyperscale/gnome :

`https://kojihub.stream.centos.org/kojifiles/repos/c9s-build/latest/$arch/`

(we're using COPR as a staging environment for rebuilding a newer GNOME for Hyperscale GNOME; when eventually built in CBS we have access to c9s-build so we won't have issues with unpublished -devel packages)

This works fine for x86_64, but consistently fails on aarch64; see https://copr.fedorainfracloud.org/coprs/g/centoshyperscale/gnome/build/7341923/

notice the super long build time, which ends up being due to this

```
Errors during downloading metadata for repository 'https_kojihub_stream_centos_org_kojifiles_repos_c9s_build_latest_arch':
  - Curl error (28): Timeout was reached for https://kojihub.stream.centos.org/kojifiles/repos/c9s-build/latest/aarch64/repodata/repomd.xml [Connection timed out after 30000 milliseconds]
Error: Failed to download metadata for repo 'https_kojihub_stream_centos_org_kojifiles_repos_c9s_build_latest_arch': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

I can hit this URL just fine on a browser https://kojihub.stream.centos.org/kojifiles/repos/c9s-build/latest/aarch64/repodata/ and I can also download files within.

**Comment by praiskup** [comment]
Is Koji filtering-out some clients (namely our builders)?

**Comment by praiskup** [comment]
I am surprised that `$arch` works.  Shouldn't you use `$basearch` instead?

Anyway, the link seems to have aarch64 expanded just fine ... and yet it failed.  I now grabbed an aarch64 worker (EC2) and centos-stream-9-aarch64 worked just fine.  Has this problem disappeared?

**Comment by praiskup** [comment]
Nah, this is not reproducible: https://copr.fedorainfracloud.org/coprs/praiskup/test-aarch-c9s/build/7349800/

I was able to reproduce the problem on
```
$ curl ifconfig.me
3.81.106.199
```

**Comment by praiskup** [comment]
Original reporter used `3.87.255.232`

**Comment by michel-slm** [comment]
This might be resolved - not sure if anyone did anything to fix the bad builders? But builds have been passing since yesterday

https://copr.fedorainfracloud.org/coprs/g/centoshyperscale/gnome/builds/

**Comment by xsuchy** [comment]
OK. Good. Closing.
Please reopen if this happen again.
