### ISSUE TITLE
Decode error bug when running make_srpm

### ISSUE THREAD

**Issue by huakim** [fedora-copr/copr#3241]
```
Traceback (most recent call last):
  File "/usr/bin/copr-rpmbuild", line 133, in main
    action(args, config)
  File "/usr/bin/copr-rpmbuild", line 218, in build_srpm
    produce_srpm(task, config)
  File "/usr/bin/copr-rpmbuild", line 166, in produce_srpm
    provider.produce_srpm()
  File "/usr/lib/python3.12/site-packages/copr_rpmbuild/providers/scm.py", line 143, in produce_srpm
    return run_cmd(cmd, cwd=self.repo_subpath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/copr_rpmbuild/helpers.py", line 69, in run_cmd
    stdout=stdout.decode('utf-8').strip()
```

It seems, that copr system does not decode some output bits, and raises an error when decode fails. I think, that `stdout.decode('utf-8').strip()` can be replaced by third party library.

**Comment by FrostyX** [comment]
Hello @huakim,
thank you for the report.

Can you please help us understand how to reproduce this issue?

**Comment by praiskup** [comment]
@huakim gently ping

**Comment by huakim** [comment]
> Hello @huakim, thank you for the report.
> 
> Can you please help us understand how to reproduce this issue?

yes

1. i created repo, with .copr/Makefile
2. added some code to the .copr/Makefile 
3. made commit to that repo, and initiated build process with make_srpm in the copr
4. i did not remembered, what i did put to the .copr/Makefile, but you can experiment with something like this:
`
outdir ?= $(shell rpm --eval '%{_srcrpmdir}')

srpm:
           curl -s https:///downloadrpmsomewhere.org -o $(outdir)/a.src.rpm ||:
           python -c 'print("\x80")'
`

**Comment by FrostyX** [comment]
Thank you for the reproducer @huakim.

I tried here https://copr.fedorainfracloud.org/coprs/frostyx/test-rpkg-makefile-unicode/build/7446914/ but the build finished successfully, and I cannot see any traceback.

My testing repository is here https://github.com/fedora-copr/copr-test-hello/tree/unicode

Did I do something incorrectly?

**Comment by praiskup** [comment]
@huakim gently ping again

**Comment by praiskup** [comment]
Are you running the copr-rpmbuild script in Fedora Copr, locally or in some other Copr instance?
