### ISSUE TITLE
on list of projects we should be able to order it by date

### ISSUE THREAD

**Issue by sergiomb2** [fedora-copr/copr#3245]
in https://copr.fedorainfracloud.org/groups/g/fedora-review/coprs/ the list is not ordered, which makes it difficult to see if there are new entries .
I think COPR with this feature will become easier to use.

**Comment by FrostyX** [comment]
@nikromen I think you are right. Looking at the code, user projects are sorted by `CoprsLogic.set_query_order` but group projects aren't. But I unintentionally fixed it in PR #3232

**Comment by praiskup** [comment]
Nice :-) so I'm closing.  We plan to have a new Copr release soon: #3238 

@sergiomb2 thank you for the report!
