### ISSUE TITLE
Clean up forked repositories for Foreman project

### ISSUE THREAD

**Issue by ekohl** [fedora-copr/copr#3248]
In the Foreman project we have [theforeman/client-nightly-staging](https://copr.fedorainfracloud.org/coprs/g/theforeman/client-nightly-staging/) which is a fork of [theforeman/foreman-client-nightly-staging](https://copr.fedorainfracloud.org/coprs/g/theforeman/foreman-client-nightly-staging/). The latter no longer exists, but we intend to keep the former. Can this be cleaned up without recreating the whole repository?

Then we also have [theforeman/pulpcore-nightly-staging](https://copr.fedorainfracloud.org/coprs/g/theforeman/pulpcore-nightly-staging/) as a fork of [theforeman/pulpcore-nigthly-staging](https://copr.fedorainfracloud.org/coprs/g/theforeman/pulpcore-nigthly-staging/) (note the typo in nightly). Can this also be cleaned up so we only have the one without a typo?

**Comment by nikromen** [comment]
![Image](https://github.com/fedora-copr/copr/assets/70757578/19fb8eb0-05be-42df-9af7-3da06b51ee91)

do you mean deleting the information from where is the project forked?

**Comment by ekohl** [comment]
Yes, that's indeed what I meant.

**Comment by nikromen** [comment]
Ok, we can change this in out database for you

**Comment by praiskup** [comment]
Fixed :)
