### ISSUE TITLE
Trying to rebuild older version/release fails

### ISSUE THREAD

**Issue by brianjmurrell** [fedora-copr/copr#3254]
Due to fedora-copr/copr#1365 one might need to go back and build an older _version-release_ of an RPM.  That seems to [fail](https://download.copr.fedorainfracloud.org/results/brianjmurrell/homeassistant/fedora-39-x86_64/07435822-python-orjson/builder-live.log.gz) however:

```
INFO: Calling: curl -H Pragma: -o orjson-3.9.15.tar.gz --location --connect-timeout 60 --retry 3 --retry-delay 10 --remote-time --show-error --fail --retry-all-errors https://copr-dist-git.fedorainfracloud.org/repo/pkgs/brianjmurrell/homeassistant/python-orjson/orjson-3.9.15.tar.gz/md5/8b2412f4edb76cd08c7db8a652fb9cd0/orjson-3.9.15.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   196    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
Warning: Problem (retrying all errors). Will retry in 10 seconds. 3 retries 
Warning: left.
  0   196    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
Warning: Problem (retrying all errors). Will retry in 10 seconds. 2 retries 
Warning: left.
  0   196    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
Warning: Problem (retrying all errors). Will retry in 10 seconds. 1 retries 
Warning: left.
  0   196    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
ERROR: Can't download file orjson-3.9.15.tar.gz
```

It seems to be trying to pull the SOURCE tarball from https://copr-dist-git.fedorainfracloud.org/repo/pkgs/... which I guess is some sort of optimization on the assumption that the SOURCE has been fetched previously but a newer _version-release_ presumably has caused that to be pruned.

Ultimately however, the canonical/upstream copy of that SOURCE still exists.  It ought to be used rather than outright failing the rebuild request.

**Comment by praiskup** [comment]
Yes, the Copr DistGit (namely the Fedora instance) is automatically cleaned up by a [cron job](https://github.com/fedora-copr/copr/blob/8de7a6906733ef63f5269922fcc51f388a55d444/dist-git/run/dist-git-clear-tarballs.py#L32) using script from the dist-git project - that only keeps sources that are referenced by [the latest commits in branches](https://github.com/release-engineering/dist-git/blob/8f0939a7700c1f8ae2c145e130ca5543e5762de7/scripts/dist-git/remove_unused_sources#L52).

**Comment by praiskup** [comment]
> Ultimately however, the canonical/upstream copy of that SOURCE still exists.

We could re-download the tarball, but we don't want to do this for all the copr chroots you have enabled (that would basically DDoS upstream server, prolong the overall build, etc.).

Therefore, we'd have to most likely re-submit the whole source build again... and this would be a very expensive tasks to implement.

Per the team-triage time, we won't have time to implement this, so closing.  Feel free to reopen, or help us with this if you are in a better position for this.

**Comment by brianjmurrell** [comment]
To be honest, I don't really understand what the Copr DistGit is entirely.  But ultimately it seems that this _Rebuild_ functionality is simply broken for some use cases, at least.  Moreover it's broken in a way that is entirely opaque to the end user leaving them with no idea why it's not working and what to do.

Should the _Rebuild_ button only be active if it would actually succeed and not fail as described here?

**Comment by praiskup** [comment]
> To be honest, I don't really understand what the Copr DistGit is entirely

We are used to naming it "a source proxy" or "cache" - between the upstream and the Copr cluster.  We need to use the sources many times (consider you build into dozens of chroots), but we only want to get the sources once from upstream (download the tarball, clone the git-archive repo, etc.).

Yet, in many cases, it allows users to re-trigger the build, and it keeps the history of the spec file. But for the Fedora Copr instance, where we do a huge amount of CI builds, we can't afford to keep all the source tarballs.

> Should the Rebuild button only be active if it would actually succeed and not fail as described here?

Maybe? The thing is that the garbage collector is run asynchronously by the DistGit machine, and the frontend (the UI) has not idea whether the source was (not) garbage collected already.
