### ISSUE TITLE
build after id should (optionaly) only happen on success

### ISSUE THREAD

**Issue by hroncok** [fedora-copr/copr#3297]
Hello.
During the night, I scheduled a build of Python 3.13.0b2 in our copr. It was late, I didn't want to wait for the build, so I scheduled a batch of thousands of builds to happen after the Python build.

https://copr.fedorainfracloud.org/batches/detail/132555/

The Python build failed. The batch started building anyway. I consider that unfortunate.

I don't see why would anyone want to build something "after" a failed build. When something is scheduled to run after something else, IMHO it should only happen of the first thing suceeds (or at least that setup should be possible).

Thanks for consodering this.

**Comment by praiskup** [comment]
Thank you for the report.  This seems to be #2485 duplicate?

**Comment by praiskup** [comment]
I think yes, closing.
