### ISSUE TITLE
No translations found

### ISSUE THREAD

**Issue by ndias** [fedora-copr/copr#3301]
I have a SPEC rpm that I successful create in a Rocky Linux 9 and Fedora 40, but when I put it on copr I have this error

+ /usr/lib/rpm/find-lang.sh /builddir/build/BUILDROOT/django-debug-toolbar-4.4.2-2.ndias.fc40.x86_64 django django-debug-toolbar.lang
No translations found for django.lang in /builddir/build/BUILDROOT/django-debug-toolbar-4.4.2-2.ndias.fc40.x86_64
error: Bad exit status from /var/tmp/rpm-tmp.zn5KzT (%install)

and the creation of the rpm fails.

The same comand if running in my local machine is always successful running against the sources of the package

**Comment by FrostyX** [comment]
Hello @ndias,
this most likely isn't a Copr issue but a packaging error. But without the full log and the specfile, it's hard for me to say what exactly is wrong. Probably a missing dependency on some package.

You can try to reproduce the issue locally in Mock
https://github.com/rpm-software-management/mock
https://frostyx.cz/posts/using-mock-is-easy

**Comment by praiskup** [comment]
I'm closing this as packaging error, but feel free to continue the discussion here.

**Comment by ndias** [comment]
> Hello @ndias, this most likely isn't a Copr issue but a packaging error. But without the full log and the specfile, it's hard for me to say what exactly is wrong. Probably a missing dependency on some package.
> 
> You can try to reproduce the issue locally in Mock https://github.com/rpm-software-management/mock https://frostyx.cz/posts/using-mock-is-easy

Sorry, you are right I forgot to past the links for the building

https://download.copr.fedorainfracloud.org/results/nunodias/debug-toolbar/fedora-40-x86_64/07554850-django-debug-toolbar/

SPEC
https://download.copr.fedorainfracloud.org/results/nunodias/debug-toolbar/fedora-40-x86_64/07554850-django-debug-toolbar/django-debug-toolbar.spec

LOGS
https://download.copr.fedorainfracloud.org/results/nunodias/debug-toolbar/fedora-40-x86_64/07554850-django-debug-toolbar/builder-live.log.gz
