### ISSUE TITLE
Document the CoprDirs feature

### ISSUE THREAD

**Issue by FrostyX** [fedora-copr/copr#3307]
I wanted to show the CoprDirs feature to several people and couldn't find documentation for it. It is possible we have it somewhere but probably not accessible enough.

**Comment by praiskup** [comment]
Some (incomplete) chunks:
https://docs.pagure.org/copr.copr/user_documentation.html#custom-webhook
https://github.com/fedora-copr/copr/blob/4edf3b26e69cde5ef78e5742cb11972a3a7e5b55/doc/user_documentation/pagure_integration.rst#L28-L30
