### ISSUE TITLE
sometimes we have duplicated builds

### ISSUE THREAD

**Issue by vbenes** [fedora-copr/copr#3308]
https://copr.fedorainfracloud.org/coprs/networkmanager/NetworkManager-main-debug/builds/

We sometimes see that doubling in builds, no idea why, but this is not happening 100% but ~75% only so I assume we hit some copr issue.

any idea what could be wrong? This might be quite resource-consuming when performing double compilation.

**Comment by praiskup** [comment]
Thank you for the report.  Are you sure the triggering webhook isn't called multiple times?

**Comment by praiskup** [comment]
Ping.

**Comment by praiskup** [comment]
Closing for now, feel free to reopen or update the ticket.
