### ISSUE TITLE
EPEL 7 builds started to fail due to centos7 EOL URLs

### ISSUE THREAD

**Issue by kokesak** [fedora-copr/copr#3320]
In several projects we are using the copr for building packages to RHEL7/Centos7 - this now started to fail as the centos-7 reached the EOL. 
Full log: 
https://download.copr.fedorainfracloud.org/results/@oamg/convert2rhel/epel-7-x86_64/07696053-convert2rhel/builder-live.log.gz
https://download.copr.fedorainfracloud.org/results/mlitwora-redhat/c2r-mock-utility/epel-7-x86_64/07695922-convert2rhel/builder-live.log.gz

Would it be possible to  fix the URLs to point to the vault (https://vault.centos.org/centos/7/) on the build systems instead of the mirrorlist? 

```
Copr repository                                 407 kB/s |  42 kB     00:00    
CentOS-7 - Base                                 0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'base':
  - Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os [Could not resolve host: mirrorlist.centos.org]
Error: Failed to download metadata for repo 'base': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os [Could not resolve host: mirrorlist.centos.org]
WARNING: DNF command failed, retrying, attempt #2, sleeping 10s
No matches found for the following disable plugin patterns: local, spacewalk, versionlock
Updating Subscription Management repositories.
Unable to read consumer identity
```

**Comment by danmyway** [comment]
IIUIC there is a container image pulled, which has the last update pushed ~ 5 years ago
https://hub.docker.com/r/centos/redis-32-centos7

**Comment by bocekm** [comment]
@praiskup, this seems to be the same issue as https://lists.fedorahosted.org/archives/list/epel-devel@lists.fedoraproject.org/thread/6J2SADUV5SF5I63COQR5HBQNO64IBS2X/.

**Comment by bocekm** [comment]
If a container image needs to be used then this one https://hub.docker.com/r/eurolinux/centos-7 can be used after https://github.com/EuroLinux/containers-rfc/issues/10 is fixed.

**Comment by praiskup** [comment]
Yup, CentOS project is EOL: https://github.com/rpm-software-management/mock/pull/1397

For Copr, it seems pretty easy to keep x86_64 working from vault, but not other architectures.

**Comment by praiskup** [comment]
Jakub promised he'd took a look at this one.  Seems that we could/should switch EPEL-7 chroots in Copr to RHEL+EPEL in Copr

**Comment by FrostyX** [comment]
> Seems that we could/should switch EPEL-7 chroots in Copr to RHEL+EPEL in Copr

Done on both Fedora Copr and Internal Copr. I can now successfully build in EPEL7 chroots, so closing the issue. If needed, please reopen.
