### ISSUE TITLE
Use at least Power9 builders for c10s ppc64le builds

### ISSUE THREAD

**Issue by thozza** [fedora-copr/copr#3321]
We have been seeing consistent failures in RPM builds for c10s ppc64le in COPR. E.g. https://download.copr.fedorainfracloud.org/results/@osbuild/osbuild/centos-stream-10-ppc64le/07697854-osbuild/builder-live.log.gz
The log contains multiple instances of signal 4 errors, which is SIGILL (illegal instruction).

[COPR uses Power8 for builders](https://download.copr.fedorainfracloud.org/results/@osbuild/osbuild/centos-stream-10-ppc64le/07697854-osbuild/hw_info.log.gz), which is too old even for c9s.

Please use at least Power9 builders for c10s.

**Comment by praiskup** [comment]
Thank you for the report!

```
coprdb=# update mock_chroot set tags_raw='arch_power9' where id = 206;
UPDATE 1
```
