### ISSUE TITLE
Add additional package(s) in New Builds section

### ISSUE THREAD

**Issue by katnatek** [fedora-copr/copr#3324]
We can add additional package(s) to chroots, but I wonder if it is possible to do this also in New Build section
This is for example to use different version or package if needed, a thing that is not possible in chroot section because the package(s) are always the same

**Comment by FrostyX** [comment]
Hello @katnatek, I am sorry, this currently isn't possible.
The issue will be fixed as a part of #2541 so I am going to close this ticket as a duplicate. Please subscribe #2541 for updates, and whoever is going to implement it, will make sure it covers this use-case as well.

**Comment by katnatek** [comment]
> Hello @katnatek, I am sorry, this currently isn't possible. The issue will be fixed as a part of #2541 so I am going to close this ticket as a duplicate. Please subscribe #2541 for updates, and whoever is going to implement it, will make sure it covers this use-case as well.

Thank you for the information, for the moment as ugly workaround I'll change the package what I require when needed.

I'll keep an eye in that bug.
