### ISSUE TITLE
500 Internal Server error

### ISSUE THREAD

**Issue by andersrh** [fedora-copr/copr#3326]
Today we experience internal server error, when trying to log in and sometimes access COPR in general.

Tried to clear cookies and website data for COPR, but it turns out that other members in our project are having the same issue.

![Screenshot_20240705_125619](https://github.com/fedora-copr/copr/assets/20405991/d2c0031c-84b4-48f9-bdd9-3487cc5223c5)

**Comment by pojunen** [comment]
Exactly same problem since today, it sometimes work but sometimes throw 500 internal server error, very unreliable, maybe DDoS or something going on?

**Comment by nirik** [comment]
I think this may have been due to python being updated (because it was a security update) but httpd still trying to use the old python and segfaulting.

I restarted httpd on copr-fe and it seems to be processing much better now.

**Comment by andersrh** [comment]
Everything seems to be working now :)
Thank you.

**Comment by praiskup** [comment]
@nirik thank you for the quick action!
