### ISSUE TITLE
Don't run DNF automatic security updates over weekends

### ISSUE THREAD

**Issue by FrostyX** [fedora-copr/copr#3327]
I thought we already had an issue for this but I cannot find it.

The security updates screwed us twice in a short amount of time:

- 2024-05-18 - Copr was down the whole Saturday because of a `git` update #3266
- 2024-07-06 - Copr was down the whole Friday (public holiday in Czech Republic) because of a python update - #3326

IMHO we should configure DNF automatic to run updates only on Monday to Thursday and only during work hours.

**Comment by xsuchy** [comment]
https://pagure.io/fedora-infra/ansible/pull-request/2228

**Comment by xsuchy** [comment]
Per feedback on infra ML I set it up for all infra machines.
