### ISSUE TITLE
Enable high-perf builders for @secureblue/hardened-chromium

### ISSUE THREAD

**Issue by qoijjj** [fedora-copr/copr#3331]
[secureblue](https://github.com/secureblue/secureblue) is building a hardened chromium package in copr inspired by [Vanadium](https://github.com/GrapheneOS/Vanadium). As is expected per the [copr documentation](https://docs.pagure.org/copr.copr/user_documentation/powerful_builders.html#high-performance-builders), it takes around 24 hours to build on normal builders (old test runs are [here](https://copr.fedorainfracloud.org/coprs/qoijjj/chromium-test/builds/)). Therefore I'm requesting high-performance builders as recommended by the docs, for [this copr](https://copr.fedorainfracloud.org/coprs/secureblue/hardened-chromium/)

**Comment by qoijjj** [comment]
also FYI, this uses Fedora's chromium [as a base](https://github.com/secureblue/hardened-chromium/blob/master/.gitmodules) so as to ensure it has all the proprietary bits fedora can't ship removed, per the [content requirements](https://docs.pagure.org/copr.copr/user_documentation.html#what-i-can-build-in-copr).

It also [disables the use of fedora's api key](https://github.com/secureblue/hardened-chromium/blob/master/hardening.patch#L23) in the spec, so as to not use it without permission.

**Comment by qoijjj** [comment]
@praiskup Hey Pavel, just wanted to check on this. If it's nearly done, I'll hold off on starting a new build.

**Comment by praiskup** [comment]
Thank you for the report.  Configuration done here (x86_64 & aarch64): https://pagure.io/fedora-infra/ansible/c/b12bc06e9e3bde5f6ae43b3ce94b6511e0e24753
Enjoy faster builds!

**Comment by qoijjj** [comment]
@praiskup Thanks a bunch! Do I need to change anything to make this take effect (and should I cancel my ongoing build)? Or is it automatic?

**Comment by praiskup** [comment]
No change needed; the very next build should allocate high-perf builder(s)

**Comment by praiskup** [comment]
Uhhh, sorry, I made a typo in the configuration, [fixed here now](https://pagure.io/fedora-infra/ansible/c/7af16136db73c908491f2c6927d4a7fb032e5c59). Please resubmit the latest build.

**Comment by RoyalOughtness** [comment]
@praiskup We're in the process of rebranding our browser including a new [copr project name](https://copr.fedorainfracloud.org/coprs/secureblue/trivalent/). Would you mind switching this in the ansible config when you have time?

Much appreciated

**Comment by praiskup** [comment]
Sure, should be done!  Happy building.
https://pagure.io/fedora-infra/ansible/c/497674fa44680d4a0b09706015b07eb11638a1c1

**Comment by RoyalOughtness** [comment]
@praiskup Sorry, I wasn't clear enough :sweat_smile: both our copr project *and* our package name are now `trivalent`

So I think it should be `"secureblue/trivalent/.*(x86_64|aarch64)/trivalent",` if I understand the syntax right

**Comment by praiskup** [comment]
Ahh, sorry, here is the fix: https://pagure.io/fedora-infra/ansible/c/fda55f0dd955c829f35f0ebfa439f11e16762f12
