### ISSUE TITLE
URL redirect for centos stream does not work correctly

### ISSUE THREAD

**Issue by thrix** [fedora-copr/copr#3334]
It would be great if this:

```
❯ curl https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/repo/centos-stream-$releasever/rhcontainerbot-podman-next-centos-stream-$releasever.repo
[copr:copr.fedorainfracloud.org:rhcontainerbot:podman-next]
name=Copr repo for podman-next owned by rhcontainerbot
baseurl=https://download.copr.fedorainfracloud.org/results/rhcontainerbot/podman-next/centos-stream-10-$basearch/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://download.copr.fedorainfracloud.org/results/rhcontainerbot/podman-next/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1
```

Would return a generic copr repo with $releasever (as for Fedora):

```
❯ curl https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/repo/centos-stream-$releasever/rhcontainerbot-podman-next-centos-stream-$releasever.repo
[copr:copr.fedorainfracloud.org:rhcontainerbot:podman-next]
name=Copr repo for podman-next owned by rhcontainerbot
baseurl=https://download.copr.fedorainfracloud.org/results/rhcontainerbot/podman-next/centos-stream-$releasever-$basearch/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://download.copr.fedorainfracloud.org/results/rhcontainerbot/podman-next/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1
```

**Comment by lsm5** [comment]
@praiskup any ETA for this?

**Comment by praiskup** [comment]
https://redhat-internal.slack.com/archives/C03BRN71JAF/p1721395805625869

**Comment by xsuchy** [comment]
@thrix, Can you please summarize the motivation and use case for why you need/want this? It will help us prioritize this issue.

**Comment by nikromen** [comment]
Patches are welcome for this!

**Comment by praiskup** [comment]
Ad ETA, we release like every [few months](https://docs.pagure.org/copr.copr/release_notes.html), and this should be an easy fix somewhere [here](https://github.com/fedora-copr/copr/blob/main/frontend/coprs_frontend/coprs/helpers.py#L346-L347). If you want to be 100% we have this in a new release, patch would be helpful.

**Comment by lsm5** [comment]
> Can you please summarize the motivation and use case for why you need/want this? It will help us prioritize this issue.

@xsuchy I need to use centos-stream copr repos from the [podman-next copr](https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/) on centos-stream envs and if I use [generic centos-stream repos](https://github.com/containers/container-selinux/pull/321/files#diff-2b4300f6d69654fd71c0cdd329b5a5f13fa8fe7eb709c76276bdfd3ea1dde578R103-R107) with $releasever in the URL, releasever resolves to 10. So, currently I can't mention a repo for c9s using `releasever`. 

Sure, there are ugly workarounds, but rather have centos-stream urls behave the same way as fedora.

Hopefully fix is as simple as the linked frontend PR :)

**Comment by nforro** [comment]
The thing is, `$releasever` in the URL expands to an empty string, but that's still a valid repo URL, but the `baseurl` in it points to the first chroot in the list, so in this case `centos-stream-10`.
