### ISSUE TITLE
Drop fedora-eln-i386 chroot

### ISSUE THREAD

**Issue by yselkowitz** [fedora-copr/copr#3339]
ELN has dropped ix86 builds: https://github.com/rpm-software-management/mock/pull/1413

**Comment by nikromen** [comment]
triage: eol this chroot

**Comment by FrostyX** [comment]
[root@copr-fe ~][PROD]# sudo -u copr-fe /usr/bin/copr-frontend alter-chroot --action eol fedora-eln-i386
