### ISSUE TITLE
Please enable high-performance builders for solopasha/qt6-test/qt6-qtwebengine

### ISSUE THREAD

**Issue by solopasha** [fedora-copr/copr#3353]
I sometimes want to test builds of the qt6-qtwebengine package that  take >8 hours on normal builders.

**Comment by xsuchy** [comment]
Done
https://pagure.io/fedora-infra/ansible/c/12f68c635247e474c64caf498c7a0470f760fec0?branch=main
And deployed in production.
Enjoy.
