### ISSUE TITLE
mageia-cauldron-i586 should be changed to mageia-cauldron-i686

### ISSUE THREAD

**Issue by katnatek** [fedora-copr/copr#3354]
For cualdron mageia switch to i686 for the 32bit build 
The chroot for mageia should be updated to be able to build mageia cualdron packages for 32bit in copr

[backend.log.gz](https://github.com/user-attachments/files/16474227/backend.log.gz)

**Comment by FrostyX** [comment]
Thank you for the report @katnatek,
you are right.

The relevant snippet from the backend log:

```
Re-try request for task on 'ResallocHost, ticket_id=4124525, hostname=2620:52:3:1:dead:beef:cafe:c150': Chroot config /etc/mock/mageia-cauldron-i586.cfg not found
```

The Mock config for Mageia Cauldron was renamed from i586 to i686 in https://github.com/rpm-software-management/mock/commit/96dd10f013bfae36a081555d3f101b690409bb89

**Comment by FrostyX** [comment]
I renamed the chroot on the frontend:

```sql
coprdb=# update mock_chroot set arch='i686' where os_release='mageia' and os_version='cauldron' and arch='i586';
UPDATE 1
```

and symlinked the existing results on backend:

```
[copr@copr-be root][PROD]$ /usr/bin/copr-rename-chroot --real-run --pair mageia-cauldron-i586:mageia-cauldron-i686
```

I can now successfully build the package mentioned in the issue description, so I think we can close this. Please reopen if you find any related issues :-)

**Comment by FrostyX** [comment]
FTR we have documentation for this https://docs.pagure.org/copr.copr/how_to_rename_chroot.html in case somebody needs something similar in the future.

**Comment by katnatek** [comment]
Thank you for solve this
