### ISSUE TITLE
Remove epel6 chroots

### ISSUE THREAD

**Issue by xsuchy** [fedora-copr/copr#3357]
We still have epel6 chroots in Fedora's Copr. 
I asked pstodulka (who was one of the last users) and they do not use it.
I am going to check with Alexandra F., but I think it may be removed.

**Comment by xsuchy** [comment]
Alexandra confirmed they are not using it too.

**Comment by FrostyX** [comment]
```
[root@copr-fe ~][PROD]# sudo -u copr-fe /usr/bin/copr-frontend alter-chroot --action eol epel-6-i386 epel-6-x86_64
```
