### ISSUE TITLE
branch f41

### ISSUE THREAD

**Issue by nikromen** [fedora-copr/copr#3370]

**Comment by nikromen** [comment]
https://docs.pagure.org/copr.copr/how_to_manage_chroots.html#branching-process

**Comment by FrostyX** [comment]
F41 is going to be branched tomorrow.

> Branch Fedora Linux 41 from Rawhide	Tue 2024-08-13

I don't think we have mock-core-configs ready, so I will probably deploy custom configs through ansible. And today, we need to run the branching script for Copr.

**Comment by FrostyX** [comment]
Running:

```
[root@copr-fe ~][PROD]# sudo -u copr-fe /usr/bin/copr-frontend branch-fedora 41
```

**Comment by FrostyX** [comment]
Already enabled in Copr
