### ISSUE TITLE
enable high-performance builders for @rocm-packagers-sig/rocm-devel

### ISSUE THREAD

**Issue by tflink** [fedora-copr/copr#3373]
Please enable high-performance builders with the following regexp:

```
@rocm-packagers-sig/rocm-devel/.*x86_64/.*
```

Several of the packages that we want to build in COPR have taken longer than the maxiumum timeout for the regular builders which is why we are requesting this change.

**Comment by praiskup** [comment]
Done here: https://pagure.io/fedora-infra/ansible/c/df5e217a694994fefae15caee5935ea78d644f6c

> Several of the packages that we want to build in COPR have taken longer than the maxiumum timeout

I am not sure how many packages will be built there, but the inexpensively-built packages will compete
with the expensively-build packages with the `.*` package pattern that you prefer - potentially slowing down the
overall throughput.  You typically want to assign high-perf builders only to a limited set of packages
so the "normal" packages are processed quickly (without waiting till the high-perf builder gets allocated).

Closing, but feel free to reopen it if you want to tweak the pattern.
