### ISSUE TITLE
Enable openeuler-24.03 chroot

### ISSUE THREAD

**Issue by nuqleo** [fedora-copr/copr#3386]
openEuler 24.03 LTS configs (based on 22.03) added in mock-core-configs v41.2
https://github.com/rpm-software-management/mock/commit/ff71b3d6e6141578515aad849bc4f87760d22677

Is it possible to enable openeuler-24.03 chroot it in fedora-copr?

**Comment by pkking** [comment]
@nuqleo thanks，also you can try openEuler copr instance: [EUR](https://eur.openeuler.openatom.cn/)

**Comment by nuqleo** [comment]
Created EUR some repos https://eur.openeuler.openatom.cn/coprs/nucleo/

**Comment by pkking** [comment]
> Created some EUR repos https://eur.openeuler.openatom.cn/coprs/nucleo/

please [contact me](pkwarcraft@hotmail.com) if you have any problem getting involved with openEuler or EUR ;)

**Comment by FrostyX** [comment]
Done:

```
sudo -u copr-fe /usr/bin/copr-frontend create-chroot openeuler-24.03-x86_64 openeuler-24.03-aarch64
```
