### ISSUE TITLE
Blog post - vcs-diff-lint && ruff

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#3388]

**Comment by praiskup** [comment]
in progress

**Comment by FrostyX** [comment]
Draft ready to be published: https://github.com/FrostyX/frostyx.github.io/blob/master/_drafts/ruff-only-on-changed-files.md
Please review at least the last section comparing `vcs-diff-lint` and `diff-cover`, I don't want to explain incorrectly and/or make either of the tools look bad.

**Comment by praiskup** [comment]
Nice post!  Much bigger than just "here's the new vcs-diff-lint version", good!

> prints only defects that changed

I'd say s/changed/newly appeared/ or something alike, csdiff's manpage says "take two lists of defects and output either added or fixed ones".

**Comment by praiskup** [comment]
otherwise lgtm

**Comment by FrostyX** [comment]
https://frostyx.cz/posts/ruff-my-dirty-code
