### ISSUE TITLE
Missing support for %autosetup -C option

### ISSUE THREAD

**Issue by edewata** [fedora-copr/copr#3392]
The latest RPM spec file for `jakarta-activation` package (and some other packages too) in Fedora uses `%autosetup -C` option:
https://src.fedoraproject.org/rpms/jakarta-activation/blob/rawhide/f/jakarta-activation.spec#_38:

```
%autosetup -p1 -C
```

However, building this package in COPR is failing since the option is currently not supported:
https://copr.fedorainfracloud.org/coprs/edewata/pki/build/7951256/
https://download.copr.fedorainfracloud.org/results/edewata/pki/srpm-builds/07951256/builder-live.log.gz:

```
autosetup: invalid option -- 'C'
error: /var/lib/copr-rpmbuild/results/jakarta-activation.spec: line 48: Unknown option C in autosetup(a:b:cDn:TvNS:p:)
```

Please add the support for `-C` option so that these packages can be built in COPR. Thanks!

**Comment by praiskup** [comment]
The `%autosetup` macro is defined in the `/usr/lib/rpm/macros` file, which is RPM:

    $ rpm -qf /usr/lib/rpm/macros
    rpm-4.19.1.1-1.fc40.x86_64

Copr is just building against official distribution repositories that we do
not own/maintain (we can't fix the packages).

I see `C` option only available in Fedora Rawhide; so you may try to request backporting
the option to older Fedora variants (not sure how likely that is).

**Comment by edewata** [comment]
OK, I was able to build using the RPM spec from the `f41` branch. I think this is sufficient for now. Thanks!
https://src.fedoraproject.org/rpms/jakarta-activation/blob/f41/f/jakarta-activation.spec
