### ISSUE TITLE
[BUG] chroot caching is so aggressive it results in different data for different geolocations

### ISSUE THREAD

**Issue by qoijjj** [fedora-copr/copr#3405]
The copr us-west data nodes have cached one of our chroots:

https://download.copr.fedorainfracloud.org/results/secureblue/hardened-chromium/fedora-40-x86_64/07988446-hardened-chromium/

such that users in western north america see this:
![image](https://github.com/user-attachments/assets/2198a9b3-393c-41b8-a032-e4417a60b2c2)

users anywhere else see this:

![image](https://github.com/user-attachments/assets/a0ca2abd-328c-4c50-ad67-b04df250e4b5)

So, this means that the data node in uswest has a broken cache or a very long cache expiry, to the point where it's unusable.

You can confirm this behavior by VPNing into a Vancouver BC vpn, and going to the URL above, and then VPNing anywhere that isn't USwest, and doing the same

**Comment by FrostyX** [comment]
Hello @qoijjj,
thank you for the report.

People confused by Copr CDN += 1 :smile: 

Please take a look here 
https://docs.pagure.org/copr.copr/user_documentation.html#build-succeeded-but-i-don-t-see-the-built-results

I don't know if there is something that we can do about this.

**Comment by praiskup** [comment]
OK, closing, this seems to match the FAQ, and should be resolved in #2625
