### ISSUE TITLE
No spec file found when generated via custom method

### ISSUE THREAD

**Issue by nikromen** [fedora-copr/copr#3417]
generating spec file via custom method doesn't work: https://copr.stg.fedoraproject.org/coprs/nikromen/custom-1-TEST1727083559203752055/build/2918883/

**Comment by FrostyX** [comment]
I needed to use a package from PR #3428 to test this because otherwise custom-method doesn't work for a different reason. However, I cannot reproduce this issue, all tests from `./runtest-custom-method.sh` pass.
