### ISSUE TITLE
The make_srpm method fails with git safe.directory error

### ISSUE THREAD

**Issue by FrostyX** [fedora-copr/copr#3421]
Full log: [builder-live.log.gz.txt](https://github.com/user-attachments/files/17113031/builder-live.log.gz.txt)

```
./contrib/fedora/make_srpm.sh --prerelease --output /mnt/safe-resultdir-c3dy38x1
remote: fatal: detected dubious ownership in repository at '/mnt/workdir-a7gx95j6/sssd/.git'        
remote: To add an exception for this directory, call:        
remote: 
remote: 	git config --global --add safe.directory /mnt/workdir-a7gx95j6/sssd/.git        
remote: git upload-archive: archiver died with error
fatal: sent error to the client: git upload-archive: archiver died with error
```

But strangely enough, after the fatal error, we still produce the SRPM?

```
Creating SRPM without extra patches.
setting SOURCE_DATE_EPOCH=1611187200
Wrote: /mnt/workdir-a7gx95j6/sssd/rpmbuild/SRPMS/sssd-2.10.0~beta2-0.240924.083430.git5f5077ac1.src.rpm
```

**Comment by pbrezina** [comment]
This is the script we use: https://github.com/SSSD/sssd/blob/master/contrib/fedora/make_srpm.sh

**Comment by FrostyX** [comment]
> But strangely enough, after the fatal error, we still produce the SRPM?

@pbrezina says "It produces some 20-bytes malformed tarball"

**Comment by pbrezina** [comment]
We run `git archive ... | gzip > "$RPMBUILD/SOURCES/$NAME.tar.gz"` so if git archive fail just feed gzip with the error message.

**Comment by FrostyX** [comment]
Or it possibly never worked with `make_srpm`? I am not sure.

**Comment by pbrezina** [comment]
Btw the last successful build was 16. 5. 2024. It is all red after this day.

**Comment by nikromen** [comment]
this is really still hapenning: https://download.copr.fedorainfracloud.org/results/nikromen/playground/srpm-builds/08113937/builder-live.log.gz

but once I take builder and try to debug it manually there, it'll pass every time 🤷  shouldn't this also produce the safe.directory fail?
What's the difference between taking a builder and running
`/usr/bin/copr-rpmbuild --verbose --drop-resultdir --srpm --task-url https://copr.fedorainfracloud.org/backend/get-srpm-build-task/8113937`
there and letting copr to do the same in a build automatically...

**Comment by nikromen** [comment]
the command to create safe directory in .gitconfig is correct in both cases, but when srpm build is handled by copr, it somehow either has no effect or something mystically "cancels" the already set safe directory

**Comment by opoplawski** [comment]
Any progress here?  I would really like to be able to test out a sssd fix.

**Comment by praiskup** [comment]
@pbrezina can you take a look at https://github.com/SSSD/sssd/pull/7639 ?  Git archive seems to behave fine if we don't use `--remote=file://`, which I'm not really sure why is needed (shouldn't be).
