### ISSUE TITLE
No webhook history for @copr/copr-pull-requests

### ISSUE THREAD

**Issue by FrostyX** [fedora-copr/copr#3455]
There are no webhooks displayed for our project 
https://copr.fedorainfracloud.org/coprs/g/copr/copr-pull-requests/integrations/
even though we webhook-rebuilt a few builds since the last Copr release.

```
Webhook History
No webhook received recently.
```

I am curious what we missed @jaitjacob. I'll let you know once I have some debugging information.

**Comment by jaitjacob** [comment]
I suspect Custom Webhooks do not add Webhook History record maybe that’s why? Only webhooks from forges call the `add_webhook_history` method. I checked `Source Type`  field on one of the builds and saw `Custom Build Method` which rang a bell. Let me send a patch for this shortly.
