### ISSUE TITLE
Quick link in copr build to create a bugzilla ticket

### ISSUE THREAD

**Issue by solomoncyj** [fedora-copr/copr#3474]
would save us a lot of clickes, edpecialy if there is alot of deps

**Comment by FrostyX** [comment]
Hello @solomoncyj,
thank you for the suggestion.

What kind of ticket do you mean? A package review request? Basically preparing this template
https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&format=fedora-review
with actual information from Copr?

**Comment by solomoncyj** [comment]
yes

**Comment by praiskup** [comment]
Is this a duplicate to #1314?

**Comment by solomoncyj** [comment]
But for the web ui

**Comment by nikromen** [comment]
let's merge this issue to #1314 and do it there
