### ISSUE TITLE
Duplicate WebhookHistory records if multiple builds are started?

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#3480]
Per:
https://github.com/fedora-copr/copr/blob/16857487818a121456a8d866b6fb41adbe8b25e3/frontend/coprs_frontend/coprs/models.py#L1601-L1605

And #3456, it seems that when one webhook triggers multiple builds, we get multiple WebhookHistory entries.

**Comment by nikromen** [comment]
probably fixed
