### ISSUE TITLE
Nagios warnings about copr-be disk space

### ISSUE THREAD

**Issue by FrostyX** [fedora-copr/copr#3492]
Currently acked:

```
Subject: ** ACKNOWLEDGEMENT alert - copr-be.aws.fedoraproject.org/Disk_Space_/ is WARNING **
```

**Comment by FrostyX** [comment]
And now I got a recovery alert. Did somebody fix this or are we balancing on the edge?

**Comment by nikromen** [comment]
resized to 160gb

**Comment by praiskup** [comment]
Can you please update this? https://github.com/fedora-copr/ansible-fedora-copr/blob/main/group_vars/prod.yml#L18
