### ISSUE TITLE
Please enable high-performance builders for some of the @kernel-vanilla coprs – or all if appropriate

### ISSUE THREAD

**Issue by knurd** [fedora-copr/copr#3512]
Please enable high-performance builders for the @kernel-vanilla coprs packages shipping stable(|-rc) kernels for Fedora Linux releases. The RE should look like this afaics[1]:

```
@kernel-vanilla/(fedora|fedora-rc|stable|stable-rc)/.*(x86_64|aarch64)/.*-releases
```

This is in preparation for next week, as the stable and stable-rc repos than will start shipping -rt kernel packages (fedora and fedora-rc will follow three week later), which will double the build time. This can already be seen in my mainline builds, which take 3 to 6 hours on arm64 and x86_64 since I enabled -rt subpackages there. To see, compare these two:
https://copr.fedorainfracloud.org/coprs/g/kernel-vanilla/mainline-wo-mergew/build/8204411/
https://copr.fedorainfracloud.org/coprs/g/kernel-vanilla/mainline-wo-mergew/build/8211067/

For the daily mainline and rawhide builds a quicker build time would be nice to have, too, but is not that crucial -- but if you think they are worth high-performance builders as well I'd be happy to get them.

But for stable and stable-rc kernels targeting Fedora Linux release it afaics would be worth reducing the time to build.

[1] side note: I think the example at the end of https://docs.pagure.org/copr.copr/user_documentation/powerful_builders.html#high-performance-builders needs a 's!kernel/.(x86_64!kernel/.*(x86_64!' (example does not escape special characters for readability).

**Comment by nikromen** [comment]
Hello I included the projects in our scripts here: https://pagure.io/fedora-infra/ansible/pull-request/2383 but I didn't merge it yet because of this:

> For the daily mainline and rawhide builds a quicker build time would be nice to have, too, but is not that crucial -- but if you think they are worth high-performance builders as well I'd be happy to get them.

yep this seems like a valid use case, so if it helps you, you can paste here additional regex for the projects you want to apply that :)

**Comment by knurd** [comment]
> yep this seems like a valid use case, so if it helps you, you can paste here additional regex for the projects you want to apply that :)

Cool, many thx. In that case replace the previously added RE with this one:

```
@kernel-vanilla/.*/.*(x86_64|aarch64)/.*
```

This seems pretty broad, but right now those repos don't build anything other than kernels.

**Comment by nikromen** [comment]
just note that enabling everyting in this repo means that if you will build packages that takes short amount of time (e.g. 5 minutes) you will wait a lot longer because it takes a while before the powerful machines boots up for you, so use different repo for smaller packages

**Comment by knurd** [comment]
Thx!

> just note that enabling everything in this repo means that […]

Don't worry, I read that in the documentation. :-D But right now there are no such packages, only kernels that take quite a while to build. If that changes I'll file a request to adjust things.
