### ISSUE TITLE
sporadic checksum mismatch

### ISSUE THREAD

**Issue by RoyalOughtness** [fedora-copr/copr#3546]
Seeing this after our recent build:

```
error: Downloading from 'copr:copr.fedorainfracloud.org:secureblue:hardened-chromium': Cannot download 08340627-hardened-chromium/hardened-chromium-common-131.0.6778.108-1.x86_64.rpm: All mirrors were tried; Last error: Downloading successful, but checksum doesn't match. Calculated: 4359c2f3b2ba8070ee4bd7aaaf7eb9a5fffa42f3292573b219e68e54679e20f3(sha256)  Expected: 8ffd6a52379417592935511c08108fbfa0e59a06c995866eda1c17ba5b51545b(sha256) 
```

Only happens sometimes, a retry or two fixes it. Maybe one of the copr data nodes has a corrupt package?

**Comment by praiskup** [comment]
Thank you for the report. 

I believe you were hitting yesterday's outage problems (we had two 15-minute slots with non-working repositories)
https://pagure.io/fedora-infrastructure/issue/12316

> Maybe one of the copr data nodes has a corrupt package?

There's just one server, distributed via Amazon CloudFront CDN.

**Comment by RoyalOughtness** [comment]
@praiskup 

> Amazon CloudFront CDN

Potentially one of the CDN nodes has a corrupt artifact?

This was last seen 10 minutes ago, so it wasn't resolved.

**Comment by RoyalOughtness** [comment]
And it's still only seen sporadically. Also, using a VPN while installing it fixes the issue, except in uswest it seems.

**Comment by RoyalOughtness** [comment]
Also, it appears to no longer be sporadic: https://github.com/RoyalOughtness/secureblue-dev/actions/runs/12186155638/job/33994004055

**Comment by RoyalOughtness** [comment]
going to attempt a rebuild as a mitigation.

**Comment by praiskup** [comment]
> Potentially one of the CDN nodes has a corrupt artifact?

That would explain it?  Not sure.  Reopening, please let us know how it goes - I don't seem to be able to reproduce this.

**Comment by RoyalOughtness** [comment]
@praiskup the rebuild fixed it

¯\_(ツ)_/¯

**Comment by praiskup** [comment]
Ok, thank you for the report @RoyalOughtness - if it appears again, please reopen, I would take a closer look. Sorry for the inconvenience.

**Comment by RoyalOughtness** [comment]
No problem, will do
