### ISSUE TITLE
Get logs from down'ed vm?

### ISSUE THREAD

**Issue by dschwoerer** [fedora-copr/copr#3551]
I am trying to figure out a random failure (random segfault). I tried running the test suite a few times.

I had one run where I saw a few failures, and when I came back later, the failures had disappeared.
Looking at the backend.log, I saw that the VM went unresponsive and a new VM has been used.

Is there some way to get the last log from the first VM?
Maybe even some additional logs?

[This is the backend.log](https://download.copr.fedorainfracloud.org/results/davidsch/testing/fedora-rawhide-x86_64/08367401-python-xbout/backend.log) and [this the link to the build](https://copr.fedorainfracloud.org/coprs/davidsch/testing/build/8367401/).

Logs would be appreciated :-)
If that can crash a VM, I am not eager to test this locally.

**Comment by FrostyX** [comment]
> Is there some way to get the last log from the first VM?
> Maybe even some additional logs?

Unfortunately no, the builder machines are removed.
But this may help you debug the issue https://frostyx.cz/posts/ssh-access-to-copr-builders

**Comment by nikromen** [comment]
Looking at the backend logs I can see that the VM booted successfully after a few attempts and the build was successful. What I can see is that the ssh to the VM failed to `54.208.45.94` which is - to my knowledge - VM in aws. After some retries, the aws VM was discarded and it got new one `2620:52:3:1:dead:beef:cafe:c193` (not aws). This really could be just aws issue - for these cases, we have the retry feature there. Can you confirm this was just one-timer or does it happen regularly?
