### ISSUE TITLE
s390x outage: distribute the IBM Cloud quota across multiple locations

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#3558]
Ashraf Vazeer wrote this:
> I just got suggestion from the IBM SRE team to spread the VMs across 3
> Madrid regions (mad1, mad2, mad3).  They are experiencing high load in
> us-east and hence the request.

**Comment by praiskup** [comment]
We had to partly evacuate the us-east location for now (9 machines only in total, max 2 machines per user). Therefore the s390x build processing is much slower.

**Comment by mohammedzee1000** [comment]
Thanks for taking care of this

**Comment by praiskup** [comment]
This config option doesn't seem to have the desired effect:
```
# Do not let one user waste the whole architecture capacity
build_max_workers_arch_per_owner=s390x=2
```
All the machines are taking by two owners :-/

**Comment by praiskup** [comment]
Per request, we had to evacuate the supported us-east1 location entirely, which effectively means we are out of s390x workers right now :-( sorry for the inconvenience.

**Comment by praiskup** [comment]
Redirected to Madrid and São Paulo. Happy building!
