### ISSUE TITLE
epel-10-x86_64 mock config mismatch

### ISSUE THREAD

**Issue by carlwgeorge** [fedora-copr/copr#3560]
In a [newly created copr](https://copr.fedorainfracloud.org/coprs/carlwgeorge/achillobator-incubator/), I enabled the `epel-10-x86_64` chroot and attempted [a build](https://copr.fedorainfracloud.org/coprs/carlwgeorge/achillobator-incubator/build/8428272/).  This same build worked for me locally with `mock-core-configs-41.5-1.fc41`, but it failed in copr.  The [log file](https://download.copr.fedorainfracloud.org/results/carlwgeorge/achillobator-incubator/epel-10-x86_64/08428272-rust-lexiclean/root.log.gz) indicates a 404 error trying to ask mirrormanager for https://mirrors.fedoraproject.org/metalink?repo=epel-&arch=x86_64 (note the missing version on the repo parameter).  I downloaded the [build configs](https://download.copr.fedorainfracloud.org/results/carlwgeorge/achillobator-incubator/epel-10-x86_64/08428272-rust-lexiclean/configs.tar.gz), and noticed something strange.

It appears to be using [epel-10.tpl from mock-core-configs-41.5-1](https://github.com/rpm-software-management/mock/blob/mock-core-configs-41.5-1/mock-core-configs/etc/mock/templates/epel-10.tpl), but [centos-stream-10.tpl from mock-core-configs-41.4-1](https://github.com/rpm-software-management/mock/blob/mock-core-configs-41.4-1/mock-core-configs/etc/mock/templates/centos-stream-10.tpl).  In https://github.com/rpm-software-management/mock/commit/a80df1cffad7ec6ed79f67d4ea25348b57701917 (part of mock-core-configs-41.5-1, but not mock-core-configs-41.4-1) we defined the jinja variable `releasever_major` and use it in the EPEL metalink.  Having a mismatch between those files results in the variable being undefined.

**Comment by praiskup** [comment]
Ah, forgotten work-arounds from early days... should be fixed now:
https://pagure.io/fedora-infra/ansible/c/8cdb4e1fbdfac269b4fb81c6afc9c3c00d40d6f1
Thank you for the report!

**Comment by carlwgeorge** [comment]
Thanks for the quick fix!
